// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { switchPlaygroundControls } from './switchPlaygroundSchema';

export type SwitchPlaygroundValue = {
  checked: boolean;
  disabled: boolean;
  required: boolean;
  invalid: boolean;
};

type SwitchPlaygroundProps = {
  platform: 'react' | 'react-native';
  renderSwitch: (
    value: SwitchPlaygroundValue,
    onChange: <K extends keyof SwitchPlaygroundValue>(
      key: K,
      nextValue: SwitchPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialSwitchPlaygroundValue: SwitchPlaygroundValue = {
  checked: false,
  disabled: false,
  required: false,
  invalid: false,
};

export function SwitchPlayground({
  platform,
  renderSwitch,
}: SwitchPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<SwitchPlaygroundValue>(
    initialSwitchPlaygroundValue
  );

  const update = (
    key: keyof SwitchPlaygroundValue,
    nextValue: SwitchPlaygroundValue[keyof SwitchPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='auto'
      controls={
        <PlaygroundControlsFromSchema
          platform={platform}
          value={value}
          controls={switchPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderSwitch(value, update)}
    </ComponentPlayground>
  );
}
