// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const reactSwitchApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Switch',
    props: [
      {
        name: 'checked',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'defaultChecked',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'required',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'invalid',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'onCheckedChange',
        type: '((checked: boolean) => void)',
        description: 'Prop for Switch.',
      },
    ],
  },
];

const nativeSwitchApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Switch',
    props: [
      {
        name: 'checked',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'defaultChecked',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'required',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'invalid',
        type: 'boolean',
        description: 'Prop for Switch.',
      },
      {
        name: 'onCheckedChange',
        type: '((checked: boolean) => void)',
        description: 'Prop for Switch.',
      },
    ],
  },
];

const inheritedReactSwitchApi: readonly ComponentApiProp[] = [];

const inheritedNativeSwitchApi: readonly ComponentApiProp[] = [];

export const switchApi = {
  react: {
    sections: reactSwitchApiSections,
    inheritedProps: inheritedReactSwitchApi,
  },
  'react-native': {
    sections: nativeSwitchApiSections,
    inheritedProps: inheritedNativeSwitchApi,
  },
} as const;
