// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Switch } from '@vellira-ui/react';

import { SwitchPlayground } from './SwitchPlayground';

export function SwitchDemo() {
  return (
    <SwitchPlayground
      platform='react'
      renderSwitch={(value, onChange) => (
        <Switch
          checked={value.checked}
          onCheckedChange={(nextValue) => onChange('checked', nextValue)}
          disabled={value.disabled}
          required={value.required}
          invalid={value.invalid}
        />
      )}
    />
  );
}
