// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type SwitchAccessibilityProps = {
  platform: ComponentPlatform;
};

export function SwitchAccessibility({ platform }: SwitchAccessibilityProps) {
  const reactItems = [
    {
      title: 'Accessible naming',
      description:
        'Provide a visible label or another accessible name that clearly identifies the control.',
    },
    {
      title: 'State communication',
      description:
        'Expose the current interactive state through the appropriate native semantics and keep it synchronized with the visual state.',
      props: ['checked'],
    },
    {
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    },
    {
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    },
    {
      title: 'Keyboard and focus',
      description:
        'Preserve expected keyboard interaction and visible focus behavior.',
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Accessible naming',
      description:
        'Provide a visible label or accessibilityLabel so screen readers can identify the control.',
      props: ['accessibilityLabel'],
    },
    {
      title: 'State communication',
      description:
        'Expose the current interactive state through React Native accessibilityState and keep it synchronized with the visual state.',
      props: ['checked'],
    },
    {
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    },
    {
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    },
    {
      title: 'Keyboard and focus',
      description:
        'Verify focus and screen reader interaction on supported React Native platforms.',
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
