// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialSwitchPlaygroundValue,
  type SwitchPlaygroundValue,
} from './SwitchPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type SwitchUsageProps = {
  platform: ComponentPlatform;
};

function createSwitchCode(
  platform: ComponentPlatform,
  value: SwitchPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children = platform === 'react' ? `` : ``;

  if (value.checked) {
    props.push('checked');
  }

  if (value.disabled) {
    props.push('disabled');
  }

  if (value.required) {
    props.push('required');
  }

  if (value.invalid) {
    props.push('invalid');
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Switch } from '${packageName}';
${platform === 'react' ? `` : ``}

<Switch${propsText}/>`;
  }

  return `import { Switch } from '${packageName}';
${platform === 'react' ? `` : ``}

<Switch${propsText}>
${children}
</Switch>`;
}

export function SwitchUsage({ platform }: SwitchUsageProps) {
  const [value] = useComponentDemoState<SwitchPlaygroundValue>(
    initialSwitchPlaygroundValue
  );

  const code = createSwitchCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
