import type { ComponentType } from 'react';

export interface BlogMDXModule {
  default: ComponentType;
}

export type BlogMDXModuleLoader = () => Promise<BlogMDXModule>;

/**
 * Generated by Blog V1 authoring tooling.
 *
 * Keep MDX imports statically analyzable for Next.js/Turbopack.
 */
const blogArticleModuleLoaders: Readonly<Record<string, BlogMDXModuleLoader>> =
  {};

export function getBlogArticleModuleLoader(
  slug: string
): BlogMDXModuleLoader | null {
  return blogArticleModuleLoaders[slug] ?? null;
}
