import fs from 'node:fs';
import path from 'node:path';

import ts from 'typescript';

type Platform = 'react' | 'react-native';

type GeneratedPlatformChildren = Partial<Record<Platform, string>>;

type GeneratedPlatformImports = Partial<Record<Platform, readonly string[]>>;

type GeneratedApiSectionModel = {
  name: string;
  props: readonly ExtractedProp[];
};

type GeneratedApiModel = Record<
  Platform,
  {
    sections: readonly GeneratedApiSectionModel[];
    inheritedProps: readonly ExtractedProp[];
  }
>;

type GeneratedPageModel = {
  componentName: string;
  slug: string;
  platforms: readonly Platform[];
  demo: {
    staticProps: Partial<Record<Platform, string>>;
    children: GeneratedPlatformChildren;
    imports: GeneratedPlatformImports;
    responsivePresentation: boolean;
  };
  playground: {
    props: readonly ExtractedProp[];
    initialValues: Record<string, string | boolean | number>;
  };
  usage: {
    children: GeneratedPlatformChildren;
  };
  examples: readonly GeneratedExample[];
  accessibility: Record<Platform, readonly AccessibilityItem[]>;
  api: GeneratedApiModel;
  related: readonly string[];
};

const [, , componentName, ...args] = process.argv;

const force = args.includes('--force');
const check = args.includes('--check');

if (!componentName) {
  console.error(
    'Usage: pnpm create:component-page ComponentName [--force] [--check]'
  );
  process.exit(1);
}

const root = process.cwd();

const velliraApiSourceRoots = [
  path.join(root, 'packages', 'types', 'src'),
  path.join(root, 'packages', 'types', 'dist'),
  path.join(root, 'packages', 'react', 'src'),
  path.join(root, 'packages', 'react', 'dist'),
  path.join(root, 'packages', 'react-native', 'src'),
  path.join(root, 'packages', 'react-native', 'dist'),
].map((sourceRoot) => path.normalize(sourceRoot));

const slug = componentName.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const generatedFileHeader = `// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

`;

const checkFailures: string[] = [];

function isPathInside(filePath: string, directoryPath: string) {
  const relativePath = path.relative(directoryPath, filePath);

  return (
    Boolean(relativePath) &&
    !relativePath.startsWith('..') &&
    !path.isAbsolute(relativePath)
  );
}

type ComponentProfile =
  | 'primitive'
  | 'form-control'
  | 'selection-control'
  | 'compound'
  | 'overlay'
  | 'navigation';

type PlatformComponentConfig = {
  demoProps?: string;
  children?: string;
  imports?: readonly string[];
  responsivePresentation?: boolean;
};

type DemoConfig = {
  label?: string;
  description?: string;
  excludeControls?: readonly string[];
  initialValues?: Record<string, string | boolean | number>;
  staticProps?: Record<string, string>;
  satisfiedRequiredProps?: readonly string[];
  previewWidth?: 'auto' | 'field' | 'full';
};

type ExampleConfig = {
  title: string;
  description: string;
  props: readonly string[];
  imports?: readonly string[];
  reactImports?: readonly string[];
  nativeImports?: readonly string[];
  reactProps?: readonly string[];
  nativeProps?: readonly string[];
  reactChildren?: string;
  nativeChildren?: string;
  platforms?: readonly Platform[];
};

type ApiConfig = {
  sections?: readonly {
    name: string;
    exportName: string | Partial<Record<Platform, string>>;
  }[];
  descriptions?: Record<string, string>;
};

type AccessibilityConfig = {
  react?: readonly {
    title: string;
    description: string;
    props?: readonly string[];
  }[];

  native?: readonly {
    title: string;
    description: string;
    props?: readonly string[];
  }[];
};

type ComponentGeneratorConfig = {
  profile?: ComponentProfile;
  react?: PlatformComponentConfig;
  native?: PlatformComponentConfig;
  demo?: DemoConfig;
  defaults?: {
    shared?: Record<string, string | boolean | number>;
    react?: Record<string, string | boolean | number>;
    native?: Record<string, string | boolean | number>;
  };
  examples?: readonly ExampleConfig[];
  api?: ApiConfig;
  apiSections?: ApiConfig['sections'];
  apiDescriptions?: Record<string, string>;
  accessibility?: AccessibilityConfig;
  related?: readonly string[];
};

const componentMetadataOverrides: Record<string, ComponentGeneratorConfig> = {
  Button: {
    react: {
      children: 'Button',
    },
    native: {
      children: 'Button',
    },
    demo: {
      initialValues: {
        color: 'primary',
        appearance: 'solid',
        size: 'md',
        shape: 'pill',
        fullWidth: false,
        loading: false,
        disabled: false,
        iconOnly: false,
      },
    },

    defaults: {
      shared: {
        color: 'primary',
        appearance: 'solid',
        size: 'md',
        shape: 'pill',
        fullWidth: false,
        loading: false,
        disabled: false,
        iconOnly: false,
      },

      react: {
        asChild: false,
      },
    },

    examples: [
      {
        title: 'Basic',
        description: 'Primary action button.',
        props: [],
      },
      {
        title: 'Appearance and color',
        description: 'Alternative surface and semantic action tone.',
        props: [`appearance='outline'`, `color='danger'`],
      },
      {
        title: 'Icons',
        description: 'Icons clarify the action without replacing the label.',
        imports: [`import { ArrowRight, Download } from '@vellira-ui/icons';`],
        props: ['iconStart={<Download />}', 'iconEnd={<ArrowRight />}'],
      },
      {
        title: 'Icon-only',
        description: 'Compact action with an accessible name.',
        imports: [`import { Plus } from '@vellira-ui/icons';`],
        props: ['iconOnly', 'iconStart={<Plus />}'],
        reactProps: [`aria-label='Add item'`],
        nativeProps: [`accessibilityLabel='Add item'`],
        reactChildren: '',
        nativeChildren: '',
      },
      {
        title: 'Loading',
        description: 'Shows progress and prevents interaction.',
        props: ['loading', `loadingText='Saving...'`],
      },
      {
        title: 'Disabled',
        description: 'Disabled action state.',
        props: ['disabled'],
      },
      {
        title: 'Full width',
        description: 'Button expands to fill its container.',
        props: ['fullWidth'],
      },
      {
        title: 'Size and shape',
        description: 'Large rounded button treatment.',
        props: [`size='lg'`, `shape='rounded'`],
      },
      {
        title: 'Composed link',
        description: 'Composes button styling onto a custom React link.',
        props: ['asChild'],
        reactChildren: `<a href='/components/button'>Button</a>`,
        platforms: ['react'],
      },
      {
        title: 'Press handler',
        description: 'Handles native press interaction.',
        props: [],
        nativeProps: ['onPress={() => {}}'],
        platforms: ['react-native'],
      },
    ],

    accessibility: {
      react: [
        {
          title: 'Accessible names',
          description:
            'Use visible text for normal buttons and aria-label or aria-labelledby for icon-only actions.',
          props: ['children', 'iconOnly', 'aria-label', 'aria-labelledby'],
        },
        {
          title: 'Loading and disabled state',
          description:
            'Loading buttons expose busy state and prevent interaction while preserving the button label.',
          props: ['loading', 'loadingText', 'disabled'],
        },
        {
          title: 'Composed semantics',
          description:
            'When using asChild, pass semantic attributes and href to the child element.',
          props: ['asChild', 'href', 'type'],
        },
      ],
      native: [
        {
          title: 'Accessible names',
          description:
            'Use visible text for normal buttons and accessibilityLabel for icon-only actions.',
          props: ['children', 'iconOnly', 'accessibilityLabel'],
        },
        {
          title: 'Loading and disabled state',
          description:
            'Loading buttons announce disabled interaction through React Native accessibility state.',
          props: ['loading', 'loadingText', 'disabled'],
        },
        {
          title: 'Press handling',
          description:
            'Keep onPress actions predictable and provide an accessibilityHint when the result is not obvious.',
          props: ['onPress', 'accessibilityHint'],
        },
      ],
    },

    related: ['input', 'checkbox', 'modal'],
  },

  Input: {
    demo: {
      label: 'Email',
      description: 'Used for account notifications.',
      initialValues: {
        placeholder: 'name@example.com',
        size: 'md',
        color: 'primary',
        variant: 'outline',
        disabled: false,
        readOnly: false,
        required: false,
        invalid: false,
        loading: false,
        clearable: false,
        revealPassword: false,
        showCounter: false,
        error: '',
      },
      previewWidth: 'field',
    },

    defaults: {
      shared: {
        size: 'md',
        color: 'primary',
        variant: 'outline',
        disabled: false,
        readOnly: false,
        required: false,
        invalid: false,
        loading: false,
        clearable: false,
        revealPassword: false,
        showCounter: false,
      },

      react: {
        type: 'text',
        startIconTone: 'default',
        endIconTone: 'default',
        clearIconTone: 'danger',
      },

      native: {
        type: 'text',
        startIconTone: 'default',
        endIconTone: 'default',
        clearIconTone: 'danger',
      },
    },

    examples: [
      {
        title: 'Basic',
        description: 'Labeled text input.',
        props: [],
      },
      {
        title: 'Clearable',
        description: 'Shows a clear action when a value is present.',
        props: ['clearable', `defaultValue='Acme Inc.'`],
      },
      {
        title: 'Loading',
        description: 'Shows progress while the field is waiting on work.',
        props: ['loading', `defaultValue='Checking...'`],
      },
      {
        title: 'Error',
        description: 'Validation feedback state.',
        props: [`error='Enter a valid email.'`],
      },
      {
        title: 'Read only',
        description: 'Preserves value display without allowing edits.',
        props: ['readOnly', `defaultValue='readonly@example.com'`],
      },
      {
        title: 'Password',
        description: 'Password input with reveal control.',
        props: [`type='password'`, 'revealPassword'],
      },
      {
        title: 'Counter',
        description: 'Character count when maxLength is set.',
        props: ['showCounter', 'maxLength={80}'],
      },
    ],

    accessibility: {
      react: [
        {
          title: 'Labels and descriptions',
          description:
            'Use label and description text so the input purpose and expected value are clear.',
          props: ['label', 'description', 'placeholder'],
        },
        {
          title: 'Validation feedback',
          description:
            'Expose error and invalid state with text that explains how to resolve the issue.',
          props: ['error', 'invalid', 'required'],
        },
        {
          title: 'Read-only and disabled fields',
          description:
            'Use readOnly when values should remain focusable and disabled only when interaction is unavailable.',
          props: ['readOnly', 'disabled'],
        },
      ],
      native: [
        {
          title: 'Labels and hints',
          description:
            'Use visible label text and accessibility hints when the expected input is not obvious.',
          props: ['label', 'description', 'accessibilityHint'],
        },
        {
          title: 'Validation feedback',
          description:
            'Expose error text and invalid state so screen reader users receive the same feedback.',
          props: ['error', 'invalid', 'required'],
        },
        {
          title: 'Keyboard input',
          description:
            'Choose the appropriate input type and keyboard behavior for the value being entered.',
          props: ['type', 'keyboardType', 'returnKeyType'],
        },
      ],
    },

    related: ['form-field', 'select', 'checkbox'],
  },

  Radio: {
    react: {
      demoProps: 'value="option"',
    },
    native: {
      demoProps: 'value="option"',
    },
    demo: {
      label: 'Email notifications',
      description: 'Receive updates by email.',
      excludeControls: ['value', 'required'],
      initialValues: {
        size: 'md',
        color: 'primary',
        checked: false,
        disabled: false,
        error: '',
      },
      previewWidth: 'field',
    },

    defaults: {
      shared: {
        defaultChecked: false,
        disabled: false,
        required: false,
        size: 'md',
        color: 'primary',
      },
    },

    examples: [
      {
        title: 'Basic',
        description: 'Standalone radio option.',
        props: [],
      },
      {
        title: 'Selected',
        description: 'Selected state.',
        props: ['checked'],
      },
      {
        title: 'Disabled',
        description: 'Disabled state.',
        props: ['disabled'],
      },
      {
        title: 'Required',
        description: 'Required form control.',
        props: ['required'],
      },
      {
        title: 'Error',
        description: 'Validation error state.',
        props: [`error='Please choose an option.'`],
      },
      {
        title: 'Size and color',
        description: 'Large semantic radio treatment.',
        props: [`size='lg'`, `color='success'`],
      },
    ],

    related: ['radio-group', 'checkbox', 'select'],
  },

  Select: {
    react: {
      children: `<Select.Item value='react'>React</Select.Item>
<Select.Item value='vue'>Vue</Select.Item>
<Select.Item value='svelte'>Svelte</Select.Item>`,
    },

    native: {
      responsivePresentation: true,
      children: `<Select.Item value='react' label='React' />
<Select.Item value='vue' label='Vue' />
<Select.Item value='svelte' label='Svelte' />`,
    },

    demo: {
      label: 'Favorite framework',
      description: 'Choose one option.',
      satisfiedRequiredProps: ['options'],
      excludeControls: [
        'multiple',
        'label',
        'description',
        'required',
        'maxSelected',
        'closeOnSelect',
        'avoidCollisions',
        'modal',
        'command',
      ],
      initialValues: {
        multiple: false,
        placeholder: 'Select an option',
        size: 'md',
        color: 'primary',
        variant: 'outline',
        invalid: false,
        loading: false,
        clearable: false,
        searchable: false,
        disabled: false,
        error: '',
      },
    },

    defaults: {
      shared: {
        multiple: false,
        placeholder: 'Select...',
        size: 'md',
        color: 'primary',
        variant: 'outline',
        invalid: false,
        loading: false,
        clearable: false,
        searchable: false,
        closeOnSelect: false,
        required: false,
        disabled: false,
      },

      react: {
        modal: false,
        command: false,
        matchTriggerWidth: true,
        avoidCollisions: true,
        portal: true,
        defaultOpen: false,
        placement: 'bottom',
      },

      native: {
        presentation: 'auto',
        placement: 'bottom-start',
        offset: 8,
        matchTriggerWidth: false,
        dismissOnBackdropPress: true,
        defaultOpen: false,
      },
    },

    examples: [
      {
        title: 'Basic',
        description: 'Basic component usage.',
        props: [],
      },
      {
        title: 'Searchable',
        description: 'Filter options by typing a search query.',
        props: ['searchable'],
      },
      {
        title: 'Multiple',
        description: 'Select more than one option.',
        props: ['multiple'],
      },
      {
        title: 'Error',
        description: 'Validation error state.',
        props: [`error='Please review this option.'`],
      },
      {
        title: 'Disabled',
        description: 'Disabled select state.',
        props: ['disabled'],
      },
      {
        title: 'Loading',
        description: 'Loading state while options are being resolved.',
        props: ['loading'],
      },
    ],

    apiDescriptions: {
      multiple: 'Enables multiple selection when true.',
      value: 'Controlled selected value or values.',
      defaultValue: 'Initial selected value or values for uncontrolled usage.',
      onValueChange: 'Called when the selected value or values change.',
    },

    apiSections: [
      { name: 'Select.Item', exportName: 'SelectItemProps' },
      { name: 'Select.Trigger', exportName: 'SelectTriggerSlotProps' },
      {
        name: 'Select.Value',
        exportName: {
          react: 'SelectValueProps',
          'react-native': 'SelectValueSlotProps',
        },
      },
      {
        name: 'Select.Content',
        exportName: {
          react: 'SelectContentSlotProps',
          'react-native': 'SelectContentProps',
        },
      },
      { name: 'Select.Search', exportName: 'SelectSearchProps' },
      { name: 'Select.Group', exportName: 'SelectGroupProps' },
      { name: 'Select.Label', exportName: 'SelectLabelProps' },
      { name: 'Select.Separator', exportName: 'SelectSeparatorProps' },
      { name: 'Select.Empty', exportName: 'SelectEmptyProps' },
      { name: 'Select.Loading', exportName: 'SelectLoadingProps' },
    ],

    accessibility: {
      react: [
        {
          title: 'Accessible naming',
          description:
            'Provide a visible label or another accessible name for the select trigger.',
          props: ['label', 'description'],
        },
        {
          title: 'Keyboard interaction',
          description:
            'Preserve expected keyboard navigation, focus management, and option selection behavior.',
          props: ['open', 'defaultOpen', 'searchable'],
        },
        {
          title: 'Selection state',
          description:
            'Keep selected values and expanded state synchronized with the visual interface.',
          props: ['value', 'defaultValue', 'multiple'],
        },
        {
          title: 'Validation feedback',
          description:
            'Associate validation feedback with the control and expose invalid and required state.',
          props: ['error', 'invalid', 'required', 'disabled'],
        },
      ],

      native: [
        {
          title: 'Accessible naming',
          description:
            'Provide a visible label or accessibilityLabel so screen readers can identify the control.',
          props: ['label', 'accessibilityLabel', 'accessibilityHint'],
        },
        {
          title: 'Screen reader interaction',
          description:
            'Expose expanded, selected, disabled, and busy state through React Native accessibility semantics.',
          props: ['value', 'multiple', 'disabled', 'loading'],
        },
        {
          title: 'Search and selection',
          description:
            'Keep search, active option, and selected values understandable when using assistive technologies.',
          props: ['searchable', 'searchPlaceholder', 'multiple'],
        },
        {
          title: 'Validation feedback',
          description:
            'Expose validation errors and required state without relying only on visual styling.',
          props: ['error', 'invalid', 'required'],
        },
      ],
    },

    related: ['input', 'dropdown', 'radio-group'],
  },

  Checkbox: {
    demo: {
      label: 'Accept terms',
      description: 'Required before continuing.',
      initialValues: {
        checked: false,
        disabled: false,
        indeterminate: false,
        required: false,
        size: 'md',
        color: 'primary',
        labelPosition: 'end',
        error: '',
      },
      previewWidth: 'field',
    },
    defaults: {
      shared: {
        defaultChecked: false,
        disabled: false,
        required: false,
        indeterminate: false,
        size: 'md',
        color: 'primary',
        labelPosition: 'end',
      },
    },
    examples: [
      { title: 'Basic', description: 'Binary selection control.', props: [] },
      { title: 'Checked', description: 'Selected state.', props: ['checked'] },
      {
        title: 'Indeterminate',
        description: 'Mixed state for partial selections.',
        props: ['indeterminate'],
      },
      {
        title: 'Disabled',
        description: 'Disabled state.',
        props: ['disabled'],
      },
      {
        title: 'Error',
        description: 'Validation feedback state.',
        props: [`error='Accept the terms to continue.'`],
      },
    ],
    accessibility: {
      react: [
        {
          title: 'Accessible naming',
          description:
            'Use the visible label or another accessible name to describe the checked state.',
          props: ['label', 'aria-label'],
        },
        {
          title: 'Mixed state',
          description:
            'Expose indeterminate state only when it represents a real partial selection.',
          props: ['indeterminate', 'checked'],
        },
        {
          title: 'Validation feedback',
          description:
            'Pair required and error state with clear text guidance.',
          props: ['required', 'error'],
        },
      ],
      native: [
        {
          title: 'Accessible naming',
          description:
            'Use the visible label or accessibilityLabel to identify the checkbox.',
          props: ['label', 'accessibilityLabel'],
        },
        {
          title: 'State communication',
          description:
            'Keep checked, indeterminate, disabled, and required state synchronized with React Native accessibility state.',
          props: ['checked', 'indeterminate', 'disabled', 'required'],
        },
      ],
    },
    related: ['radio', 'radio-group', 'select'],
  },

  Dropdown: {
    react: {
      children: `<Dropdown.Trigger>Actions</Dropdown.Trigger>
<Dropdown.Content>
  <Dropdown.Item>Profile</Dropdown.Item>
  <Dropdown.Item>Settings</Dropdown.Item>
  <Dropdown.Separator />
  <Dropdown.Item color='danger'>Sign out</Dropdown.Item>
</Dropdown.Content>`,
    },
    native: {
      responsivePresentation: true,
      children: `<Dropdown.Trigger>Actions</Dropdown.Trigger>
<Dropdown.Content>
  <Dropdown.Item value='profile'>Profile</Dropdown.Item>
  <Dropdown.Item value='settings'>Settings</Dropdown.Item>
  <Dropdown.Separator />
  <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>
</Dropdown.Content>`,
    },
    demo: {
      initialValues: {
        size: 'md',
        color: 'primary',
        disabled: false,
        loading: false,
        searchable: false,
        command: false,
      },
    },
    defaults: {
      shared: {
        size: 'md',
        color: 'primary',
        disabled: false,
        loading: false,
        closeOnSelect: true,
        searchable: false,
        command: false,
      },
      react: {
        portal: true,
        avoidCollisions: true,
        modal: false,
        loop: true,
        offset: 8,
      },
      native: {
        presentation: 'auto',
        placement: 'bottom-start',
        offset: 8,
        showArrow: true,
      },
    },
    examples: [
      {
        title: 'Basic',
        description: 'Action menu with common items.',
        props: [],
      },
      {
        title: 'Searchable',
        description: 'Filter menu items.',
        props: ['searchable'],
      },
      {
        title: 'Loading',
        description: 'Loading menu state.',
        props: ['loading'],
      },
      {
        title: 'Disabled',
        description: 'Disabled trigger state.',
        props: ['disabled'],
      },
    ],
    apiSections: [
      { name: 'Dropdown.Trigger', exportName: 'DropdownTriggerProps' },
      { name: 'Dropdown.Content', exportName: 'DropdownContentProps' },
      { name: 'Dropdown.Search', exportName: 'DropdownSearchProps' },
      { name: 'Dropdown.Item', exportName: 'DropdownItemProps' },
      { name: 'Dropdown.Group', exportName: 'DropdownGroupProps' },
      { name: 'Dropdown.Label', exportName: 'DropdownLabelProps' },
      { name: 'Dropdown.Separator', exportName: 'DropdownSeparatorProps' },
      { name: 'Dropdown.Empty', exportName: 'DropdownEmptyProps' },
      { name: 'Dropdown.Loading', exportName: 'DropdownLoadingProps' },
    ],
    accessibility: {
      react: [
        {
          title: 'Trigger naming',
          description:
            'Use trigger content that clearly communicates the menu purpose.',
          props: ['children', 'aria-label'],
        },
        {
          title: 'Keyboard menu behavior',
          description:
            'Preserve arrow-key navigation, Escape dismissal, and focus return to the trigger.',
          props: ['loop', 'modal', 'open'],
        },
        {
          title: 'Item states',
          description:
            'Use disabled and color state to communicate unavailable or destructive actions.',
          props: ['disabled', 'color'],
        },
      ],
      native: [
        {
          title: 'Trigger naming',
          description:
            'Provide visible trigger text or accessibilityLabel for the menu trigger.',
          props: ['label', 'accessibilityLabel'],
        },
        {
          title: 'Presentation semantics',
          description:
            'Choose sheet, modal, or popover presentation based on screen size and interaction context.',
          props: ['presentation', 'placement'],
        },
        {
          title: 'Selection state',
          description:
            'Keep selected, disabled, and loading state reflected in item labels and accessibility state.',
          props: ['disabled', 'loading', 'onSelect'],
        },
      ],
    },
    related: ['button', 'select', 'popover'],
  },

  Tabs: {
    react: {
      children: `<Tabs.List>
  <Tabs.Trigger value='account'>Account</Tabs.Trigger>
  <Tabs.Trigger value='billing'>Billing</Tabs.Trigger>
</Tabs.List>
<Tabs.Content value='account'>Account settings</Tabs.Content>
<Tabs.Content value='billing'>Billing details</Tabs.Content>`,
    },
    native: {
      children: `<Tabs.List>
  <Tabs.Trigger value='account'>Account</Tabs.Trigger>
  <Tabs.Trigger value='billing'>Billing</Tabs.Trigger>
</Tabs.List>
<Tabs.Content value='account'><NativeText>Account settings</NativeText></Tabs.Content>
<Tabs.Content value='billing'><NativeText>Billing details</NativeText></Tabs.Content>`,
      imports: [`import { Text as NativeText } from 'react-native';`],
    },
    demo: {
      initialValues: {
        orientation: 'horizontal',
        activationMode: 'automatic',
        variant: 'line',
        color: 'primary',
        size: 'md',
        disabled: false,
      },
    },
    defaults: {
      shared: {
        orientation: 'horizontal',
        activationMode: 'automatic',
        loop: true,
        keepMounted: false,
        lazyMount: false,
        variant: 'line',
        color: 'primary',
        size: 'md',
        disabled: false,
      },
    },
    examples: [
      { title: 'Basic', description: 'Two-panel tab navigation.', props: [] },
      {
        title: 'Pills',
        description: 'Alternative visual treatment.',
        props: [`variant='pills'`],
      },
      {
        title: 'Manual activation',
        description: 'Focus tabs without selecting until activation.',
        props: [`activationMode='manual'`],
      },
      {
        title: 'Disabled',
        description: 'Disabled tab set.',
        props: ['disabled'],
      },
    ],
    apiSections: [
      { name: 'Tabs.List', exportName: 'TabsListProps' },
      { name: 'Tabs.Trigger', exportName: 'TabsTriggerProps' },
      { name: 'Tabs.Content', exportName: 'TabsContentProps' },
    ],
    accessibility: {
      react: [
        {
          title: 'Keyboard navigation',
          description:
            'Support arrow-key movement between triggers and preserve focus order.',
          props: ['orientation', 'activationMode', 'loop'],
        },
        {
          title: 'Panel relationships',
          description:
            'Each trigger value should match exactly one content panel value.',
          props: ['value', 'defaultValue'],
        },
      ],
      native: [
        {
          title: 'Screen reader state',
          description:
            'Expose the selected tab and associated panel content through React Native accessibility state.',
          props: ['value', 'defaultValue'],
        },
        {
          title: 'Activation behavior',
          description:
            'Use activation mode and orientation consistently with the platform navigation pattern.',
          props: ['activationMode', 'orientation'],
        },
      ],
    },
    related: ['radio-group', 'button'],
  },

  Modal: {
    react: {
      children: `<Modal.Trigger>Open modal</Modal.Trigger>
<Modal.Overlay />
<Modal.Content>
  <Modal.Header>
    <Modal.Title>Confirm action</Modal.Title>
    <Modal.Description>This action can be reviewed before continuing.</Modal.Description>
  </Modal.Header>
  <Modal.Body>Modal body content.</Modal.Body>
  <Modal.Footer>
    <Modal.Close aria-label='Cancel' />
  </Modal.Footer>
</Modal.Content>`,
    },
    native: {
      children: `<Modal.Trigger>Open modal</Modal.Trigger>
<Modal.Overlay>
  <Modal.Content>
    <Modal.Header>
      <Modal.Title>Confirm action</Modal.Title>
      <Modal.Description>This action can be reviewed before continuing.</Modal.Description>
    </Modal.Header>
    <Modal.Body>Modal body content.</Modal.Body>
    <Modal.Footer>
      <Modal.Close accessibilityLabel='Cancel' />
    </Modal.Footer>
  </Modal.Content>
</Modal.Overlay>`,
    },
    defaults: {
      shared: {
        closeOnOutsidePress: true,
        closeOnEscape: true,
        animation: 'scale',
        restoreFocus: true,
      },
      react: {
        modal: true,
        preventScroll: true,
        trapFocus: true,
        role: 'dialog',
      },
    },
    examples: [
      {
        title: 'Basic',
        description: 'Dialog with trigger and content.',
        props: [],
        reactChildren: `<Modal.Trigger>Open modal</Modal.Trigger>
<Modal.Overlay />
<Modal.Content>
  <Modal.Header>
    <Modal.Title>Confirm action</Modal.Title>
    <Modal.Description>This action can be reviewed before continuing.</Modal.Description>
  </Modal.Header>
  <Modal.Body>Modal body content.</Modal.Body>
  <Modal.Footer>
    <Modal.Close aria-label='Cancel' />
  </Modal.Footer>
</Modal.Content>`,
        nativeChildren: `<Modal.Trigger>Open modal</Modal.Trigger>
<Modal.Overlay>
  <Modal.Content>
    <Modal.Header>
      <Modal.Title>Confirm action</Modal.Title>
      <Modal.Description>This action can be reviewed before continuing.</Modal.Description>
    </Modal.Header>
    <Modal.Body>Modal body content.</Modal.Body>
    <Modal.Footer>
      <Modal.Close accessibilityLabel='Cancel' />
    </Modal.Footer>
  </Modal.Content>
</Modal.Overlay>`,
      },
      {
        title: 'No outside dismissal',
        description: 'Requires an explicit close action.',
        props: ['closeOnOutsidePress={false}'],
        reactChildren: `<Modal.Trigger>Open modal</Modal.Trigger>
<Modal.Overlay />
<Modal.Content>
  <Modal.Header>
    <Modal.Title>Confirm action</Modal.Title>
    <Modal.Description>This action can be reviewed before continuing.</Modal.Description>
  </Modal.Header>
  <Modal.Body>Modal body content.</Modal.Body>
  <Modal.Footer>
    <Modal.Close aria-label='Cancel' />
  </Modal.Footer>
</Modal.Content>`,
        nativeChildren: `<Modal.Trigger>Open modal</Modal.Trigger>
<Modal.Overlay>
  <Modal.Content>
    <Modal.Header>
      <Modal.Title>Confirm action</Modal.Title>
      <Modal.Description>This action can be reviewed before continuing.</Modal.Description>
    </Modal.Header>
    <Modal.Body>Modal body content.</Modal.Body>
    <Modal.Footer>
      <Modal.Close accessibilityLabel='Cancel' />
    </Modal.Footer>
  </Modal.Content>
</Modal.Overlay>`,
      },
    ],
    apiSections: [
      { name: 'Modal.Trigger', exportName: 'ModalTriggerProps' },
      { name: 'Modal.Overlay', exportName: 'ModalOverlayProps' },
      { name: 'Modal.Content', exportName: 'ModalContentProps' },
      { name: 'Modal.Header', exportName: 'ModalHeaderProps' },
      { name: 'Modal.Body', exportName: 'ModalBodyProps' },
      { name: 'Modal.Footer', exportName: 'ModalFooterProps' },
      { name: 'Modal.Close', exportName: 'ModalCloseProps' },
    ],
    accessibility: {
      react: [
        {
          title: 'Focus management',
          description:
            'Trap focus while open and restore focus to the trigger when the modal closes.',
          props: ['trapFocus', 'restoreFocus', 'initialFocus', 'finalFocus'],
        },
        {
          title: 'Dialog labelling',
          description:
            'Use title and description content so assistive technology can announce the dialog purpose.',
          props: ['role', 'children'],
        },
        {
          title: 'Dismissal',
          description:
            'Choose outside press and Escape dismissal behavior based on task criticality.',
          props: ['closeOnOutsidePress', 'closeOnEscape'],
        },
      ],
      native: [
        {
          title: 'Modal announcement',
          description:
            'Use title and description content so the modal purpose is announced clearly.',
          props: ['children'],
        },
        {
          title: 'Dismissal',
          description:
            'Provide an explicit close action when outside dismissal is disabled.',
          props: ['closeOnOutsidePress'],
        },
      ],
    },
    related: ['button', 'popover', 'tooltip'],
  },

  Popover: {
    react: {
      children: `<Popover.Trigger>Open popover</Popover.Trigger>
<Popover.Content>
  <Popover.Title>Details</Popover.Title>
  <Popover.Description>Contextual information for this control.</Popover.Description>
</Popover.Content>`,
    },
    native: {
      children: `<Popover.Trigger asChild>
  <NativeButton>Open popover</NativeButton>
</Popover.Trigger>
<Popover.Content>
  <Popover.Title>Details</Popover.Title>
  <Popover.Description>Contextual information for this control.</Popover.Description>
</Popover.Content>`,
      imports: [
        `import { Button as NativeButton } from '@vellira-ui/react-native';`,
      ],
    },
    defaults: {
      shared: {
        side: 'bottom',
        align: 'center',
        sideOffset: 8,
        avoidCollisions: true,
        modal: false,
      },
      react: {
        portal: true,
        strategy: 'absolute',
      },
    },
    examples: [
      {
        title: 'Basic',
        description: 'Floating contextual content.',
        props: [],
        nativeImports: [
          `import { Button as NativeButton } from '@vellira-ui/react-native';`,
        ],
      },
      {
        title: 'Top aligned',
        description: 'Alternative content placement.',
        props: [`side='top'`, `align='start'`],
        nativeImports: [
          `import { Button as NativeButton } from '@vellira-ui/react-native';`,
        ],
      },
      {
        title: 'Modal',
        description: 'Modal interaction semantics.',
        props: ['modal'],
        nativeImports: [
          `import { Button as NativeButton } from '@vellira-ui/react-native';`,
        ],
      },
    ],
    apiSections: [
      { name: 'Popover.Trigger', exportName: 'PopoverTriggerProps' },
      { name: 'Popover.Content', exportName: 'PopoverContentProps' },
      { name: 'Popover.Title', exportName: 'PopoverTitleProps' },
      { name: 'Popover.Description', exportName: 'PopoverDescriptionProps' },
      { name: 'Popover.Close', exportName: 'PopoverCloseProps' },
      { name: 'Popover.Arrow', exportName: 'PopoverArrowProps' },
      { name: 'Popover.Anchor', exportName: 'PopoverAnchorProps' },
    ],
    accessibility: {
      react: [
        {
          title: 'Trigger relationship',
          description:
            'Use trigger content and popover title or description to clarify the relationship.',
          props: ['children', 'open', 'onOpenChange'],
        },
        {
          title: 'Dismissal and focus',
          description:
            'Keep focus and dismissal predictable when content contains interactive controls.',
          props: ['modal', 'side', 'align'],
        },
      ],
      native: [
        {
          title: 'Context announcement',
          description:
            'Use title and description content so screen readers can identify popover purpose.',
          props: ['children'],
        },
        {
          title: 'Placement',
          description:
            'Choose placement that keeps content near its trigger without obscuring controls.',
          props: ['side', 'align'],
        },
      ],
    },
    related: ['button', 'tooltip', 'modal'],
  },

  Tooltip: {
    react: {
      children: `<Tooltip.Trigger>Hover for details</Tooltip.Trigger>
<Tooltip.Content>Helpful contextual label.</Tooltip.Content>`,
    },
    native: {
      children: `<Tooltip.Trigger>Press for details</Tooltip.Trigger>
<Tooltip.Content>Helpful contextual label.</Tooltip.Content>`,
    },
    defaults: {
      shared: {
        placement: 'top',
        disabled: false,
      },
    },
    examples: [
      {
        title: 'Basic',
        description: 'Contextual label for a trigger.',
        props: [],
      },
      {
        title: 'Placement',
        description: 'Alternative tooltip placement.',
        props: [`placement='bottom'`],
      },
      {
        title: 'Disabled',
        description: 'Disabled tooltip behavior.',
        props: ['disabled'],
      },
    ],
    apiSections: [
      { name: 'Tooltip.Trigger', exportName: 'TooltipTriggerProps' },
      { name: 'Tooltip.Content', exportName: 'TooltipContentProps' },
    ],
    accessibility: {
      react: [
        {
          title: 'Supplemental text',
          description:
            'Use tooltips for supplemental labels, not as the only way to complete a task.',
          props: ['children', 'disabled'],
        },
        {
          title: 'Delay behavior',
          description:
            'Choose open and close delays that keep hover and focus behavior predictable.',
          props: ['delay', 'onOpenChange'],
        },
      ],
      native: [
        {
          title: 'Supplemental text',
          description:
            'Keep tooltip content concise and make critical information available outside the tooltip.',
          props: ['children', 'disabled'],
        },
        {
          title: 'Placement',
          description:
            'Use placement that keeps the tooltip near its trigger without covering the control.',
          props: ['placement'],
        },
      ],
    },
    related: ['button', 'popover'],
  },
};

function inferComponentProfile(name: string): ComponentProfile {
  if (['Modal', 'Popover', 'Tooltip', 'Dropdown'].includes(name)) {
    return 'overlay';
  }

  if (['Tabs'].includes(name)) {
    return 'navigation';
  }

  if (['Select'].includes(name)) {
    return 'compound';
  }

  if (['Radio', 'Checkbox'].includes(name)) {
    return 'selection-control';
  }

  if (['Input', 'FormField'].includes(name)) {
    return 'form-control';
  }

  return 'primitive';
}

const componentConfig = componentMetadataOverrides[componentName] ?? {};

const componentProfile =
  componentConfig.profile ?? inferComponentProfile(componentName);

function getDemoProps(platform: Platform) {
  if (platform === 'react') {
    return componentConfig.react?.demoProps ?? '';
  }

  return componentConfig.native?.demoProps ?? '';
}

type ExtractedProp = {
  name: string;
  kind: 'boolean' | 'string' | 'number' | 'select' | 'other';
  required: boolean;
  type: string;
  description: string;
  sourceFilePath?: string;
  options?: string[];
};

const typesRoot = path.join(root, 'packages', 'types', 'src');

function findTypeSourceFile(name: string) {
  const candidates = [
    path.join(typesRoot, `${name}.ts`),
    path.join(typesRoot, `${name.charAt(0).toLowerCase()}${name.slice(1)}.ts`),
  ];

  return candidates.find((filePath) => fs.existsSync(filePath));
}

function findPlatformTypeSourceFile(
  platform: Platform,
  name: string
): string | undefined {
  const packageName = platform === 'react' ? 'react' : 'react-native';

  const packageRoot = path.join(root, 'packages', packageName, 'src');
  const stack = [packageRoot];

  while (stack.length > 0) {
    const current = stack.pop();

    if (!current) continue;

    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const fullPath = path.join(current, entry.name);

      if (entry.isDirectory()) {
        stack.push(fullPath);
        continue;
      }

      if (
        entry.name === 'types.ts' &&
        path.basename(path.dirname(fullPath)) === name
      ) {
        return fullPath;
      }
    }
  }

  return undefined;
}

function listPlatformTypeSourceFiles(platform: Platform) {
  const packageName = platform === 'react' ? 'react' : 'react-native';
  const packageRoot = path.join(root, 'packages', packageName, 'src');
  const stack = [packageRoot];
  const files: string[] = [];

  while (stack.length > 0) {
    const current = stack.pop();

    if (!current) continue;

    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const fullPath = path.join(current, entry.name);

      if (entry.isDirectory()) {
        stack.push(fullPath);
        continue;
      }

      if (entry.name === 'types.ts') {
        files.push(fullPath);
      }
    }
  }

  return files;
}

function getSectionExportName(
  section: NonNullable<ComponentGeneratorConfig['apiSections']>[number],
  platform: Platform
) {
  if (typeof section.exportName === 'string') {
    return section.exportName;
  }

  return section.exportName[platform];
}

function findPlatformExportSourceFile(params: {
  exportName: string;
  platform: Platform;
  program: ts.Program;
}) {
  const { exportName, platform, program } = params;
  const checker = program.getTypeChecker();

  for (const filePath of listPlatformTypeSourceFiles(platform)) {
    const sourceFile = program.getSourceFile(filePath);

    if (!sourceFile) continue;

    const moduleSymbol = checker.getSymbolAtLocation(sourceFile);

    if (!moduleSymbol) continue;

    const hasExport = checker
      .getExportsOfModule(moduleSymbol)
      .some((symbol) => symbol.name === exportName);

    if (hasExport) {
      return filePath;
    }
  }

  return undefined;
}

function createTypesProgram() {
  const tsconfigPath = path.join(root, 'packages', 'types', 'tsconfig.json');

  const configFile = ts.readConfigFile(tsconfigPath, ts.sys.readFile);

  if (configFile.error) {
    const message = ts.flattenDiagnosticMessageText(
      configFile.error.messageText,
      '\n'
    );

    throw new Error(`Failed to read ${tsconfigPath}: ${message}`);
  }

  const parsedConfig = ts.parseJsonConfigFileContent(
    configFile.config,
    ts.sys,
    path.dirname(tsconfigPath)
  );

  return ts.createProgram({
    rootNames: parsedConfig.fileNames,
    options: parsedConfig.options,
  });
}

function createPackageProgram(platform: Platform) {
  const packageName = platform === 'react' ? 'react' : 'react-native';

  const tsconfigPath = path.join(
    root,
    'packages',
    packageName,
    'tsconfig.json'
  );

  const configFile = ts.readConfigFile(tsconfigPath, ts.sys.readFile);

  if (configFile.error) {
    const message = ts.flattenDiagnosticMessageText(
      configFile.error.messageText,
      '\n'
    );

    throw new Error(`Failed to read ${tsconfigPath}: ${message}`);
  }

  const parsedConfig = ts.parseJsonConfigFileContent(
    configFile.config,
    ts.sys,
    path.dirname(tsconfigPath)
  );

  return ts.createProgram({
    rootNames: parsedConfig.fileNames,
    options: parsedConfig.options,
  });
}

function getLiteralUnionOptions(type: ts.Type) {
  if (!type.isUnion()) {
    return null;
  }

  const options: string[] = [];

  for (const item of type.types) {
    if (item.flags & ts.TypeFlags.Undefined) {
      continue;
    }

    if (!item.isStringLiteral()) {
      return null;
    }

    options.push(item.value);
  }

  return options.length > 0 ? options : null;
}

function extractComponentProps(name: string): ExtractedProp[] {
  const sourceFilePath = findTypeSourceFile(
    name.charAt(0).toLowerCase() + name.slice(1)
  );

  if (!sourceFilePath) {
    console.log(`⚠️ Types source not found for ${name}`);
    return [];
  }

  const program = createTypesProgram();
  const checker = program.getTypeChecker();

  const sourceFile = program.getSourceFile(sourceFilePath);

  if (!sourceFile) {
    return [];
  }

  const typeNames = [`Base${name}Props`, `${name}BaseProps`];

  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);

  if (!moduleSymbol) {
    console.log(`⚠️ Module symbol not found for ${sourceFilePath}`);
    return [];
  }

  const exportedSymbol = checker
    .getExportsOfModule(moduleSymbol)
    .find((symbol) => typeNames.includes(symbol.name));

  if (!exportedSymbol) {
    console.log(`⚠️ Export ${typeNames.join(' or ')} not found.`);
    return [];
  }

  const declaredType = checker.getDeclaredTypeOfSymbol(exportedSymbol);

  const propSymbols = checker.getPropertiesOfType(declaredType);

  const extracted: ExtractedProp[] = [];

  for (const propSymbol of propSymbols) {
    const declaration =
      propSymbol.valueDeclaration ?? propSymbol.declarations?.[0];

    if (!declaration) {
      continue;
    }

    const propName = propSymbol.name;

    const required = (propSymbol.flags & ts.SymbolFlags.Optional) === 0;

    const type = checker.getTypeOfSymbolAtLocation(propSymbol, declaration);

    const typeText = checker.typeToString(
      type,
      declaration,
      ts.TypeFormatFlags.NoTruncation
    );

    const description = ts.displayPartsToString(
      propSymbol.getDocumentationComment(checker)
    );

    const unionOptions = getLiteralUnionOptions(type);

    if (unionOptions) {
      extracted.push({
        name: propName,
        kind: 'select',
        required,
        type: typeText,
        description,
        sourceFilePath: declaration.getSourceFile().fileName,
        options: unionOptions,
      });

      continue;
    }

    const nonNullableType = checker.getNonNullableType(type);

    if (nonNullableType.flags & ts.TypeFlags.Boolean) {
      extracted.push({
        name: propName,
        kind: 'boolean',
        required,
        type: typeText,
        description,
        sourceFilePath: declaration.getSourceFile().fileName,
      });

      continue;
    }

    if (
      nonNullableType.flags & ts.TypeFlags.String ||
      nonNullableType.flags & ts.TypeFlags.StringLiteral
    ) {
      extracted.push({
        name: propName,
        kind: 'string',
        required,
        type: typeText,
        description,
        sourceFilePath: declaration.getSourceFile().fileName,
      });

      continue;
    }

    if (
      nonNullableType.flags & ts.TypeFlags.Number ||
      nonNullableType.flags & ts.TypeFlags.NumberLiteral
    ) {
      extracted.push({
        name: propName,
        kind: 'number',
        required,
        type: typeText,
        description,
        sourceFilePath: declaration.getSourceFile().fileName,
      });

      continue;
    }

    extracted.push({
      name: propName,
      kind: 'other',
      required,
      type: typeText,
      description,
      sourceFilePath: declaration.getSourceFile().fileName,
    });
  }

  return extracted;
}

function extractExportedProps(params: {
  sourceFilePath: string;
  exportName: string;
  program: ts.Program;
}): ExtractedProp[] {
  const { sourceFilePath, exportName, program } = params;

  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(sourceFilePath);

  if (!sourceFile) {
    return [];
  }

  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);

  if (!moduleSymbol) {
    return [];
  }

  const exportedSymbol = checker
    .getExportsOfModule(moduleSymbol)
    .find((symbol) => symbol.name === exportName);

  if (!exportedSymbol) {
    console.log(`⚠️ Export ${exportName} not found in ${sourceFilePath}`);
    return [];
  }

  const declaredType = checker.getDeclaredTypeOfSymbol(exportedSymbol);
  const propSymbols = checker.getPropertiesOfType(declaredType);

  const extracted: ExtractedProp[] = [];

  for (const propSymbol of propSymbols) {
    const declaration =
      propSymbol.valueDeclaration ?? propSymbol.declarations?.[0];

    if (!declaration) continue;

    const type = checker.getTypeOfSymbolAtLocation(propSymbol, declaration);

    const typeText = checker.typeToString(
      type,
      declaration,
      ts.TypeFormatFlags.NoTruncation
    );

    const description = ts.displayPartsToString(
      propSymbol.getDocumentationComment(checker)
    );

    const unionOptions = getLiteralUnionOptions(type);
    const nonNullableType = checker.getNonNullableType(type);

    let kind: ExtractedProp['kind'] = 'other';

    if (unionOptions) {
      kind = 'select';
    } else if (nonNullableType.flags & ts.TypeFlags.Boolean) {
      kind = 'boolean';
    } else if (
      nonNullableType.flags & ts.TypeFlags.String ||
      nonNullableType.flags & ts.TypeFlags.StringLiteral
    ) {
      kind = 'string';
    } else if (
      nonNullableType.flags & ts.TypeFlags.Number ||
      nonNullableType.flags & ts.TypeFlags.NumberLiteral
    ) {
      kind = 'number';
    }

    extracted.push({
      name: propSymbol.name,
      kind,
      required: (propSymbol.flags & ts.SymbolFlags.Optional) === 0,
      type: typeText,
      description,
      sourceFilePath: declaration.getSourceFile().fileName,
      ...(unionOptions ? { options: unionOptions } : {}),
    });
  }

  return extracted;
}

const extractedProps = extractComponentProps(componentName);

const excludedControls = new Set(componentConfig.demo?.excludeControls ?? []);

const playgroundProps = extractedProps.filter(
  (prop) =>
    prop.kind !== 'other' &&
    !prop.name.startsWith('on') &&
    !prop.name.startsWith('default') &&
    !excludedControls.has(prop.name)
);

const requiredComplexProps = extractedProps.filter(
  (prop) => prop.required && prop.kind === 'other'
);

const satisfiedRequiredProps = new Set(
  componentConfig.demo?.satisfiedRequiredProps ?? []
);

const missingRequiredComplexProps = requiredComplexProps.filter(
  (prop) =>
    !componentConfig.demo?.staticProps?.[prop.name] &&
    !satisfiedRequiredProps.has(prop.name)
);

if (missingRequiredComplexProps.length > 0) {
  console.warn(
    `⚠️ ${componentName} requires demo values for complex props: ${missingRequiredComplexProps
      .map((prop) => prop.name)
      .join(', ')}`
  );
}

const componentTypeFile = findTypeSourceFile(
  componentName.charAt(0).toLowerCase() + componentName.slice(1)
);

const componentTypeSource = componentTypeFile
  ? fs.readFileSync(componentTypeFile, 'utf8')
  : '';

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function getChangeHandlerName(propName: string) {
  const handlerName = `on${capitalize(propName)}Change`;

  return componentTypeSource.includes(handlerName) ? handlerName : null;
}

const catalogRoot = path.join(
  root,
  'apps',
  'website',
  'src',
  'component-catalog'
);

const catalogComponentsRoot = path.join(catalogRoot, 'components');

const catalogRegistryFile = path.join(
  catalogRoot,
  'registry',
  'componentPages.ts'
);

function getComponentCatalogDir(name: string) {
  return path.join(catalogComponentsRoot, name);
}

const componentCatalogDir = getComponentCatalogDir(componentName);

function existsInPackage(packageName: 'react' | 'react-native') {
  const packageRoot = path.join(root, 'packages', packageName, 'src');

  const stack = [packageRoot];

  while (stack.length > 0) {
    const current = stack.pop();

    if (!current) continue;

    for (const entry of fs.readdirSync(current, {
      withFileTypes: true,
    })) {
      const fullPath = path.join(current, entry.name);

      if (entry.isDirectory()) {
        if (entry.name === componentName) {
          return true;
        }

        stack.push(fullPath);
      }
    }
  }

  return false;
}

const platforms: Platform[] = [];

if (existsInPackage('react')) {
  platforms.push('react');
}

if (existsInPackage('react-native')) {
  platforms.push('react-native');
}

if (platforms.length === 0) {
  console.error(
    `Component "${componentName}" was not found in react or react-native packages.`
  );
  process.exit(1);
}

function extractPlatformProps(platform: Platform) {
  const sourceFilePath = findPlatformTypeSourceFile(platform, componentName);

  if (!sourceFilePath) {
    console.log(`⚠️ Platform types not found for ${platform}/${componentName}`);
    return [];
  }

  return extractExportedProps({
    sourceFilePath,
    exportName: `${componentName}Props`,
    program: createPackageProgram(platform),
  });
}

const reactApiProps = platforms.includes('react')
  ? extractPlatformProps('react')
  : [];

const nativeApiProps = platforms.includes('react-native')
  ? extractPlatformProps('react-native')
  : [];

function writeIfMissing(filePath: string, content: string) {
  const exists = fs.existsSync(filePath);

  if (check) {
    const currentContent = exists ? fs.readFileSync(filePath, 'utf8') : null;

    if (currentContent !== content) {
      checkFailures.push(path.relative(root, filePath));
    }

    return;
  }

  if (exists && !force) {
    console.log(`⏭ Skipped existing: ${path.relative(root, filePath)}`);
    return;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);

  console.log(
    `${exists ? '♻️ Updated' : '✅ Created'}: ${path.relative(root, filePath)}`
  );
}

const usageDir = componentCatalogDir;

const usageFile = path.join(usageDir, `${componentName}Usage.tsx`);

function createUsageStaticProps(platform: Platform) {
  return [
    getDemoProps(platform) || null,
    componentConfig.demo?.label
      ? `label='${componentConfig.demo.label}'`
      : null,
    componentConfig.demo?.description
      ? `description='${componentConfig.demo.description}'`
      : null,
  ]
    .filter((prop): prop is string => Boolean(prop))
    .map((prop) => `        ${JSON.stringify(prop)},`)
    .join('\n');
}

const reactUsageStaticProps = createUsageStaticProps('react');

const nativeUsageStaticProps = createUsageStaticProps('react-native');

function createUsageChildren(platform: Platform) {
  const children =
    platform === 'react'
      ? (componentConfig.react?.children ?? '')
      : (componentConfig.native?.children ?? '');

  if (!children) {
    return '';
  }

  return children
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');
}

const reactUsageChildren = createUsageChildren('react');

const nativeUsageChildren = createUsageChildren('react-native');

function createPlatformImports(platform: Platform) {
  const imports =
    platform === 'react'
      ? (componentConfig.react?.imports ?? [])
      : (componentConfig.native?.imports ?? []);

  return imports.length > 0 ? `\n${imports.join('\n')}` : '';
}

const reactPlatformImports = createPlatformImports('react');

const nativePlatformImports = createPlatformImports('react-native');

const usageContent = `${generatedFileHeader}'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initial${componentName}PlaygroundValue,
  type ${componentName}PlaygroundValue,
} from './${componentName}Playground';

import styles from '../../shared/ComponentUsage.module.css';

type ${componentName}UsageProps = {
  platform: ComponentPlatform;
};

function create${componentName}Code(
  platform: ComponentPlatform,
  value: ${componentName}PlaygroundValue
) {
  const packageName =
    platform === 'react'
      ? '@vellira-ui/react'
      : '@vellira-ui/react-native';

  const props: string[] =
    platform === 'react'
      ? [
${reactUsageStaticProps}
        ]
      : [
${nativeUsageStaticProps}
        ];

  const children =
    platform === 'react'
      ? ${JSON.stringify(reactUsageChildren)}
      : ${JSON.stringify(nativeUsageChildren)};

${playgroundProps
  .map((prop) => {
    const initialValue = componentConfig.demo?.initialValues?.[prop.name];

    if (prop.kind === 'boolean') {
      return `  if (value.${prop.name}) {
    props.push('${prop.name}');
  }`;
    }

    if (prop.kind === 'string') {
      return `  if (value.${prop.name}) {
    props.push(\`${prop.name}='\${value.${prop.name}}'\`);
  }`;
    }

    if (prop.kind === 'number') {
      return `  if (value.${prop.name} !== ${JSON.stringify(initialValue ?? 0)}) {
    props.push(\`${prop.name}={\${value.${prop.name}}}\`);
  }`;
    }

    return `  if (value.${prop.name} !== ${JSON.stringify(
      initialValue ?? prop.options[0] ?? ''
    )}) {
    props.push(\`${prop.name}='\${value.${prop.name}}'\`);
  }`;
  })
  .join('\n\n')}

  const propsText =
    props.length === 0 ? '' : \`\\n  \${props.join('\\n  ')}\\n\`;

  if (!children) {
    return \`import { ${componentName} } from '\${packageName}';
\${platform === 'react' ? ${JSON.stringify(reactPlatformImports)} : ${JSON.stringify(nativePlatformImports)}}

<${componentName}\${propsText}/>\`;
  }

  return \`import { ${componentName} } from '\${packageName}';
\${platform === 'react' ? ${JSON.stringify(reactPlatformImports)} : ${JSON.stringify(nativePlatformImports)}}

<${componentName}\${propsText}>
\${children}
</${componentName}>\`;
}

export function ${componentName}Usage({
  platform,
}: ${componentName}UsageProps) {
  const [value] =
    useComponentDemoState<${componentName}PlaygroundValue>(
      initial${componentName}PlaygroundValue
    );

  const code = create${componentName}Code(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
`;

writeIfMissing(usageFile, usageContent);

const examplesDir = componentCatalogDir;

const examplesFile = path.join(examplesDir, `${componentName}Examples.tsx`);

type GeneratedExample = {
  title: string;
  description: string;
  props: readonly string[];
  imports?: readonly string[];
  reactImports?: readonly string[];
  nativeImports?: readonly string[];
  reactProps?: readonly string[];
  nativeProps?: readonly string[];
  reactChildren?: string;
  nativeChildren?: string;
  platforms?: readonly Platform[];
};

function hasExtractedProp(name: string) {
  return extractedProps.some((prop) => prop.name === name);
}

function getSelectExample() {
  const prop = playgroundProps.find(
    (item) => item.kind === 'select' && item.options.length > 1
  );

  if (!prop || prop.kind !== 'select') {
    return null;
  }

  const initialValue =
    componentConfig.demo?.initialValues?.[prop.name] ?? prop.options[0];

  const alternative = prop.options.find((option) => option !== initialValue);

  if (!alternative) {
    return null;
  }

  return {
    title: toLabel(prop.name),
    description: `Alternative ${toLabel(prop.name).toLowerCase()} option.`,
    props: [`${prop.name}='${alternative}'`],
  } satisfies GeneratedExample;
}

function createGeneratedExamples(): GeneratedExample[] {
  if (componentConfig.examples) {
    return [...componentConfig.examples];
  }

  const examples: GeneratedExample[] = [
    {
      title: 'Basic',
      description:
        componentProfile === 'overlay'
          ? 'Basic trigger and floating content.'
          : componentProfile === 'navigation'
            ? 'Basic navigation structure.'
            : componentProfile === 'form-control'
              ? 'Basic form control usage.'
              : 'Basic component usage.',
      props: [],
    },
  ];

  if (hasExtractedProp('disabled')) {
    examples.push({
      title: 'Disabled',
      description: 'Disabled state.',
      props: ['disabled'],
    });
  }

  if (hasExtractedProp('checked')) {
    examples.push({
      title: 'Selected',
      description: 'Selected state.',
      props: ['checked'],
    });
  } else if (hasExtractedProp('loading')) {
    examples.push({
      title: 'Loading',
      description: 'Loading state.',
      props: ['loading'],
    });
  } else if (hasExtractedProp('open')) {
    examples.push({
      title: 'Open',
      description: 'Open state.',
      props: ['open'],
    });
  }

  if (hasExtractedProp('error')) {
    examples.push({
      title: 'Error',
      description: 'Validation error state.',
      props: [`error='Please review this option.'`],
    });
  }

  const selectExample = getSelectExample();

  if (selectExample) {
    examples.push(selectExample);
  }

  if (hasExtractedProp('required')) {
    examples.push({
      title: 'Required',
      description: 'Required form control.',
      props: ['required'],
    });
  }

  if (componentProfile === 'compound' && hasExtractedProp('children')) {
    examples.push({
      title: 'Compound usage',
      description: 'Composes the root with public child slots.',
      props: [],
    });
  }

  return examples;
}

const generatedExamples = createGeneratedExamples();

function createExampleJsx(platform: Platform, example: GeneratedExample) {
  const componentAlias =
    platform === 'react' ? `React${componentName}` : `Native${componentName}`;

  const props = [
    getDemoProps(platform),
    componentConfig.demo?.label
      ? `label=${toTsString(componentConfig.demo.label)}`
      : '',
    componentConfig.demo?.description
      ? `description=${toTsString(componentConfig.demo.description)}`
      : '',
    ...example.props,
    ...(platform === 'react'
      ? (example.reactProps ?? [])
      : (example.nativeProps ?? [])),
  ].filter(Boolean);

  const exampleChildren =
    platform === 'react'
      ? (example.reactChildren ?? componentConfig.react?.children ?? '')
      : (example.nativeChildren ?? componentConfig.native?.children ?? '');

  const propsText =
    props.length === 0 ? '' : `\n          ${props.join('\n          ')}`;

  if (!exampleChildren) {
    return `<${componentAlias}${propsText}
        />`;
  }

  const aliasedChildren = exampleChildren
    .replaceAll(`<${componentName}.`, `<${componentAlias}.`)
    .replaceAll(`</${componentName}.`, `</${componentAlias}.`);

  const formattedChildren = aliasedChildren
    .split('\n')
    .map((line) => `          ${line}`)
    .join('\n');

  return `<${componentAlias}${propsText}
        >
${formattedChildren}
        </${componentAlias}>`;
}

function createExampleCode(platform: Platform, example: GeneratedExample) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props = [
    getDemoProps(platform),
    componentConfig.demo?.label
      ? `label=${toTsString(componentConfig.demo.label)}`
      : '',
    componentConfig.demo?.description
      ? `description=${toTsString(componentConfig.demo.description)}`
      : '',
    ...example.props,
    ...(platform === 'react'
      ? (example.reactProps ?? [])
      : (example.nativeProps ?? [])),
  ].filter(Boolean);

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  const exampleChildren =
    platform === 'react'
      ? (example.reactChildren ?? componentConfig.react?.children ?? '')
      : (example.nativeChildren ?? componentConfig.native?.children ?? '');

  if (!exampleChildren) {
    const imports = [
      `import { ${componentName} } from '${packageName}';`,
      ...(example.imports ?? []),
      ...(platform === 'react'
        ? (example.reactImports ?? [])
        : (example.nativeImports ?? [])),
    ].join('\n');

    return `${imports}

<${componentName}${propsText}/>`;
  }

  const formattedChildren = exampleChildren
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');

  const imports = [
    `import { ${componentName} } from '${packageName}';`,
    ...(example.imports ?? []),
    ...(platform === 'react'
      ? (example.reactImports ?? [])
      : (example.nativeImports ?? [])),
  ].join('\n');

  return `${imports}

<${componentName}${propsText}>
${formattedChildren}
</${componentName}>`;
}

function getExamplesForPlatform(platform: Platform) {
  return generatedExamples.filter(
    (example) => !example.platforms || example.platforms.includes(platform)
  );
}

const exampleImports = Array.from(
  new Set(
    generatedExamples.flatMap((example) => [
      ...(example.imports ?? []),
      ...(example.reactImports ?? []),
      ...(example.nativeImports ?? []),
      ...(componentConfig.react?.imports ?? []),
      ...(componentConfig.native?.imports ?? []),
    ])
  )
);

const reactGeneratedExamples = getExamplesForPlatform('react')
  .map(
    (example) => `    {
      title: ${toTsString(example.title)},
      description: ${toTsString(example.description)},
      preview: (
        ${createExampleJsx('react', example)}
      ),
      code: ${JSON.stringify(createExampleCode('react', example))},
    },`
  )
  .join('\n');

const nativeGeneratedExamples = getExamplesForPlatform('react-native')
  .map(
    (example) => `    {
      title: ${toTsString(example.title)},
      description: ${toTsString(example.description)},
      preview: (
        ${createExampleJsx('react-native', example)}
      ),
      code: ${JSON.stringify(createExampleCode('react-native', example))},
    },`
  )
  .join('\n');

const examplesContent = `${generatedFileHeader}'use client';

import { ${componentName} as React${componentName} } from '@vellira-ui/react';
import { ${componentName} as Native${componentName} } from '@vellira-ui/react-native';
${exampleImports.join('\n')}

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type ${componentName}ExamplesProps = {
  platform: ComponentPlatform;
};

export function ${componentName}Examples({
  platform,
}: ${componentName}ExamplesProps) {
  const reactExamples = [
${reactGeneratedExamples}
  ] as const;

  const nativeExamples = [
${nativeGeneratedExamples}
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
`;

writeIfMissing(examplesFile, examplesContent);

const accessibilityDir = componentCatalogDir;

const accessibilityFile = path.join(
  accessibilityDir,
  `${componentName}Accessibility.tsx`
);

function toTsString(value: string) {
  return `'${value
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\n', '\\n')}'`;
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

type AccessibilityItem = {
  title: string;
  description: string;
  props?: readonly string[];
};

function createAccessibilityItems(platform: Platform): AccessibilityItem[] {
  const configuredItems =
    platform === 'react'
      ? componentConfig.accessibility?.react
      : componentConfig.accessibility?.native;

  if (configuredItems) {
    return [...configuredItems];
  }

  const items: AccessibilityItem[] = [];
  const platformProps =
    platform === 'react'
      ? reactApiProps.length > 0
        ? reactApiProps
        : extractedProps
      : nativeApiProps.length > 0
        ? nativeApiProps
        : extractedProps;

  const hasProp = (name: string) =>
    platformProps.some((prop) => prop.name === name);

  const isInteractive =
    hasProp('disabled') ||
    hasProp('checked') ||
    hasProp('selected') ||
    hasProp('open') ||
    hasProp('onPress') ||
    hasProp('onClick') ||
    extractedProps.some((prop) => prop.name.startsWith('on'));

  if (
    componentConfig.demo?.label ||
    hasProp('label') ||
    hasProp('accessibilityLabel')
  ) {
    items.push({
      title: 'Accessible naming',
      description:
        platform === 'react'
          ? 'Provide a visible label or another accessible name that clearly identifies the control.'
          : 'Provide a visible label or accessibilityLabel so screen readers can identify the control.',
      props: ['label', 'children', 'aria-label', 'accessibilityLabel'].filter(
        hasProp
      ),
    });
  }

  if (
    hasProp('checked') ||
    hasProp('selected') ||
    hasProp('open') ||
    hasProp('expanded')
  ) {
    items.push({
      title: 'State communication',
      description:
        platform === 'react'
          ? 'Expose the current interactive state through the appropriate native semantics and keep it synchronized with the visual state.'
          : 'Expose the current interactive state through React Native accessibilityState and keep it synchronized with the visual state.',
      props: ['checked', 'selected', 'open', 'expanded'].filter(hasProp),
    });
  }

  if (hasProp('disabled')) {
    items.push({
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    });
  }

  if (hasProp('error')) {
    items.push({
      title: 'Validation feedback',
      description:
        platform === 'react'
          ? 'Associate validation feedback with the control and expose its invalid state to assistive technologies.'
          : 'Expose validation feedback through accessible text or hints and preserve the invalid state for assistive technologies.',
      props: ['error', 'invalid'].filter(hasProp),
    });
  }

  if (hasProp('required')) {
    items.push({
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    });
  }

  if (isInteractive) {
    items.push({
      title: 'Keyboard and focus',
      description:
        platform === 'react'
          ? 'Preserve expected keyboard interaction and visible focus behavior.'
          : 'Verify focus and screen reader interaction on supported React Native platforms.',
      props: ['onKeyDown', 'onFocus', 'onBlur', 'onPress', 'onClick'].filter(
        hasProp
      ),
    });
  }

  if (items.length === 0) {
    items.push({
      title: 'Accessible usage',
      description:
        platform === 'react'
          ? 'Use semantic markup, accessible naming, and predictable keyboard behavior.'
          : 'Expose meaningful accessibility roles, labels, states, and interaction behavior.',
    });
  }

  if (componentProfile === 'overlay') {
    items.push({
      title: 'Dismissal',
      description:
        platform === 'react'
          ? 'Keep dismissal, focus return, and Escape behavior predictable for overlay interactions.'
          : 'Keep dismissal, back navigation, and screen reader focus predictable for overlay interactions.',
      props: ['open', 'defaultOpen', 'onOpenChange'].filter(hasProp),
    });
  }

  return items;
}

const reactAccessibilityItems = createAccessibilityItems('react')
  .map(
    (item) => `    {
      title: ${toTsString(item.title)},
      description: ${toTsString(item.description)},${
        item.props?.length
          ? `\n      props: [${item.props.map(toTsString).join(', ')}],`
          : ''
      }
    },`
  )
  .join('\n');

const nativeAccessibilityItems = createAccessibilityItems('react-native')
  .map(
    (item) => `    {
      title: ${toTsString(item.title)},
      description: ${toTsString(item.description)},${
        item.props?.length
          ? `\n      props: [${item.props.map(toTsString).join(', ')}],`
          : ''
      }
    },`
  )
  .join('\n');

const accessibilityContent = `${generatedFileHeader}'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type ${componentName}AccessibilityProps = {
  platform: ComponentPlatform;
};

export function ${componentName}Accessibility({
  platform,
}: ${componentName}AccessibilityProps) {
  const reactItems = [
${reactAccessibilityItems}
  ] as const;

  const nativeItems = [
${nativeAccessibilityItems}
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
`;

writeIfMissing(accessibilityFile, accessibilityContent);

const apiFile = path.join(componentCatalogDir, `${slug}Api.ts`);

function cleanApiType(type: string) {
  return type
    .replace(/\s*\|\s*undefined\b/g, '')
    .replace(/\bundefined\s*\|\s*/g, '')
    .trim();
}

function getApiType(prop: ExtractedProp) {
  const sharedProp = getSharedProp(prop);
  const apiProp = isExternalProp(prop) && sharedProp ? sharedProp : prop;

  if (apiProp.kind === 'select' && apiProp.options?.length) {
    return apiProp.options.map((option) => `'${option}'`).join(' | ');
  }

  return cleanApiType(apiProp.type);
}

function getApiDefaultValue(prop: ExtractedProp, platform: Platform) {
  const sharedValue = componentConfig.defaults?.shared?.[prop.name];

  const platformValue =
    platform === 'react'
      ? componentConfig.defaults?.react?.[prop.name]
      : componentConfig.defaults?.native?.[prop.name];

  const value = platformValue ?? sharedValue;

  if (value === undefined) {
    return undefined;
  }

  if (typeof value === 'string') {
    return `'${value}'`;
  }

  return String(value);
}

function isExternalProp(prop: ExtractedProp) {
  if (!prop.sourceFilePath) {
    return false;
  }

  const normalizedSource = path.normalize(prop.sourceFilePath);

  return !velliraApiSourceRoots.some((sourceRoot) =>
    isPathInside(normalizedSource, sourceRoot)
  );
}

function getFallbackApiDescription(prop: ExtractedProp, platform: Platform) {
  if (!isExternalProp(prop)) {
    return `Prop for ${componentName}.`;
  }

  if (platform === 'react') {
    return 'Forwarded React DOM prop.';
  }

  return 'Forwarded React Native prop.';
}

function getSharedProp(prop: ExtractedProp) {
  return extractedProps.find((item) => item.name === prop.name);
}

function isOwnedApiProp(prop: ExtractedProp) {
  return !isExternalProp(prop) || Boolean(getSharedProp(prop));
}

function createApiEntries(props: readonly ExtractedProp[], platform: Platform) {
  return props
    .map((prop) => {
      const defaultValue = getApiDefaultValue(prop, platform);
      const sharedProp = getSharedProp(prop);

      const description =
        componentConfig.api?.descriptions?.[prop.name] ||
        componentConfig.apiDescriptions?.[prop.name] ||
        (isExternalProp(prop) ? sharedProp?.description : undefined) ||
        prop.description ||
        sharedProp?.description ||
        getFallbackApiDescription(prop, platform);

      return `  {
    name: ${toTsString(prop.name)},
    type: ${toTsString(getApiType(prop))},${
      defaultValue ? `\n    defaultValue: ${toTsString(defaultValue)},` : ''
    }
    description: ${toTsString(description)},${
      prop.required ? '\n    required: true,' : ''
    }
  },`;
    })
    .join('\n');
}

function splitApiProps(props: readonly ExtractedProp[]) {
  const ownedProps: ExtractedProp[] = [];
  const inheritedProps: ExtractedProp[] = [];

  for (const prop of props) {
    if (isOwnedApiProp(prop)) {
      ownedProps.push(prop);
    } else {
      inheritedProps.push(prop);
    }
  }

  return { ownedProps, inheritedProps };
}

type ApiSectionData = {
  name: string;
  ownedProps: ExtractedProp[];
};

function createConfiguredApiSections(platform: Platform): ApiSectionData[] {
  const program = createPackageProgram(platform);
  const sections: ApiSectionData[] = [];

  for (const section of componentConfig.api?.sections ??
    componentConfig.apiSections ??
    []) {
    const exportName = getSectionExportName(section, platform);

    if (!exportName) continue;

    const sourceFilePath = findPlatformExportSourceFile({
      exportName,
      platform,
      program,
    });

    if (!sourceFilePath) {
      console.log(
        `⚠️ Export ${exportName} not found for ${platform}/${componentName}`
      );
      continue;
    }

    const props = extractExportedProps({
      sourceFilePath,
      exportName,
      program,
    });

    sections.push({
      name: section.name,
      ownedProps: splitApiProps(props).ownedProps,
    });
  }

  return sections.filter((section) => section.ownedProps.length > 0);
}

const reactSplit = splitApiProps(
  reactApiProps.length > 0 ? reactApiProps : extractedProps
);

const nativeSplit = splitApiProps(
  nativeApiProps.length > 0 ? nativeApiProps : extractedProps
);

const reactApiSections = [
  {
    name: componentName,
    ownedProps: reactSplit.ownedProps,
  },
  ...createConfiguredApiSections('react'),
];

const nativeApiSections = [
  {
    name: componentName,
    ownedProps: nativeSplit.ownedProps,
  },
  ...createConfiguredApiSections('react-native'),
];

function createApiSectionEntries(
  sections: readonly ApiSectionData[],
  platform: Platform
) {
  return sections
    .map(
      (section) => `  {
    name: ${toTsString(section.name)},
    props: [
${createApiEntries(section.ownedProps, platform)}
    ],
  },`
    )
    .join('\n');
}

const reactApiSectionEntries = createApiSectionEntries(
  reactApiSections,
  'react'
);

const nativeApiSectionEntries = createApiSectionEntries(
  nativeApiSections,
  'react-native'
);

const reactInheritedApiEntries = createApiEntries(
  reactSplit.inheritedProps,
  'react'
);

const nativeInheritedApiEntries = createApiEntries(
  nativeSplit.inheritedProps,
  'react-native'
);

const apiContent = `${generatedFileHeader}import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const react${componentName}ApiSections: readonly ComponentApiSection[] = [
${reactApiSectionEntries}
];

const native${componentName}ApiSections: readonly ComponentApiSection[] = [
${nativeApiSectionEntries}
];

const inheritedReact${componentName}Api: readonly ComponentApiProp[] = [
${reactInheritedApiEntries}
];

const inheritedNative${componentName}Api: readonly ComponentApiProp[] = [
${nativeInheritedApiEntries}
];

export const ${slug}Api = {
  react: {
    sections: react${componentName}ApiSections,
    inheritedProps: inheritedReact${componentName}Api,
  },
  'react-native': {
    sections: native${componentName}ApiSections,
    inheritedProps: inheritedNative${componentName}Api,
  },
} as const;
`;

writeIfMissing(apiFile, apiContent);

function insertAfterMarker(params: {
  filePath: string;
  marker: string;
  content: string;
  existsCheck: string;
}) {
  const { filePath, marker, content, existsCheck } = params;

  const originalSource = fs.readFileSync(filePath, 'utf8');
  const source = originalSource;

  if (source.includes(existsCheck)) {
    if (!force) {
      console.log(`⏭ Skipped registry update: ${existsCheck}`);
      return;
    }

    const entryStartMatch = source.match(
      new RegExp(`\\n\\s*${escapeRegExp(slug)}: \\{`)
    );
    const entryStart =
      entryStartMatch?.index !== undefined ? entryStartMatch.index + 1 : -1;

    if (entryStart === -1) {
      console.error(`Existing registry entry not found for ${slug}`);
      process.exit(1);
    }

    const nextEntryMatch = source
      .slice(entryStart + 1)
      .match(/\n {2}[a-z0-9-]+: \{/);

    const registryEndMatch = source
      .slice(entryStart)
      .match(/\n}(?: satisfies [^;]+)?;/);

    const entryEnd =
      nextEntryMatch?.index !== undefined
        ? entryStart + 1 + nextEntryMatch.index
        : registryEndMatch?.index !== undefined
          ? entryStart + registryEndMatch.index
          : -1;

    if (entryEnd === -1) {
      console.error(`Could not determine registry entry boundary for ${slug}`);
      process.exit(1);
    }

    const nextSource =
      source.slice(0, entryStart) + content + source.slice(entryEnd);

    if (check) {
      if (nextSource !== source) {
        checkFailures.push(path.relative(root, filePath));
      }

      return;
    }

    fs.writeFileSync(filePath, nextSource);

    console.log(`♻️ Updated registry: ${existsCheck}`);
    return;
  }

  if (!source.includes(marker)) {
    console.error(`Marker not found in ${filePath}: ${marker}`);
    process.exit(1);
  }

  const nextSource = source.replace(marker, `${marker}\n${content}`);

  if (check) {
    if (nextSource !== source) {
      checkFailures.push(path.relative(root, filePath));
    }

    return;
  }

  fs.writeFileSync(filePath, nextSource);

  console.log(`✅ Updated: ${path.relative(root, filePath)}`);
}

const playgroundDir = componentCatalogDir;

const playgroundSchemaFile = path.join(
  playgroundDir,
  `${slug}PlaygroundSchema.ts`
);

function toLabel(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/^./, (character) => character.toUpperCase());
}

function getInitialValue(prop: ExtractedProp) {
  const configuredValue = componentConfig.demo?.initialValues?.[prop.name];

  if (configuredValue !== undefined) {
    return JSON.stringify(configuredValue);
  }

  if (prop.kind === 'boolean') {
    return 'false';
  }

  if (prop.kind === 'number') {
    return '0';
  }

  if (prop.kind === 'select') {
    return JSON.stringify(prop.options[0] ?? '');
  }

  return prop.required ? JSON.stringify('example') : JSON.stringify('');
}

function getPlaygroundPropBinding(prop: ExtractedProp) {
  const propValue =
    prop.kind === 'string' && !prop.required
      ? `value.${prop.name} || undefined`
      : `value.${prop.name}`;

  const binding = `${prop.name}={${propValue}}`;

  const changeHandler = getChangeHandlerName(prop.name);

  if (!changeHandler) {
    return binding;
  }

  return `${binding}
          ${changeHandler}={(nextValue) =>
            onChange('${prop.name}', nextValue)
          }`;
}

const reactStaticDemoProps = getDemoProps('react');
const nativeStaticDemoProps = getDemoProps('react-native');

const reactDemoChildren = componentConfig.react?.children ?? '';
const nativeDemoChildren = componentConfig.native?.children ?? '';

function isPlaygroundProp(name: string) {
  return playgroundProps.some((prop) => prop.name === name);
}

const demoPresentationProps = [
  componentConfig.demo?.label && !isPlaygroundProp('label')
    ? `label=${toTsString(componentConfig.demo.label)}`
    : null,
  componentConfig.demo?.description && !isPlaygroundProp('description')
    ? `description=${toTsString(componentConfig.demo.description)}`
    : null,
]
  .filter(Boolean)
  .join('\n          ');

const staticDemoProps = Object.entries(componentConfig.demo?.staticProps ?? {})
  .map(([name, value]) => `${name}={${value}}`)
  .join('\n          ');

const playgroundPropBindings = playgroundProps
  .map((prop) => getPlaygroundPropBinding(prop))
  .join('\n          ');

const playgroundValueFields = playgroundProps
  .map((prop) => {
    if (prop.kind === 'boolean') {
      return `  ${prop.name}: boolean;`;
    }

    if (prop.kind === 'number') {
      return `  ${prop.name}: number;`;
    }

    if (prop.kind === 'select') {
      const union = prop.options.map((option) => `'${option}'`).join(' | ');

      return `  ${prop.name}: ${union};`;
    }

    return `  ${prop.name}: string;`;
  })
  .join('\n');

const playgroundInitialValues = playgroundProps
  .map((prop) => `  ${prop.name}: ${getInitialValue(prop)},`)
  .join('\n');

const playgroundControlEntries = playgroundProps
  .map((prop) => {
    const label = toLabel(prop.name);

    if (prop.kind === 'boolean') {
      return `  {
    type: 'toggle',
    key: '${prop.name}',
    label: '${label}',
    group: 'Options',
  },`;
    }

    if (prop.kind === 'select') {
      return `  {
    type: 'select',
    key: '${prop.name}',
    label: '${label}',
    options: [${prop.options.map((option) => `'${option}'`).join(', ')}],
  },`;
    }

    if (prop.kind === 'number') {
      return `  {
    type: 'number',
    key: '${prop.name}',
    label: '${label}',
  },`;
    }

    return `  {
    type: 'text',
    key: '${prop.name}',
    label: '${label}',
  },`;
  })
  .join('\n');

const playgroundSchemaContent = `${generatedFileHeader}import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { ${componentName}PlaygroundValue } from './${componentName}Playground';

export const ${slug}PlaygroundControls = [
${playgroundControlEntries}
] as const satisfies readonly PlaygroundControl<${componentName}PlaygroundValue>[];
`;

writeIfMissing(playgroundSchemaFile, playgroundSchemaContent);

const playgroundFile = path.join(
  playgroundDir,
  `${componentName}Playground.tsx`
);

const playgroundContent = `${generatedFileHeader}'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { ${slug}PlaygroundControls } from './${slug}PlaygroundSchema';

export type ${componentName}PlaygroundValue = {
${playgroundValueFields}
};

type ${componentName}PlaygroundProps = {
  render${componentName}: (
    value: ${componentName}PlaygroundValue,
    onChange: <K extends keyof ${componentName}PlaygroundValue>(
      key: K,
      nextValue: ${componentName}PlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initial${componentName}PlaygroundValue: ${componentName}PlaygroundValue = {
${playgroundInitialValues}
};

export function ${componentName}Playground({
  render${componentName},
}: ${componentName}PlaygroundProps) {
  const [value, setValue] =
    useComponentDemoState<${componentName}PlaygroundValue>(
      initial${componentName}PlaygroundValue
    );

    const update = (
    key: keyof ${componentName}PlaygroundValue,
    nextValue: ${componentName}PlaygroundValue[keyof ${componentName}PlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
    previewWidth=${JSON.stringify(componentConfig.demo?.previewWidth ?? 'auto')}
      controls={
        <PlaygroundControlsFromSchema
          value={value}
          controls={${slug}PlaygroundControls}
          onChange={update}
        />
      }
    >
      {render${componentName}(value, update)}
    </ComponentPlayground>
  );
}
`;

writeIfMissing(playgroundFile, playgroundContent);

const demoEntries = [
  platforms.includes('react') ? `      react: ${componentName}Demo,` : null,
  platforms.includes('react-native')
    ? `      'react-native': Native${componentName}Demo,`
    : null,
]
  .filter(Boolean)
  .join('\n');

const relatedComponents = componentConfig.related ?? [];

const nativeResponsivePresentation =
  componentConfig.native?.responsivePresentation === true;

function createInitialValueMap() {
  return Object.fromEntries(
    playgroundProps.map((prop) => [prop.name, getInitialValue(prop)])
  ) as Record<string, string | boolean | number>;
}

function createGeneratedPageModel(): GeneratedPageModel {
  return {
    componentName,
    slug,
    platforms,
    demo: {
      staticProps: {
        react: reactStaticDemoProps,
        'react-native': nativeStaticDemoProps,
      },
      children: {
        react: reactDemoChildren,
        'react-native': nativeDemoChildren,
      },
      imports: {
        react: componentConfig.react?.imports ?? [],
        'react-native': componentConfig.native?.imports ?? [],
      },
      responsivePresentation: nativeResponsivePresentation,
    },
    playground: {
      props: playgroundProps,
      initialValues: createInitialValueMap(),
    },
    usage: {
      children: {
        react: reactUsageChildren,
        'react-native': nativeUsageChildren,
      },
    },
    examples: generatedExamples,
    accessibility: {
      react: createAccessibilityItems('react'),
      'react-native': createAccessibilityItems('react-native'),
    },
    api: {
      react: {
        sections: reactApiSections.map((section) => ({
          name: section.name,
          props: section.ownedProps,
        })),
        inheritedProps: reactSplit.inheritedProps,
      },
      'react-native': {
        sections: nativeApiSections.map((section) => ({
          name: section.name,
          props: section.ownedProps,
        })),
        inheritedProps: nativeSplit.inheritedProps,
      },
    },
    related: relatedComponents,
  };
}

const generatedPageModel = createGeneratedPageModel();

const pageConfigSnippet = `
  ${slug}: {
    name: '${componentName}',
    demos: {
${demoEntries}
    },
    Usage: ${componentName}Usage,
    Examples: ${componentName}Examples,
    Accessibility: ${componentName}Accessibility,
    api: ${slug}Api,
    related: ${
      generatedPageModel.related.length > 0
        ? `[${generatedPageModel.related.map((item) => `'${item}'`).join(', ')}]`
        : '[]'
    },
  },
`;

const componentPagesFile = catalogRegistryFile;

const reactDemoDir = componentCatalogDir;

const reactDemoFile = path.join(reactDemoDir, `${componentName}Demo.tsx`);

const nativeResponsiveImport = nativeResponsivePresentation
  ? `import { useWindowDimensions } from 'react-native';\n`
  : '';

const nativeResponsiveSetup = nativeResponsivePresentation
  ? `  const { width } = useWindowDimensions();
  const presentation = width <= 890 ? 'sheet' : 'popover';

`
  : '';

function createDemoElement(params: {
  platform: Platform;
  propBindings: string;
}) {
  const { platform, propBindings } = params;

  const children =
    platform === 'react' ? reactDemoChildren : nativeDemoChildren;

  const staticProps =
    platform === 'react' ? reactStaticDemoProps : nativeStaticDemoProps;

  const props = [
    staticProps,
    staticDemoProps,
    platform === 'react-native' && nativeResponsivePresentation
      ? 'presentation={presentation}'
      : '',
    propBindings,
    demoPresentationProps,
  ]
    .filter(Boolean)
    .join('\n          ');

  if (!children) {
    return `<${componentName}
          ${props}
        />`;
  }

  const formattedChildren = children
    .split('\n')
    .map((line) => `          ${line}`)
    .join('\n');

  return `<${componentName}
          ${props}
        >
${formattedChildren}
        </${componentName}>`;
}

const reactDemoElement = createDemoElement({
  platform: 'react',
  propBindings: playgroundPropBindings,
});

const nativeDemoElement = createDemoElement({
  platform: 'react-native',
  propBindings: playgroundPropBindings,
});

const usesDemoValue = playgroundProps.length > 0;

const usesDemoOnChange = playgroundProps.some((prop) =>
  Boolean(getChangeHandlerName(prop.name))
);

const demoRenderParams = usesDemoOnChange
  ? '(value, onChange)'
  : usesDemoValue
    ? '(value)'
    : '()';

const reactDemoContent = `${generatedFileHeader}'use client';

import { ${componentName} } from '@vellira-ui/react';
${componentConfig.react?.imports?.join('\n') ?? ''}

import { ${componentName}Playground } from './${componentName}Playground';

export function ${componentName}Demo() {
  return (
    <${componentName}Playground
      render${componentName}={${demoRenderParams} => (
        ${reactDemoElement}
      )}
    />
  );
}
`;

if (platforms.includes('react')) {
  writeIfMissing(reactDemoFile, reactDemoContent);
}

const nativeDemoDir = componentCatalogDir;

const nativeDemoFile = path.join(
  nativeDemoDir,
  `Native${componentName}Demo.tsx`
);

const nativeDemoContent = `${generatedFileHeader}'use client';

${nativeResponsiveImport}import { ${componentName} } from '@vellira-ui/react-native';
${componentConfig.native?.imports?.join('\n') ?? ''}

import { ${componentName}Playground } from './${componentName}Playground';

export function Native${componentName}Demo() {
${nativeResponsiveSetup}  return (
    <${componentName}Playground
      render${componentName}={${demoRenderParams} => (
        ${nativeDemoElement}
      )}
    />
  );
}
`;

if (platforms.includes('react-native')) {
  writeIfMissing(nativeDemoFile, nativeDemoContent);
}

const componentIndexFile = path.join(componentCatalogDir, 'index.ts');

const componentIndexContent = `${generatedFileHeader}export { ${componentName}Accessibility } from './${componentName}Accessibility';
${platforms.includes('react') ? `export { ${componentName}Demo } from './${componentName}Demo';\n` : ''}export { ${componentName}Examples } from './${componentName}Examples';
export {
  ${componentName}Playground,
  initial${componentName}PlaygroundValue,
} from './${componentName}Playground';
export { ${componentName}Usage } from './${componentName}Usage';
${platforms.includes('react-native') ? `export { Native${componentName}Demo } from './Native${componentName}Demo';\n` : ''}export { ${slug}Api } from './${slug}Api';

export type {
  ${componentName}PlaygroundValue,
} from './${componentName}Playground';
`;

writeIfMissing(componentIndexFile, componentIndexContent);

function insertMissingLinesAfterMarker(params: {
  filePath: string;
  marker: string;
  lines: string[];
}) {
  const { filePath, marker, lines } = params;

  const originalSource = fs.readFileSync(filePath, 'utf8');
  let source = originalSource;

  if (!source.includes(marker)) {
    console.error(`Marker not found in ${filePath}: ${marker}`);
    process.exit(1);
  }

  const missingLines = lines.filter((line) => !source.includes(line));

  if (missingLines.length === 0) {
    console.log('⏭ Skipped registry imports: already present');
    return;
  }

  source = source.replace(
    new RegExp(
      `\\nimport \\{[^;]*?\\} from '../components/${escapeRegExp(
        componentName
      )}';`,
      'g'
    ),
    ''
  );

  const nextSource = source.replace(
    marker,
    `${marker}\n${missingLines.join('\n')}`
  );

  if (check) {
    if (nextSource !== originalSource) {
      checkFailures.push(path.relative(root, filePath));
    }

    return;
  }

  fs.writeFileSync(filePath, nextSource);

  console.log(`✅ Updated imports: ${path.relative(root, filePath)}`);
}

const requiredDemoFiles = [
  platforms.includes('react')
    ? path.join(componentCatalogDir, `${componentName}Demo.tsx`)
    : null,

  platforms.includes('react-native')
    ? path.join(componentCatalogDir, `Native${componentName}Demo.tsx`)
    : null,
].filter((filePath): filePath is string => Boolean(filePath));

const missingDemoFiles = requiredDemoFiles.filter(
  (filePath) => !fs.existsSync(filePath)
);

if (missingDemoFiles.length > 0) {
  console.log('\n⚠️ Registry update skipped. Missing website demos:');

  for (const filePath of missingDemoFiles) {
    console.log(`   - ${path.relative(root, filePath)}`);
  }
} else {
  const registryImportNames = [
    `${componentName}Accessibility`,
    platforms.includes('react') ? `${componentName}Demo` : null,
    `${componentName}Examples`,
    `${componentName}Usage`,
    platforms.includes('react-native') ? `Native${componentName}Demo` : null,
    `${slug}Api`,
  ].filter((name): name is string => Boolean(name));

  const registryImports = [
    `import {
${registryImportNames.map((name) => `  ${name},`).join('\n')}
} from '../components/${componentName}';`,
  ];
  insertMissingLinesAfterMarker({
    filePath: componentPagesFile,
    marker: '// component-page-imports',
    lines: registryImports,
  });

  insertAfterMarker({
    filePath: componentPagesFile,
    marker: '// component-page-entries',
    content: pageConfigSnippet.trimEnd().replace(/^\n/, ''),
    existsCheck: `${slug}: {`,
  });
}

if (check) {
  if (checkFailures.length > 0) {
    console.error('Generated component page files are out of date:');

    for (const filePath of [...new Set(checkFailures)].sort()) {
      console.error(`  - ${filePath}`);
    }

    process.exit(1);
  }

  console.log(`Generated component page is up to date: ${componentName}`);
  process.exit(0);
}

console.log('Extracted props:', extractedProps);

console.log(`Component: ${componentName}`);
console.log(`Slug: ${slug}`);
console.log(`Platforms: ${platforms.join(', ')}`);
console.log(`Catalog root: ${catalogRoot}`);
