// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Tooltip } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';
import { useTheme } from '@vellira-ui/react-native';
import { controlSizes } from '@vellira-ui/tokens';

import { TooltipPlayground } from './TooltipPlayground';

export function NativeTooltipDemo() {
  const { theme: nativeTheme } = useTheme();

  return (
    <TooltipPlayground
      platform='react-native'
      renderTooltip={(value) => (
        <Tooltip placement={value.placement} disabled={value.disabled}>
          <Tooltip.Trigger
            style={{
              alignItems: 'center',
              justifyContent: 'center',
              minHeight: controlSizes.md.height,
              paddingLeft: nativeTheme.tokens.spacing[6],
              paddingRight: nativeTheme.tokens.spacing[6],
              borderRadius: nativeTheme.tokens.radius.full,
              backgroundColor:
                nativeTheme.components.button.primary.solid.default.bg,
            }}
          >
            <NativeText
              style={{
                color: nativeTheme.components.button.primary.solid.default.fg,
                fontFamily: nativeTheme.tokens.typography.family.regular,
                fontSize: nativeTheme.tokens.typography.size.md,
                lineHeight: nativeTheme.tokens.typography.lineHeight.md,
              }}
            >
              Press and hold
            </NativeText>
          </Tooltip.Trigger>
          <Tooltip.Content withArrow>Helpful contextual label.</Tooltip.Content>
        </Tooltip>
      )}
    />
  );
}
