// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type TooltipAccessibilityProps = {
  platform: ComponentPlatform;
};

export function TooltipAccessibility({ platform }: TooltipAccessibilityProps) {
  const reactItems = [
    {
      title: 'Supplemental text',
      description:
        'Use tooltips for supplemental labels, not as the only way to complete a task.',
      props: ['children', 'disabled'],
    },
    {
      title: 'Delay behavior',
      description:
        'Choose open and close delays that keep hover and focus behavior predictable.',
      props: ['delay', 'onOpenChange'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Supplemental text',
      description:
        'Keep tooltip content concise and make critical information available outside the tooltip.',
      props: ['children', 'disabled'],
    },
    {
      title: 'Placement',
      description:
        'Use placement that keeps the tooltip near its trigger without covering the control.',
      props: ['placement'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
