// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialTooltipPlaygroundValue,
  type TooltipPlaygroundValue,
} from './TooltipPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type TooltipUsageProps = {
  platform: ComponentPlatform;
};

function createTooltipCode(
  platform: ComponentPlatform,
  value: TooltipPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children =
    platform === 'react'
      ? `  <Tooltip.Trigger asChild>
    <ReactButton>Hover for details</ReactButton>
  </Tooltip.Trigger>
  <Tooltip.Content withArrow>Helpful contextual label.</Tooltip.Content>`
      : `  <Tooltip.Trigger
    style={{
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: controlSizes.md.height,
      paddingLeft: nativeTheme.tokens.spacing[6],
      paddingRight: nativeTheme.tokens.spacing[6],
      borderRadius: nativeTheme.tokens.radius.full,
      backgroundColor:
        nativeTheme.components.button.primary.solid.default.bg,
    }}
  >
    <NativeText
      style={{
        color: nativeTheme.components.button.primary.solid.default.fg,
        fontFamily: nativeTheme.tokens.typography.family.regular,
        fontSize: nativeTheme.tokens.typography.size.md,
        lineHeight: nativeTheme.tokens.typography.lineHeight.md,
      }}
    >
      Press and hold
    </NativeText>
  </Tooltip.Trigger>
  <Tooltip.Content withArrow>Helpful contextual label.</Tooltip.Content>`;

  if (value.placement !== 'top') {
    props.push(`placement='${value.placement}'`);
  }

  if (value.disabled) {
    props.push('disabled');
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  const imports = `import { Tooltip } from '${packageName}';${
    platform === 'react'
      ? `
import { Button as ReactButton } from '@vellira-ui/react';`
      : `
import { Text as NativeText } from 'react-native';
import { useTheme } from '@vellira-ui/react-native';
import { controlSizes } from '@vellira-ui/tokens';`
  }`;

  const setup =
    platform === 'react' ? `` : `  const { theme: nativeTheme } = useTheme();`;

  const root = !children
    ? `<Tooltip${propsText}/>`
    : `<Tooltip${propsText}>
${children}
</Tooltip>`;

  if (setup) {
    const indentedRoot = root
      .split('\n')
      .map((line) => `    ${line}`)
      .join('\n');

    return `${imports}

function Example() {
${setup}

  return (
${indentedRoot}
  );
}`;
  }

  return `${imports}

${root}`;
}

export function TooltipUsage({ platform }: TooltipUsageProps) {
  const [value] = useComponentDemoState<TooltipPlaygroundValue>(
    initialTooltipPlaygroundValue
  );

  const code = createTooltipCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
