// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { tooltipPlaygroundControls } from './tooltipPlaygroundSchema';

export type TooltipPlaygroundValue = {
  placement:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'left'
    | 'left-start'
    | 'left-end';
  disabled: boolean;
};

type TooltipPlaygroundProps = {
  platform: 'react' | 'react-native';
  renderTooltip: (
    value: TooltipPlaygroundValue,
    onChange: <K extends keyof TooltipPlaygroundValue>(
      key: K,
      nextValue: TooltipPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialTooltipPlaygroundValue: TooltipPlaygroundValue = {
  placement: 'top',
  disabled: false,
};

export function TooltipPlayground({
  platform,
  renderTooltip,
}: TooltipPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<TooltipPlaygroundValue>(
    initialTooltipPlaygroundValue
  );

  const update = (
    key: keyof TooltipPlaygroundValue,
    nextValue: TooltipPlaygroundValue[keyof TooltipPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='auto'
      controls={
        <PlaygroundControlsFromSchema
          platform={platform}
          value={value}
          controls={tooltipPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderTooltip(value, update)}
    </ComponentPlayground>
  );
}
