// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Tooltip as ReactTooltip } from '@vellira-ui/react';
import { Tooltip as NativeTooltip } from '@vellira-ui/react-native';
import { Button as ReactButton } from '@vellira-ui/react';
import { Text as NativeText } from 'react-native';
import { useTheme } from '@vellira-ui/react-native';
import { controlSizes } from '@vellira-ui/tokens';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

function NativeTooltipExample1Preview() {
  const { theme: nativeTheme } = useTheme();

  return (
    <NativeTooltip>
      <NativeTooltip.Trigger
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: controlSizes.md.height,
          paddingLeft: nativeTheme.tokens.spacing[6],
          paddingRight: nativeTheme.tokens.spacing[6],
          borderRadius: nativeTheme.tokens.radius.full,
          backgroundColor:
            nativeTheme.components.button.primary.solid.default.bg,
        }}
      >
        <NativeText
          style={{
            color: nativeTheme.components.button.primary.solid.default.fg,
            fontFamily: nativeTheme.tokens.typography.family.regular,
            fontSize: nativeTheme.tokens.typography.size.md,
            lineHeight: nativeTheme.tokens.typography.lineHeight.md,
          }}
        >
          Press and hold
        </NativeText>
      </NativeTooltip.Trigger>
      <NativeTooltip.Content withArrow>
        Helpful contextual label.
      </NativeTooltip.Content>
    </NativeTooltip>
  );
}

function NativeTooltipExample2Preview() {
  const { theme: nativeTheme } = useTheme();

  return (
    <NativeTooltip placement='bottom'>
      <NativeTooltip.Trigger
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: controlSizes.md.height,
          paddingLeft: nativeTheme.tokens.spacing[6],
          paddingRight: nativeTheme.tokens.spacing[6],
          borderRadius: nativeTheme.tokens.radius.full,
          backgroundColor:
            nativeTheme.components.button.primary.solid.default.bg,
        }}
      >
        <NativeText
          style={{
            color: nativeTheme.components.button.primary.solid.default.fg,
            fontFamily: nativeTheme.tokens.typography.family.regular,
            fontSize: nativeTheme.tokens.typography.size.md,
            lineHeight: nativeTheme.tokens.typography.lineHeight.md,
          }}
        >
          Press and hold
        </NativeText>
      </NativeTooltip.Trigger>
      <NativeTooltip.Content withArrow>
        Helpful contextual label.
      </NativeTooltip.Content>
    </NativeTooltip>
  );
}

function NativeTooltipExample3Preview() {
  const { theme: nativeTheme } = useTheme();

  return (
    <NativeTooltip disabled>
      <NativeTooltip.Trigger
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: controlSizes.md.height,
          paddingLeft: nativeTheme.tokens.spacing[6],
          paddingRight: nativeTheme.tokens.spacing[6],
          borderRadius: nativeTheme.tokens.radius.full,
          backgroundColor:
            nativeTheme.components.button.primary.solid.default.bg,
        }}
      >
        <NativeText
          style={{
            color: nativeTheme.components.button.primary.solid.default.fg,
            fontFamily: nativeTheme.tokens.typography.family.regular,
            fontSize: nativeTheme.tokens.typography.size.md,
            lineHeight: nativeTheme.tokens.typography.lineHeight.md,
          }}
        >
          Press and hold
        </NativeText>
      </NativeTooltip.Trigger>
      <NativeTooltip.Content withArrow>
        Helpful contextual label.
      </NativeTooltip.Content>
    </NativeTooltip>
  );
}

function NativeTooltipExample4Preview() {
  const { theme: nativeTheme } = useTheme();

  return (
    <NativeTooltip>
      <NativeTooltip.Trigger
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: controlSizes.md.height,
          paddingLeft: nativeTheme.tokens.spacing[6],
          paddingRight: nativeTheme.tokens.spacing[6],
          borderRadius: nativeTheme.tokens.radius.full,
          backgroundColor:
            nativeTheme.components.button.primary.solid.default.bg,
        }}
      >
        <NativeText
          style={{
            color: nativeTheme.components.button.primary.solid.default.fg,
            fontFamily: nativeTheme.tokens.typography.family.regular,
            fontSize: nativeTheme.tokens.typography.size.md,
            lineHeight: nativeTheme.tokens.typography.lineHeight.md,
          }}
        >
          No arrow
        </NativeText>
      </NativeTooltip.Trigger>
      <NativeTooltip.Content>Tooltip without arrow</NativeTooltip.Content>
    </NativeTooltip>
  );
}

type TooltipExamplesProps = {
  platform: ComponentPlatform;
};

export function TooltipExamples({ platform }: TooltipExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Contextual label for a trigger.',
      preview: (
        <ReactTooltip>
          <ReactTooltip.Trigger asChild>
            <ReactButton>Hover for details</ReactButton>
          </ReactTooltip.Trigger>
          <ReactTooltip.Content withArrow>
            Helpful contextual label.
          </ReactTooltip.Content>
        </ReactTooltip>
      ),
      code: `import { Tooltip } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Tooltip>
  <Tooltip.Trigger asChild>
    <ReactButton>Hover for details</ReactButton>
  </Tooltip.Trigger>
  <Tooltip.Content withArrow>Helpful contextual label.</Tooltip.Content>
</Tooltip>`,
    },
    {
      title: 'Placement',
      description: 'Alternative tooltip placement.',
      preview: (
        <ReactTooltip placement='bottom'>
          <ReactTooltip.Trigger asChild>
            <ReactButton>Hover for details</ReactButton>
          </ReactTooltip.Trigger>
          <ReactTooltip.Content withArrow>
            Helpful contextual label.
          </ReactTooltip.Content>
        </ReactTooltip>
      ),
      code: `import { Tooltip } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Tooltip
  placement='bottom'
>
  <Tooltip.Trigger asChild>
    <ReactButton>Hover for details</ReactButton>
  </Tooltip.Trigger>
  <Tooltip.Content withArrow>Helpful contextual label.</Tooltip.Content>
</Tooltip>`,
    },
    {
      title: 'Disabled',
      description: 'Disabled tooltip behavior.',
      preview: (
        <ReactTooltip disabled>
          <ReactTooltip.Trigger asChild>
            <ReactButton>Hover for details</ReactButton>
          </ReactTooltip.Trigger>
          <ReactTooltip.Content withArrow>
            Helpful contextual label.
          </ReactTooltip.Content>
        </ReactTooltip>
      ),
      code: `import { Tooltip } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Tooltip
  disabled
>
  <Tooltip.Trigger asChild>
    <ReactButton>Hover for details</ReactButton>
  </Tooltip.Trigger>
  <Tooltip.Content withArrow>Helpful contextual label.</Tooltip.Content>
</Tooltip>`,
    },
    {
      title: 'Without arrow',
      description: 'Omits the arrow when a simpler bubble is preferred.',
      preview: (
        <ReactTooltip>
          <ReactTooltip.Trigger asChild>
            <ReactButton>No arrow</ReactButton>
          </ReactTooltip.Trigger>
          <ReactTooltip.Content>Tooltip without arrow</ReactTooltip.Content>
        </ReactTooltip>
      ),
      code: `import { Tooltip } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Tooltip>
  <Tooltip.Trigger asChild>
    <ReactButton>No arrow</ReactButton>
  </Tooltip.Trigger>
  <Tooltip.Content>Tooltip without arrow</Tooltip.Content>
</Tooltip>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Contextual label for a trigger.',
      preview: <NativeTooltipExample1Preview />,
      code: `import { Tooltip } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';
import { useTheme } from '@vellira-ui/react-native';
import { controlSizes } from '@vellira-ui/tokens';

function Example() {
  const { theme: nativeTheme } = useTheme();

  return (
    <Tooltip>
      <Tooltip.Trigger
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: controlSizes.md.height,
          paddingLeft: nativeTheme.tokens.spacing[6],
          paddingRight: nativeTheme.tokens.spacing[6],
          borderRadius: nativeTheme.tokens.radius.full,
          backgroundColor:
            nativeTheme.components.button.primary.solid.default.bg,
        }}
      >
        <NativeText
          style={{
            color: nativeTheme.components.button.primary.solid.default.fg,
            fontFamily: nativeTheme.tokens.typography.family.regular,
            fontSize: nativeTheme.tokens.typography.size.md,
            lineHeight: nativeTheme.tokens.typography.lineHeight.md,
          }}
        >
          Press and hold
        </NativeText>
      </Tooltip.Trigger>
      <Tooltip.Content withArrow>Helpful contextual label.</Tooltip.Content>
    </Tooltip>
  );
}`,
    },
    {
      title: 'Placement',
      description: 'Alternative tooltip placement.',
      preview: <NativeTooltipExample2Preview />,
      code: `import { Tooltip } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';
import { useTheme } from '@vellira-ui/react-native';
import { controlSizes } from '@vellira-ui/tokens';

function Example() {
  const { theme: nativeTheme } = useTheme();

  return (
    <Tooltip
      placement='bottom'
    >
      <Tooltip.Trigger
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: controlSizes.md.height,
          paddingLeft: nativeTheme.tokens.spacing[6],
          paddingRight: nativeTheme.tokens.spacing[6],
          borderRadius: nativeTheme.tokens.radius.full,
          backgroundColor:
            nativeTheme.components.button.primary.solid.default.bg,
        }}
      >
        <NativeText
          style={{
            color: nativeTheme.components.button.primary.solid.default.fg,
            fontFamily: nativeTheme.tokens.typography.family.regular,
            fontSize: nativeTheme.tokens.typography.size.md,
            lineHeight: nativeTheme.tokens.typography.lineHeight.md,
          }}
        >
          Press and hold
        </NativeText>
      </Tooltip.Trigger>
      <Tooltip.Content withArrow>Helpful contextual label.</Tooltip.Content>
    </Tooltip>
  );
}`,
    },
    {
      title: 'Disabled',
      description: 'Disabled tooltip behavior.',
      preview: <NativeTooltipExample3Preview />,
      code: `import { Tooltip } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';
import { useTheme } from '@vellira-ui/react-native';
import { controlSizes } from '@vellira-ui/tokens';

function Example() {
  const { theme: nativeTheme } = useTheme();

  return (
    <Tooltip
      disabled
    >
      <Tooltip.Trigger
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: controlSizes.md.height,
          paddingLeft: nativeTheme.tokens.spacing[6],
          paddingRight: nativeTheme.tokens.spacing[6],
          borderRadius: nativeTheme.tokens.radius.full,
          backgroundColor:
            nativeTheme.components.button.primary.solid.default.bg,
        }}
      >
        <NativeText
          style={{
            color: nativeTheme.components.button.primary.solid.default.fg,
            fontFamily: nativeTheme.tokens.typography.family.regular,
            fontSize: nativeTheme.tokens.typography.size.md,
            lineHeight: nativeTheme.tokens.typography.lineHeight.md,
          }}
        >
          Press and hold
        </NativeText>
      </Tooltip.Trigger>
      <Tooltip.Content withArrow>Helpful contextual label.</Tooltip.Content>
    </Tooltip>
  );
}`,
    },
    {
      title: 'Without arrow',
      description: 'Omits the arrow when a simpler bubble is preferred.',
      preview: <NativeTooltipExample4Preview />,
      code: `import { Tooltip } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';
import { useTheme } from '@vellira-ui/react-native';
import { controlSizes } from '@vellira-ui/tokens';

function Example() {
  const { theme: nativeTheme } = useTheme();

  return (
    <Tooltip>
      <Tooltip.Trigger
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: controlSizes.md.height,
          paddingLeft: nativeTheme.tokens.spacing[6],
          paddingRight: nativeTheme.tokens.spacing[6],
          borderRadius: nativeTheme.tokens.radius.full,
          backgroundColor:
            nativeTheme.components.button.primary.solid.default.bg,
        }}
      >
        <NativeText
          style={{
            color: nativeTheme.components.button.primary.solid.default.fg,
            fontFamily: nativeTheme.tokens.typography.family.regular,
            fontSize: nativeTheme.tokens.typography.size.md,
            lineHeight: nativeTheme.tokens.typography.lineHeight.md,
          }}
        >
          No arrow
        </NativeText>
      </Tooltip.Trigger>
      <Tooltip.Content>Tooltip without arrow</Tooltip.Content>
    </Tooltip>
  );
}`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
