// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import { Tooltip as ReactTooltip } from '@vellira-ui/react';
import { Tooltip as NativeTooltip } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type TooltipExamplesProps = {
  platform: ComponentPlatform;
};

export function TooltipExamples({ platform }: TooltipExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Contextual label for a trigger.',
      preview: (
        <ReactTooltip>
          <ReactTooltip.Trigger>Hover for details</ReactTooltip.Trigger>
          <ReactTooltip.Content>Helpful contextual label.</ReactTooltip.Content>
        </ReactTooltip>
      ),
      code: "import { Tooltip } from '@vellira-ui/react';\n\n<Tooltip>\n  <Tooltip.Trigger>Hover for details</Tooltip.Trigger>\n  <Tooltip.Content>Helpful contextual label.</Tooltip.Content>\n</Tooltip>",
    },
    {
      title: 'Placement',
      description: 'Alternative tooltip placement.',
      preview: (
        <ReactTooltip placement='bottom'>
          <ReactTooltip.Trigger>Hover for details</ReactTooltip.Trigger>
          <ReactTooltip.Content>Helpful contextual label.</ReactTooltip.Content>
        </ReactTooltip>
      ),
      code: "import { Tooltip } from '@vellira-ui/react';\n\n<Tooltip\n  placement='bottom'\n>\n  <Tooltip.Trigger>Hover for details</Tooltip.Trigger>\n  <Tooltip.Content>Helpful contextual label.</Tooltip.Content>\n</Tooltip>",
    },
    {
      title: 'Disabled',
      description: 'Disabled tooltip behavior.',
      preview: (
        <ReactTooltip disabled>
          <ReactTooltip.Trigger>Hover for details</ReactTooltip.Trigger>
          <ReactTooltip.Content>Helpful contextual label.</ReactTooltip.Content>
        </ReactTooltip>
      ),
      code: "import { Tooltip } from '@vellira-ui/react';\n\n<Tooltip\n  disabled\n>\n  <Tooltip.Trigger>Hover for details</Tooltip.Trigger>\n  <Tooltip.Content>Helpful contextual label.</Tooltip.Content>\n</Tooltip>",
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Contextual label for a trigger.',
      preview: (
        <NativeTooltip>
          <NativeTooltip.Trigger>Press for details</NativeTooltip.Trigger>
          <NativeTooltip.Content>
            Helpful contextual label.
          </NativeTooltip.Content>
        </NativeTooltip>
      ),
      code: "import { Tooltip } from '@vellira-ui/react-native';\n\n<Tooltip>\n  <Tooltip.Trigger>Press for details</Tooltip.Trigger>\n  <Tooltip.Content>Helpful contextual label.</Tooltip.Content>\n</Tooltip>",
    },
    {
      title: 'Placement',
      description: 'Alternative tooltip placement.',
      preview: (
        <NativeTooltip placement='bottom'>
          <NativeTooltip.Trigger>Press for details</NativeTooltip.Trigger>
          <NativeTooltip.Content>
            Helpful contextual label.
          </NativeTooltip.Content>
        </NativeTooltip>
      ),
      code: "import { Tooltip } from '@vellira-ui/react-native';\n\n<Tooltip\n  placement='bottom'\n>\n  <Tooltip.Trigger>Press for details</Tooltip.Trigger>\n  <Tooltip.Content>Helpful contextual label.</Tooltip.Content>\n</Tooltip>",
    },
    {
      title: 'Disabled',
      description: 'Disabled tooltip behavior.',
      preview: (
        <NativeTooltip disabled>
          <NativeTooltip.Trigger>Press for details</NativeTooltip.Trigger>
          <NativeTooltip.Content>
            Helpful contextual label.
          </NativeTooltip.Content>
        </NativeTooltip>
      ),
      code: "import { Tooltip } from '@vellira-ui/react-native';\n\n<Tooltip\n  disabled\n>\n  <Tooltip.Trigger>Press for details</Tooltip.Trigger>\n  <Tooltip.Content>Helpful contextual label.</Tooltip.Content>\n</Tooltip>",
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
