// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const reactTooltipApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Tooltip',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Compound tooltip children.',
        required: true,
      },
      {
        name: 'open',
        type: 'boolean',
        description: 'Controlled open state.',
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        description: 'Initial uncontrolled open state.',
      },
      {
        name: 'onOpenChange',
        type: '((open: boolean) => void)',
        description: 'Called when the open state changes.',
      },
      {
        name: 'delay',
        type: 'number | import("@vellira-ui/types").TooltipDelay',
        description:
          'Open delay in milliseconds, or explicit open/close delays.',
      },
      {
        name: 'skipDelay',
        type: 'number',
        description: 'Delay window for future sibling tooltip delay skipping.',
      },
      {
        name: 'offset',
        type: 'number',
        description: 'Distance between trigger and content in pixels.',
      },
      {
        name: 'interactive',
        type: 'boolean',
        description: 'Allows pointer interaction inside tooltip content.',
      },
      {
        name: 'portal',
        type: 'boolean',
        description:
          'Reserved for automatic portal rendering in higher-level helpers.',
      },
      {
        name: 'avoidCollisions',
        type: 'boolean',
        description: 'Allows the tooltip to flip or shift to stay visible.',
      },
      {
        name: 'matchTriggerWidth',
        type: 'boolean',
        description: 'Matches tooltip content width to the trigger width.',
      },
      {
        name: 'modal',
        type: 'boolean',
        description:
          'Reserved for modal overlay semantics. Tooltip defaults to non-modal.',
      },
      {
        name: 'placement',
        type: "'top' | 'top-start' | 'top-end' | 'right' | 'right-start' | 'right-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end'",
        defaultValue: "'top'",
        description:
          'Preferred placement for tooltip content relative to the trigger.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Disables tooltip interaction and prevents it from opening.',
      },
    ],
  },
  {
    name: 'Tooltip.Trigger',
    props: [
      {
        name: 'asChild',
        type: 'boolean',
        description: 'Composes trigger behavior onto a single child element.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Trigger content.',
        required: true,
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables tooltip interaction for this trigger.',
      },
    ],
  },
  {
    name: 'Tooltip.Content',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Tooltip content shown while open.',
        required: true,
      },
      {
        name: 'forceMount',
        type: 'boolean',
        description: 'Keeps tooltip content mounted when closed.',
      },
      {
        name: 'withArrow',
        type: 'boolean',
        description: 'Renders a small arrow pointing at the trigger.',
      },
      {
        name: 'className',
        type: 'string',
        description: 'Class name applied to the tooltip content element.',
      },
      {
        name: 'style',
        type: 'CSSProperties',
        description: 'Inline style applied to the tooltip content element.',
      },
    ],
  },
];

const nativeTooltipApiSections: readonly ComponentApiSection[] = [
  {
    name: 'Tooltip',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Tooltip trigger and content children.',
        required: true,
      },
      {
        name: 'open',
        type: 'boolean',
        description: 'Controlled open state.',
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        description: 'Initial open state for uncontrolled usage.',
      },
      {
        name: 'onOpenChange',
        type: '((open: boolean) => void)',
        description: 'Called when the open state changes.',
      },
      {
        name: 'delay',
        type: 'number | Partial<TooltipDelay>',
        description:
          'Open delay in milliseconds, or explicit open/close delays.',
      },
      {
        name: 'offset',
        type: 'number',
        description: 'Distance between trigger and content in pixels.',
      },
      {
        name: 'closeOnOutsidePress',
        type: 'boolean',
        description: 'Closes the tooltip when pressing outside the content.',
      },
      {
        name: 'style',
        type: 'StyleProp<ViewStyle>',
        description: 'Style applied to the tooltip root container.',
      },
      {
        name: 'placement',
        type: "'top' | 'top-start' | 'top-end' | 'right' | 'right-start' | 'right-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end'",
        defaultValue: "'top'",
        description:
          'Preferred placement for tooltip content relative to the trigger.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description:
          'Disables tooltip interaction and prevents it from opening.',
      },
    ],
  },
  {
    name: 'Tooltip.Trigger',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Trigger content.',
        required: true,
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Disables tooltip interaction for this trigger.',
      },
      {
        name: 'style',
        type: 'StyleProp<ViewStyle>',
        description: 'Style applied to the trigger container.',
      },
    ],
  },
  {
    name: 'Tooltip.Content',
    props: [
      {
        name: 'children',
        type: 'ReactNode',
        description: 'Tooltip content shown while open.',
        required: true,
      },
      {
        name: 'forceMount',
        type: 'boolean',
        description: 'Keeps tooltip content mounted when closed.',
      },
      {
        name: 'withArrow',
        type: 'boolean',
        description: 'Renders a small arrow pointing at the trigger.',
      },
      {
        name: 'style',
        type: 'StyleProp<ViewStyle>',
        description: 'Style applied to the tooltip content container.',
      },
      {
        name: 'textStyle',
        type: 'StyleProp<TextStyle>',
        description: 'Style applied to tooltip text.',
      },
    ],
  },
];

const inheritedReactTooltipApi: readonly ComponentApiProp[] = [];

const inheritedNativeTooltipApi: readonly ComponentApiProp[] = [];

export const tooltipApi = {
  react: {
    sections: reactTooltipApiSections,
    inheritedProps: inheritedReactTooltipApi,
  },
  'react-native': {
    sections: nativeTooltipApiSections,
    inheritedProps: inheritedNativeTooltipApi,
  },
} as const;
