// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { TooltipPlaygroundValue } from './TooltipPlayground';

export const tooltipPlaygroundControls = [
  {
    type: 'select',
    key: 'placement',
    label: 'Placement',
    options: [
      'top',
      'top-start',
      'top-end',
      'right',
      'right-start',
      'right-end',
      'bottom',
      'bottom-start',
      'bottom-end',
      'left',
      'left-start',
      'left-end',
    ],
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
] as const satisfies readonly PlaygroundControl<TooltipPlaygroundValue>[];
