// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { RadioGroup } from '@vellira-ui/react-native';

import { RadioGroupPlayground } from './RadioGroupPlayground';

export function NativeRadioGroupDemo() {
  return (
    <RadioGroupPlayground
      renderRadioGroup={(value, onChange) => (
        <RadioGroup
          value={value.value || undefined}
          onValueChange={(nextValue) => onChange('value', nextValue)}
          disabled={value.disabled}
          required={value.required}
          orientation={value.orientation}
          size={value.size}
          color={value.color}
          label='Country'
          description='Choose your country of residence.'
        >
          <RadioGroup.Item value='starter' label='Starter' />
          <RadioGroup.Item value='pro' label='Pro' />
          <RadioGroup.Item value='enterprise' label='Enterprise' />
        </RadioGroup>
      )}
    />
  );
}
