// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { RadioGroupPlaygroundValue } from './RadioGroupPlayground';

export const radioGroupPlaygroundControls = [
  {
    type: 'text',
    key: 'value',
    label: 'Value',
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'required',
    label: 'Required',
    group: 'Options',
  },
  {
    type: 'select',
    key: 'orientation',
    label: 'Orientation',
    options: ['vertical', 'horizontal'],
  },
  {
    type: 'select',
    key: 'size',
    label: 'Size',
    options: ['sm', 'md', 'lg'],
  },
  {
    type: 'select',
    key: 'color',
    label: 'Color',
    options: ['primary', 'neutral', 'success', 'warning', 'danger'],
  },
] as const satisfies readonly PlaygroundControl<RadioGroupPlaygroundValue>[];
