// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { radioGroupPlaygroundControls } from './radio-groupPlaygroundSchema';

export type RadioGroupPlaygroundValue = {
  value: string;
  disabled: boolean;
  required: boolean;
  orientation: 'vertical' | 'horizontal';
  size: 'sm' | 'md' | 'lg';
  color: 'primary' | 'neutral' | 'success' | 'warning' | 'danger';
};

type RadioGroupPlaygroundProps = {
  platform: 'react' | 'react-native';
  renderRadioGroup: (
    value: RadioGroupPlaygroundValue,
    onChange: <K extends keyof RadioGroupPlaygroundValue>(
      key: K,
      nextValue: RadioGroupPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialRadioGroupPlaygroundValue: RadioGroupPlaygroundValue = {
  value: '',
  disabled: false,
  required: false,
  orientation: 'vertical',
  size: 'md',
  color: 'primary',
};

export function RadioGroupPlayground({
  platform,
  renderRadioGroup,
}: RadioGroupPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<RadioGroupPlaygroundValue>(
    initialRadioGroupPlaygroundValue
  );

  const update = (
    key: keyof RadioGroupPlaygroundValue,
    nextValue: RadioGroupPlaygroundValue[keyof RadioGroupPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='full'
      controls={
        <PlaygroundControlsFromSchema
          platform={platform}
          value={value}
          controls={radioGroupPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderRadioGroup(value, update)}
    </ComponentPlayground>
  );
}
