// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type RadioGroupAccessibilityProps = {
  platform: ComponentPlatform;
};

export function RadioGroupAccessibility({
  platform,
}: RadioGroupAccessibilityProps) {
  const reactItems = [
    {
      title: 'Group labelling',
      description:
        'Use a visible label and optional description so the radiogroup purpose is announced clearly.',
      props: ['label', 'description'],
    },
    {
      title: 'Single selection',
      description:
        'Each item value should be unique so keyboard and form selection remain predictable.',
      props: ['value', 'defaultValue', 'onValueChange'],
    },
    {
      title: 'Validation state',
      description:
        'Use required and error together when a selection must be made before submission.',
      props: ['required', 'error'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Group announcement',
      description:
        'Provide a visible label and description so assistive technology can identify the choice set.',
      props: ['label', 'description'],
    },
    {
      title: 'Selection state',
      description:
        'Keep value, defaultValue, and onValueChange tied to exactly one selected item.',
      props: ['value', 'defaultValue', 'onValueChange'],
    },
    {
      title: 'Required and error text',
      description:
        'Pair required state with clear error content when validation fails.',
      props: ['required', 'error'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
