// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { ModalPlaygroundValue } from './ModalPlayground';

export const modalPlaygroundControls = [
  {
    type: 'toggle',
    key: 'open',
    label: 'Open',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'closeOnOutsidePress',
    label: 'Close On Outside Press',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'closeOnEscape',
    label: 'Close On Escape',
    group: 'Options',
  },
  {
    type: 'select',
    key: 'animation',
    label: 'Animation',
    options: ['scale', 'slide', 'fade', 'none'],
  },
  {
    type: 'select',
    key: 'easing',
    label: 'Easing',
    options: [
      'standard',
      'linear',
      'ease',
      'ease-in',
      'ease-out',
      'ease-in-out',
    ],
  },
  {
    type: 'toggle',
    key: 'restoreFocus',
    label: 'Restore Focus',
    group: 'Options',
  },
] as const satisfies readonly PlaygroundControl<ModalPlaygroundValue>[];
