// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type ModalAccessibilityProps = {
  platform: ComponentPlatform;
};

export function ModalAccessibility({ platform }: ModalAccessibilityProps) {
  const reactItems = [
    {
      title: 'Focus management',
      description:
        'Trap focus while open and restore focus to the trigger when the modal closes.',
      props: ['trapFocus', 'restoreFocus', 'initialFocus', 'finalFocus'],
    },
    {
      title: 'Dialog labelling',
      description:
        'Use title and description content so assistive technology can announce the dialog purpose.',
      props: ['role', 'children'],
    },
    {
      title: 'Dismissal',
      description:
        'Choose outside press and Escape dismissal behavior based on task criticality.',
      props: ['closeOnOutsidePress', 'closeOnEscape'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Modal announcement',
      description:
        'Use title and description content so the modal purpose is announced clearly.',
      props: ['children'],
    },
    {
      title: 'Dismissal',
      description:
        'Provide an explicit close action when outside dismissal is disabled.',
      props: ['closeOnOutsidePress'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
