// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialModalPlaygroundValue,
  type ModalPlaygroundValue,
} from './ModalPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type ModalUsageProps = {
  platform: ComponentPlatform;
};

function createModalCode(
  platform: ComponentPlatform,
  value: ModalPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children =
    platform === 'react'
      ? "  <Modal.Trigger>Open modal</Modal.Trigger>\n  <Modal.Overlay />\n  <Modal.Content>\n    <Modal.Header>\n      <Modal.Title>Confirm action</Modal.Title>\n      <Modal.Description>This action can be reviewed before continuing.</Modal.Description>\n    </Modal.Header>\n    <Modal.Body>Modal body content.</Modal.Body>\n    <Modal.Footer>\n      <Modal.Close aria-label='Cancel' />\n    </Modal.Footer>\n  </Modal.Content>"
      : "  <Modal.Trigger>Open modal</Modal.Trigger>\n  <Modal.Overlay>\n    <Modal.Content>\n      <Modal.Header>\n        <Modal.Title>Confirm action</Modal.Title>\n        <Modal.Description>This action can be reviewed before continuing.</Modal.Description>\n      </Modal.Header>\n      <Modal.Body>Modal body content.</Modal.Body>\n      <Modal.Footer>\n        <Modal.Close accessibilityLabel='Cancel' />\n      </Modal.Footer>\n    </Modal.Content>\n  </Modal.Overlay>";

  if (value.open) {
    props.push('open');
  }

  if (value.closeOnOutsidePress) {
    props.push('closeOnOutsidePress');
  }

  if (value.closeOnEscape) {
    props.push('closeOnEscape');
  }

  if (value.animation !== 'scale') {
    props.push(`animation='${value.animation}'`);
  }

  if (value.easing !== 'standard') {
    props.push(`easing='${value.easing}'`);
  }

  if (value.restoreFocus) {
    props.push('restoreFocus');
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Modal } from '${packageName}';
${platform === 'react' ? '' : ''}

<Modal${propsText}/>`;
  }

  return `import { Modal } from '${packageName}';
${platform === 'react' ? '' : ''}

<Modal${propsText}>
${children}
</Modal>`;
}

export function ModalUsage({ platform }: ModalUsageProps) {
  const [value] = useComponentDemoState<ModalPlaygroundValue>(
    initialModalPlaygroundValue
  );

  const code = createModalCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
