// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Modal } from '@vellira-ui/react';
import {
  Button as ReactButton,
  Portal as ReactPortal,
} from '@vellira-ui/react';

import { ModalPlayground } from './ModalPlayground';

export function ModalDemo() {
  return (
    <ModalPlayground
      renderModal={(value, onChange) => (
        <Modal
          open={value.open}
          onOpenChange={(nextValue) => onChange('open', nextValue)}
          closeOnOutsidePress={value.closeOnOutsidePress}
          closeOnEscape={value.closeOnEscape}
          animation={value.animation}
          easing={value.easing}
          restoreFocus={value.restoreFocus}
        >
          <Modal.Trigger asChild>
            <ReactButton>Open modal</ReactButton>
          </Modal.Trigger>
          <ReactPortal>
            <Modal.Overlay />
            <Modal.Content>
              <Modal.Header>
                <div>
                  <Modal.Title>Delete file</Modal.Title>
                  <Modal.Description>
                    This action cannot be undone.
                  </Modal.Description>
                </div>
                <Modal.Close />
              </Modal.Header>
              <Modal.Body>Are you sure you want to continue?</Modal.Body>
              <Modal.Footer>
                <Modal.Close asChild>
                  <ReactButton color='neutral' appearance='ghost'>
                    Cancel
                  </ReactButton>
                </Modal.Close>
                <ReactButton color='danger'>Delete</ReactButton>
              </Modal.Footer>
            </Modal.Content>
          </ReactPortal>
        </Modal>
      )}
    />
  );
}
