// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialModalPlaygroundValue,
  type ModalPlaygroundValue,
} from './ModalPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type ModalUsageProps = {
  platform: ComponentPlatform;
};

function createModalCode(
  platform: ComponentPlatform,
  value: ModalPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children =
    platform === 'react'
      ? `  <Modal.Trigger asChild>
    <ReactButton>Open modal</ReactButton>
  </Modal.Trigger>
  <ReactPortal>
    <Modal.Overlay />
    <Modal.Content>
      <Modal.Header>
        <div>
          <Modal.Title>Delete file</Modal.Title>
          <Modal.Description>This action cannot be undone.</Modal.Description>
        </div>
        <Modal.Close />
      </Modal.Header>
      <Modal.Body>Are you sure you want to continue?</Modal.Body>
      <Modal.Footer>
        <Modal.Close asChild>
          <ReactButton color='neutral' appearance='ghost'>Cancel</ReactButton>
        </Modal.Close>
        <ReactButton color='danger'>Delete</ReactButton>
      </Modal.Footer>
    </Modal.Content>
  </ReactPortal>`
      : `  <Modal.Trigger asChild>
    <NativeButton>Open modal</NativeButton>
  </Modal.Trigger>
  <Modal.Overlay>
    <Modal.Content>
      <Modal.Header>
        <Modal.Title>Delete file</Modal.Title>
        <Modal.Description>This action uses the native overlay stack and focus restore.</Modal.Description>
      </Modal.Header>
      <Modal.Body>Are you sure you want to continue?</Modal.Body>
      <Modal.Footer>
        <Modal.Close>
          <NativeButton color='neutral' appearance='solid'>Cancel</NativeButton>
        </Modal.Close>
        <Modal.Close>
          <NativeButton color='danger' appearance='solid'>Delete</NativeButton>
        </Modal.Close>
      </Modal.Footer>
    </Modal.Content>
  </Modal.Overlay>`;

  if (value.open) {
    props.push('open');
  }

  if (value.closeOnOutsidePress) {
    props.push('closeOnOutsidePress');
  }

  if (value.closeOnEscape) {
    props.push('closeOnEscape');
  }

  if (value.animation !== 'scale') {
    props.push(`animation='${value.animation}'`);
  }

  if (value.easing !== 'standard') {
    props.push(`easing='${value.easing}'`);
  }

  if (value.restoreFocus) {
    props.push('restoreFocus');
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Modal } from '${packageName}';
${
  platform === 'react'
    ? `
import { Button as ReactButton, Portal as ReactPortal } from '@vellira-ui/react';`
    : `
import { Button as NativeButton } from '@vellira-ui/react-native';`
}

<Modal${propsText}/>`;
  }

  return `import { Modal } from '${packageName}';
${
  platform === 'react'
    ? `
import { Button as ReactButton, Portal as ReactPortal } from '@vellira-ui/react';`
    : `
import { Button as NativeButton } from '@vellira-ui/react-native';`
}

<Modal${propsText}>
${children}
</Modal>`;
}

export function ModalUsage({ platform }: ModalUsageProps) {
  const [value] = useComponentDemoState<ModalPlaygroundValue>(
    initialModalPlaygroundValue
  );

  const code = createModalCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
