// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Modal } from '@vellira-ui/react-native';
import { Button as NativeButton } from '@vellira-ui/react-native';

import { ModalPlayground } from './ModalPlayground';

export function NativeModalDemo() {
  return (
    <ModalPlayground
      renderModal={(value, onChange) => (
        <Modal
          open={value.open}
          onOpenChange={(nextValue) => onChange('open', nextValue)}
          closeOnOutsidePress={value.closeOnOutsidePress}
          closeOnEscape={value.closeOnEscape}
          animation={value.animation}
          easing={value.easing}
          restoreFocus={value.restoreFocus}
        >
          <Modal.Trigger asChild>
            <NativeButton>Open Modal</NativeButton>
          </Modal.Trigger>
          <Modal.Overlay>
            <Modal.Content>
              <Modal.Header>
                <Modal.Title>Delete file</Modal.Title>
                <Modal.Description>
                  This action uses the native overlay stack and focus restore.
                </Modal.Description>
              </Modal.Header>
              <Modal.Body>Are you sure you want to continue?</Modal.Body>
              <Modal.Footer>
                <Modal.Close>
                  <NativeButton color='neutral' appearance='solid'>
                    Cancel
                  </NativeButton>
                </Modal.Close>
                <Modal.Close>
                  <NativeButton color='danger' appearance='solid'>
                    Delete
                  </NativeButton>
                </Modal.Close>
              </Modal.Footer>
            </Modal.Content>
          </Modal.Overlay>
        </Modal>
      )}
    />
  );
}
