// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type AccordionAccessibilityProps = {
  platform: ComponentPlatform;
};

export function AccordionAccessibility({
  platform,
}: AccordionAccessibilityProps) {
  const reactItems = [
    {
      title: 'Keyboard operation',
      description:
        'Triggers are native buttons. Tab to a trigger and use Enter or Space to expand or collapse its section.',
      props: ['disabled'],
    },
    {
      title: 'Expanded state',
      description:
        'Each trigger exposes its expanded state and references the content panel it controls.',
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Screen reader support',
      description:
        'Triggers expose button semantics, disabled and expanded state, plus a hint describing the resulting action.',
      props: ['disabled'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
