// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Accordion } from '@vellira-ui/react';

import { AccordionPlayground } from './AccordionPlayground';

export function AccordionDemo() {
  return (
    <AccordionPlayground
      platform='react'
      renderAccordion={(value, onChange) => (
        <Accordion
          value={value.value || undefined}
          onValueChange={(nextValue) => onChange('value', nextValue)}
          collapsible={value.collapsible}
          disabled={value.disabled}
        >
          <Accordion.Item value='profile'>
            <Accordion.Trigger>Profile settings</Accordion.Trigger>
            <Accordion.Content>
              Update your public profile and account details.
            </Accordion.Content>
          </Accordion.Item>
          <Accordion.Item value='notifications'>
            <Accordion.Trigger>Notifications</Accordion.Trigger>
            <Accordion.Content>
              Choose when you want to receive updates.
            </Accordion.Content>
          </Accordion.Item>
        </Accordion>
      )}
    />
  );
}
