// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Accordion as ReactAccordion } from '@vellira-ui/react';
import { Accordion as NativeAccordion } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';
import { useState } from 'react';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

function ReactAccordionExample4Preview() {
  const [value, setValue] = useState('security');

  return (
    <ReactAccordion value={value} onValueChange={setValue}>
      <ReactAccordion.Item value='profile'>
        <ReactAccordion.Trigger>Profile</ReactAccordion.Trigger>
        <ReactAccordion.Content>
          Profile visibility and contact details can be updated here.
        </ReactAccordion.Content>
      </ReactAccordion.Item>
      <ReactAccordion.Item value='security'>
        <ReactAccordion.Trigger>Security</ReactAccordion.Trigger>
        <ReactAccordion.Content>
          Password, passkey, and recovery settings are managed in this section.
        </ReactAccordion.Content>
      </ReactAccordion.Item>
    </ReactAccordion>
  );
}

function NativeAccordionExample4Preview() {
  const [value, setValue] = useState('security');

  return (
    <NativeAccordion value={value} onValueChange={setValue}>
      <NativeAccordion.Item value='profile'>
        <NativeAccordion.Trigger>Profile</NativeAccordion.Trigger>
        <NativeAccordion.Content>
          <NativeText
            style={{
              fontFamily: 'VelliraSans-Regular',
              fontSize: 16,
              lineHeight: 22,
            }}
          >
            Profile visibility and contact details can be updated here.
          </NativeText>
        </NativeAccordion.Content>
      </NativeAccordion.Item>
      <NativeAccordion.Item value='security'>
        <NativeAccordion.Trigger>Security</NativeAccordion.Trigger>
        <NativeAccordion.Content>
          <NativeText
            style={{
              fontFamily: 'VelliraSans-Regular',
              fontSize: 16,
              lineHeight: 22,
            }}
          >
            Password, passkey, and recovery settings are managed in this
            section.
          </NativeText>
        </NativeAccordion.Content>
      </NativeAccordion.Item>
    </NativeAccordion>
  );
}

type AccordionExamplesProps = {
  platform: ComponentPlatform;
};

export function AccordionExamples({ platform }: AccordionExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description:
        'A single accordion keeps one settings section visible at a time.',
      preview: (
        <ReactAccordion>
          <ReactAccordion.Item value='profile'>
            <ReactAccordion.Trigger>Profile settings</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Update your public profile and account details.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
          <ReactAccordion.Item value='notifications'>
            <ReactAccordion.Trigger>Notifications</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Choose when you want to receive updates.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
        </ReactAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react';

<Accordion>
  <Accordion.Item value='profile'>
    <Accordion.Trigger>Profile settings</Accordion.Trigger>
    <Accordion.Content>Update your public profile and account details.</Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='notifications'>
    <Accordion.Trigger>Notifications</Accordion.Trigger>
    <Accordion.Content>Choose when you want to receive updates.</Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Multiple open items',
      description:
        'Use multiple mode when people need to compare information across sections.',
      preview: (
        <ReactAccordion type='multiple' defaultValue={['billing', 'limits']}>
          <ReactAccordion.Item value='billing'>
            <ReactAccordion.Trigger>Billing cadence</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Invoices are issued monthly with a separate annual tax summary.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
          <ReactAccordion.Item value='limits'>
            <ReactAccordion.Trigger>Usage limits</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Workspace exports include the last 90 days by default.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
          <ReactAccordion.Item value='retention'>
            <ReactAccordion.Trigger>Data retention</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Audit logs remain searchable for one year on business plans.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
        </ReactAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react';

<Accordion
  type='multiple'
  defaultValue={['billing', 'limits']}
>
  <Accordion.Item value='billing'>
    <Accordion.Trigger>Billing cadence</Accordion.Trigger>
    <Accordion.Content>Invoices are issued monthly with a separate annual tax summary.</Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='limits'>
    <Accordion.Trigger>Usage limits</Accordion.Trigger>
    <Accordion.Content>Workspace exports include the last 90 days by default.</Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='retention'>
    <Accordion.Trigger>Data retention</Accordion.Trigger>
    <Accordion.Content>Audit logs remain searchable for one year on business plans.</Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Collapsible single item',
      description:
        'Allow the current section to close when the interface can return to an empty state.',
      preview: (
        <ReactAccordion collapsible defaultValue='profile'>
          <ReactAccordion.Item value='profile'>
            <ReactAccordion.Trigger>Profile settings</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Update your public profile and account details.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
          <ReactAccordion.Item value='notifications'>
            <ReactAccordion.Trigger>Notifications</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Choose when you want to receive updates.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
        </ReactAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react';

<Accordion
  collapsible
  defaultValue='profile'
>
  <Accordion.Item value='profile'>
    <Accordion.Trigger>Profile settings</Accordion.Trigger>
    <Accordion.Content>Update your public profile and account details.</Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='notifications'>
    <Accordion.Trigger>Notifications</Accordion.Trigger>
    <Accordion.Content>Choose when you want to receive updates.</Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Controlled state',
      description:
        'Store the open section in application state when another part of the interface needs to control it.',
      preview: <ReactAccordionExample4Preview />,
      code: `import { Accordion } from '@vellira-ui/react';
import { useState } from 'react';

function Example() {
  const [value, setValue] = useState('security');

  return (
    <Accordion
      value={value}
      onValueChange={setValue}
    >
      <Accordion.Item value='profile'>
        <Accordion.Trigger>Profile</Accordion.Trigger>
        <Accordion.Content>Profile visibility and contact details can be updated here.</Accordion.Content>
      </Accordion.Item>
      <Accordion.Item value='security'>
        <Accordion.Trigger>Security</Accordion.Trigger>
        <Accordion.Content>Password, passkey, and recovery settings are managed in this section.</Accordion.Content>
      </Accordion.Item>
    </Accordion>
  );
}`,
    },
    {
      title: 'Default expanded state',
      description:
        'Set an initial expanded item while keeping later changes uncontrolled.',
      preview: (
        <ReactAccordion defaultValue='notifications'>
          <ReactAccordion.Item value='profile'>
            <ReactAccordion.Trigger>Profile settings</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Update your public profile and account details.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
          <ReactAccordion.Item value='notifications'>
            <ReactAccordion.Trigger>Notifications</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Choose when you want to receive updates.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
        </ReactAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react';

<Accordion
  defaultValue='notifications'
>
  <Accordion.Item value='profile'>
    <Accordion.Trigger>Profile settings</Accordion.Trigger>
    <Accordion.Content>Update your public profile and account details.</Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='notifications'>
    <Accordion.Trigger>Notifications</Accordion.Trigger>
    <Accordion.Content>Choose when you want to receive updates.</Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Disabled state',
      description:
        'Disable the whole accordion or a single item while preserving visible context.',
      preview: (
        <ReactAccordion>
          <ReactAccordion.Item value='billing'>
            <ReactAccordion.Trigger>Billing</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              View invoices and payment methods.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
          <ReactAccordion.Item value='audit' disabled>
            <ReactAccordion.Trigger>Audit exports</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Audit exports are available after the first report is generated.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
        </ReactAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react';

<Accordion>
  <Accordion.Item value='billing'>
    <Accordion.Trigger>Billing</Accordion.Trigger>
    <Accordion.Content>View invoices and payment methods.</Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='audit' disabled>
    <Accordion.Trigger>Audit exports</Accordion.Trigger>
    <Accordion.Content>Audit exports are available after the first report is generated.</Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Rich content',
      description:
        'Panels can contain structured content for support notes or account summaries.',
      preview: (
        <ReactAccordion defaultValue='handoff'>
          <ReactAccordion.Item value='handoff'>
            <ReactAccordion.Trigger>Support handoff</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              <p>
                Include ownership, status, and next action so the next teammate
                can continue without opening another view.
              </p>
              <ul>
                <li>Owner: Customer operations</li>
                <li>Status: Waiting for workspace admin</li>
                <li>Next action: Confirm billing contact</li>
              </ul>
            </ReactAccordion.Content>
          </ReactAccordion.Item>
          <ReactAccordion.Item value='history'>
            <ReactAccordion.Trigger>Recent history</ReactAccordion.Trigger>
            <ReactAccordion.Content>
              Four workspace settings changed in the last seven days.
            </ReactAccordion.Content>
          </ReactAccordion.Item>
        </ReactAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react';

<Accordion
  defaultValue='handoff'
>
  <Accordion.Item value='handoff'>
    <Accordion.Trigger>Support handoff</Accordion.Trigger>
    <Accordion.Content>
      <p>Include ownership, status, and next action so the next teammate can continue without opening another view.</p>
      <ul>
        <li>Owner: Customer operations</li>
        <li>Status: Waiting for workspace admin</li>
        <li>Next action: Confirm billing contact</li>
      </ul>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='history'>
    <Accordion.Trigger>Recent history</Accordion.Trigger>
    <Accordion.Content>Four workspace settings changed in the last seven days.</Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description:
        'A single accordion keeps one settings section visible at a time.',
      preview: (
        <NativeAccordion>
          <NativeAccordion.Item value='profile'>
            <NativeAccordion.Trigger>Profile settings</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Update your public profile and account details.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
          <NativeAccordion.Item value='notifications'>
            <NativeAccordion.Trigger>Notifications</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Choose when you want to receive updates.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
        </NativeAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';

<Accordion>
  <Accordion.Item value='profile'>
    <Accordion.Trigger>Profile settings</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Update your public profile and account details.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='notifications'>
    <Accordion.Trigger>Notifications</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Choose when you want to receive updates.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Multiple open items',
      description:
        'Use multiple mode when people need to compare information across sections.',
      preview: (
        <NativeAccordion type='multiple' defaultValue={['billing', 'limits']}>
          <NativeAccordion.Item value='billing'>
            <NativeAccordion.Trigger>Billing cadence</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Invoices are issued monthly with a separate annual tax summary.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
          <NativeAccordion.Item value='limits'>
            <NativeAccordion.Trigger>Usage limits</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Workspace exports include the last 90 days by default.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
          <NativeAccordion.Item value='retention'>
            <NativeAccordion.Trigger>Data retention</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Audit logs remain searchable for one year on business plans.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
        </NativeAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';

<Accordion
  type='multiple'
  defaultValue={['billing', 'limits']}
>
  <Accordion.Item value='billing'>
    <Accordion.Trigger>Billing cadence</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Invoices are issued monthly with a separate annual tax summary.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='limits'>
    <Accordion.Trigger>Usage limits</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Workspace exports include the last 90 days by default.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='retention'>
    <Accordion.Trigger>Data retention</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Audit logs remain searchable for one year on business plans.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Collapsible single item',
      description:
        'Allow the current section to close when the interface can return to an empty state.',
      preview: (
        <NativeAccordion collapsible defaultValue='profile'>
          <NativeAccordion.Item value='profile'>
            <NativeAccordion.Trigger>Profile settings</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Update your public profile and account details.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
          <NativeAccordion.Item value='notifications'>
            <NativeAccordion.Trigger>Notifications</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Choose when you want to receive updates.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
        </NativeAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';

<Accordion
  collapsible
  defaultValue='profile'
>
  <Accordion.Item value='profile'>
    <Accordion.Trigger>Profile settings</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Update your public profile and account details.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='notifications'>
    <Accordion.Trigger>Notifications</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Choose when you want to receive updates.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Controlled state',
      description:
        'Store the open section in application state when another part of the interface needs to control it.',
      preview: <NativeAccordionExample4Preview />,
      code: `import { Accordion } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';
import { useState } from 'react';

function Example() {
  const [value, setValue] = useState('security');

  return (
    <Accordion
      value={value}
      onValueChange={setValue}
    >
      <Accordion.Item value='profile'>
        <Accordion.Trigger>Profile</Accordion.Trigger>
        <Accordion.Content>
          <NativeText
            style={{
            fontFamily: 'VelliraSans-Regular',
            fontSize: 16,
            lineHeight: 22,
          }}
          >
            Profile visibility and contact details can be updated here.
          </NativeText>
        </Accordion.Content>
      </Accordion.Item>
      <Accordion.Item value='security'>
        <Accordion.Trigger>Security</Accordion.Trigger>
        <Accordion.Content>
          <NativeText
            style={{
            fontFamily: 'VelliraSans-Regular',
            fontSize: 16,
            lineHeight: 22,
          }}
          >
            Password, passkey, and recovery settings are managed in this section.
          </NativeText>
        </Accordion.Content>
      </Accordion.Item>
    </Accordion>
  );
}`,
    },
    {
      title: 'Default expanded state',
      description:
        'Set an initial expanded item while keeping later changes uncontrolled.',
      preview: (
        <NativeAccordion defaultValue='notifications'>
          <NativeAccordion.Item value='profile'>
            <NativeAccordion.Trigger>Profile settings</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Update your public profile and account details.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
          <NativeAccordion.Item value='notifications'>
            <NativeAccordion.Trigger>Notifications</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Choose when you want to receive updates.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
        </NativeAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';

<Accordion
  defaultValue='notifications'
>
  <Accordion.Item value='profile'>
    <Accordion.Trigger>Profile settings</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Update your public profile and account details.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='notifications'>
    <Accordion.Trigger>Notifications</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Choose when you want to receive updates.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Disabled state',
      description:
        'Disable the whole accordion or a single item while preserving visible context.',
      preview: (
        <NativeAccordion>
          <NativeAccordion.Item value='billing'>
            <NativeAccordion.Trigger>Billing</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                View invoices and payment methods.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
          <NativeAccordion.Item value='audit' disabled>
            <NativeAccordion.Trigger>Audit exports</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Audit exports are available after the first report is generated.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
        </NativeAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';

<Accordion>
  <Accordion.Item value='billing'>
    <Accordion.Trigger>Billing</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        View invoices and payment methods.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='audit' disabled>
    <Accordion.Trigger>Audit exports</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Audit exports are available after the first report is generated.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
    {
      title: 'Rich content',
      description:
        'Panels can contain structured content for support notes or account summaries.',
      preview: (
        <NativeAccordion defaultValue='handoff'>
          <NativeAccordion.Item value='handoff'>
            <NativeAccordion.Trigger>Support handoff</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Include ownership, status, and next action so the next teammate
                can continue without opening another view.
              </NativeText>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Owner: Customer operations
              </NativeText>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Status: Waiting for workspace admin
              </NativeText>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Next action: Confirm billing contact
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
          <NativeAccordion.Item value='history'>
            <NativeAccordion.Trigger>Recent history</NativeAccordion.Trigger>
            <NativeAccordion.Content>
              <NativeText
                style={{
                  fontFamily: 'VelliraSans-Regular',
                  fontSize: 16,
                  lineHeight: 22,
                }}
              >
                Four workspace settings changed in the last seven days.
              </NativeText>
            </NativeAccordion.Content>
          </NativeAccordion.Item>
        </NativeAccordion>
      ),
      code: `import { Accordion } from '@vellira-ui/react-native';
import { Text as NativeText } from 'react-native';

<Accordion
  defaultValue='handoff'
>
  <Accordion.Item value='handoff'>
    <Accordion.Trigger>Support handoff</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Include ownership, status, and next action so the next teammate can continue without opening another view.
      </NativeText>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Owner: Customer operations
      </NativeText>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Status: Waiting for workspace admin
      </NativeText>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Next action: Confirm billing contact
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item value='history'>
    <Accordion.Trigger>Recent history</Accordion.Trigger>
    <Accordion.Content>
      <NativeText
        style={{
        fontFamily: 'VelliraSans-Regular',
        fontSize: 16,
        lineHeight: 22,
      }}
      >
        Four workspace settings changed in the last seven days.
      </NativeText>
    </Accordion.Content>
  </Accordion.Item>
</Accordion>`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
