// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Select } from '@vellira-ui/react-native';

import { SelectPlayground } from './SelectPlayground';

export function NativeSelectDemo() {
  return (
    <SelectPlayground
      renderSelect={(value) => (
        <Select
          presentation='popover'
          matchTriggerWidth
          placeholder={value.placeholder || undefined}
          size={value.size}
          color={value.color}
          variant={value.variant}
          invalid={value.invalid}
          loading={value.loading}
          clearable={value.clearable}
          searchable={value.searchable}
          error={value.error || undefined}
          disabled={value.disabled}
          label='Favorite framework'
          description='Choose one option.'
        >
          <Select.Item value='react' label='React' />
          <Select.Item value='vue' label='Vue' />
          <Select.Item value='svelte' label='Svelte' />
        </Select>
      )}
    />
  );
}
