// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { selectPlaygroundControls } from './selectPlaygroundSchema';

export type SelectPlaygroundValue = {
  placeholder: string;
  size: 'sm' | 'md' | 'lg';
  color: 'primary' | 'neutral' | 'success' | 'warning' | 'danger';
  variant: 'outline' | 'filled' | 'soft';
  invalid: boolean;
  loading: boolean;
  clearable: boolean;
  searchable: boolean;
  error: string;
  disabled: boolean;
};

type SelectPlaygroundProps = {
  renderSelect: (
    value: SelectPlaygroundValue,
    onChange: <K extends keyof SelectPlaygroundValue>(
      key: K,
      nextValue: SelectPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialSelectPlaygroundValue: SelectPlaygroundValue = {
  placeholder: 'Select an option',
  size: 'md',
  color: 'primary',
  variant: 'outline',
  invalid: false,
  loading: false,
  clearable: false,
  searchable: false,
  error: '',
  disabled: false,
};

export function SelectPlayground({ renderSelect }: SelectPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<SelectPlaygroundValue>(
    initialSelectPlaygroundValue
  );

  const update = (
    key: keyof SelectPlaygroundValue,
    nextValue: SelectPlaygroundValue[keyof SelectPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='auto'
      controls={
        <PlaygroundControlsFromSchema
          value={value}
          controls={selectPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderSelect(value, update)}
    </ComponentPlayground>
  );
}
