// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Select as ReactSelect } from '@vellira-ui/react';
import { Select as NativeSelect } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type SelectExamplesProps = {
  platform: ComponentPlatform;
};

export function SelectExamples({ platform }: SelectExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Basic component usage.',
      preview: (
        <ReactSelect
          label='Favorite framework'
          description='Choose one option.'
        >
          <ReactSelect.Item value='react'>React</ReactSelect.Item>
          <ReactSelect.Item value='vue'>Vue</ReactSelect.Item>
          <ReactSelect.Item value='svelte'>Svelte</ReactSelect.Item>
        </ReactSelect>
      ),
      code: `import { Select } from '@vellira-ui/react';

<Select
  label='Favorite framework'
  description='Choose one option.'
>
  <Select.Item value='react'>React</Select.Item>
  <Select.Item value='vue'>Vue</Select.Item>
  <Select.Item value='svelte'>Svelte</Select.Item>
</Select>`,
    },
    {
      title: 'Searchable',
      description: 'Filter options by typing a search query.',
      preview: (
        <ReactSelect
          label='Favorite framework'
          description='Choose one option.'
          searchable
        >
          <ReactSelect.Item value='react'>React</ReactSelect.Item>
          <ReactSelect.Item value='vue'>Vue</ReactSelect.Item>
          <ReactSelect.Item value='svelte'>Svelte</ReactSelect.Item>
        </ReactSelect>
      ),
      code: `import { Select } from '@vellira-ui/react';

<Select
  label='Favorite framework'
  description='Choose one option.'
  searchable
>
  <Select.Item value='react'>React</Select.Item>
  <Select.Item value='vue'>Vue</Select.Item>
  <Select.Item value='svelte'>Svelte</Select.Item>
</Select>`,
    },
    {
      title: 'Multiple',
      description: 'Select more than one option.',
      preview: (
        <ReactSelect
          label='Favorite framework'
          description='Choose one option.'
          multiple
        >
          <ReactSelect.Item value='react'>React</ReactSelect.Item>
          <ReactSelect.Item value='vue'>Vue</ReactSelect.Item>
          <ReactSelect.Item value='svelte'>Svelte</ReactSelect.Item>
        </ReactSelect>
      ),
      code: `import { Select } from '@vellira-ui/react';

<Select
  label='Favorite framework'
  description='Choose one option.'
  multiple
>
  <Select.Item value='react'>React</Select.Item>
  <Select.Item value='vue'>Vue</Select.Item>
  <Select.Item value='svelte'>Svelte</Select.Item>
</Select>`,
    },
    {
      title: 'Error',
      description: 'Validation error state.',
      preview: (
        <ReactSelect
          label='Favorite framework'
          description='Choose one option.'
          error='Please review this option.'
        >
          <ReactSelect.Item value='react'>React</ReactSelect.Item>
          <ReactSelect.Item value='vue'>Vue</ReactSelect.Item>
          <ReactSelect.Item value='svelte'>Svelte</ReactSelect.Item>
        </ReactSelect>
      ),
      code: `import { Select } from '@vellira-ui/react';

<Select
  label='Favorite framework'
  description='Choose one option.'
  error='Please review this option.'
>
  <Select.Item value='react'>React</Select.Item>
  <Select.Item value='vue'>Vue</Select.Item>
  <Select.Item value='svelte'>Svelte</Select.Item>
</Select>`,
    },
    {
      title: 'Disabled',
      description: 'Disabled select state.',
      preview: (
        <ReactSelect
          label='Favorite framework'
          description='Choose one option.'
          disabled
        >
          <ReactSelect.Item value='react'>React</ReactSelect.Item>
          <ReactSelect.Item value='vue'>Vue</ReactSelect.Item>
          <ReactSelect.Item value='svelte'>Svelte</ReactSelect.Item>
        </ReactSelect>
      ),
      code: `import { Select } from '@vellira-ui/react';

<Select
  label='Favorite framework'
  description='Choose one option.'
  disabled
>
  <Select.Item value='react'>React</Select.Item>
  <Select.Item value='vue'>Vue</Select.Item>
  <Select.Item value='svelte'>Svelte</Select.Item>
</Select>`,
    },
    {
      title: 'Loading',
      description: 'Loading state while options are being resolved.',
      preview: (
        <ReactSelect
          label='Favorite framework'
          description='Choose one option.'
          loading
        >
          <ReactSelect.Item value='react'>React</ReactSelect.Item>
          <ReactSelect.Item value='vue'>Vue</ReactSelect.Item>
          <ReactSelect.Item value='svelte'>Svelte</ReactSelect.Item>
        </ReactSelect>
      ),
      code: `import { Select } from '@vellira-ui/react';

<Select
  label='Favorite framework'
  description='Choose one option.'
  loading
>
  <Select.Item value='react'>React</Select.Item>
  <Select.Item value='vue'>Vue</Select.Item>
  <Select.Item value='svelte'>Svelte</Select.Item>
</Select>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Basic component usage.',
      preview: (
        <NativeSelect
          presentation='popover'
          matchTriggerWidth
          label='Favorite framework'
          description='Choose one option.'
        >
          <NativeSelect.Item value='react' label='React' />
          <NativeSelect.Item value='vue' label='Vue' />
          <NativeSelect.Item value='svelte' label='Svelte' />
        </NativeSelect>
      ),
      code: `import { Select } from '@vellira-ui/react-native';

<Select
  presentation='popover'
  matchTriggerWidth
  label='Favorite framework'
  description='Choose one option.'
>
  <Select.Item value='react' label='React' />
  <Select.Item value='vue' label='Vue' />
  <Select.Item value='svelte' label='Svelte' />
</Select>`,
    },
    {
      title: 'Searchable',
      description: 'Filter options by typing a search query.',
      preview: (
        <NativeSelect
          presentation='popover'
          matchTriggerWidth
          label='Favorite framework'
          description='Choose one option.'
          searchable
        >
          <NativeSelect.Item value='react' label='React' />
          <NativeSelect.Item value='vue' label='Vue' />
          <NativeSelect.Item value='svelte' label='Svelte' />
        </NativeSelect>
      ),
      code: `import { Select } from '@vellira-ui/react-native';

<Select
  presentation='popover'
  matchTriggerWidth
  label='Favorite framework'
  description='Choose one option.'
  searchable
>
  <Select.Item value='react' label='React' />
  <Select.Item value='vue' label='Vue' />
  <Select.Item value='svelte' label='Svelte' />
</Select>`,
    },
    {
      title: 'Multiple',
      description: 'Select more than one option.',
      preview: (
        <NativeSelect
          presentation='popover'
          matchTriggerWidth
          label='Favorite framework'
          description='Choose one option.'
          multiple
        >
          <NativeSelect.Item value='react' label='React' />
          <NativeSelect.Item value='vue' label='Vue' />
          <NativeSelect.Item value='svelte' label='Svelte' />
        </NativeSelect>
      ),
      code: `import { Select } from '@vellira-ui/react-native';

<Select
  presentation='popover'
  matchTriggerWidth
  label='Favorite framework'
  description='Choose one option.'
  multiple
>
  <Select.Item value='react' label='React' />
  <Select.Item value='vue' label='Vue' />
  <Select.Item value='svelte' label='Svelte' />
</Select>`,
    },
    {
      title: 'Error',
      description: 'Validation error state.',
      preview: (
        <NativeSelect
          presentation='popover'
          matchTriggerWidth
          label='Favorite framework'
          description='Choose one option.'
          error='Please review this option.'
        >
          <NativeSelect.Item value='react' label='React' />
          <NativeSelect.Item value='vue' label='Vue' />
          <NativeSelect.Item value='svelte' label='Svelte' />
        </NativeSelect>
      ),
      code: `import { Select } from '@vellira-ui/react-native';

<Select
  presentation='popover'
  matchTriggerWidth
  label='Favorite framework'
  description='Choose one option.'
  error='Please review this option.'
>
  <Select.Item value='react' label='React' />
  <Select.Item value='vue' label='Vue' />
  <Select.Item value='svelte' label='Svelte' />
</Select>`,
    },
    {
      title: 'Disabled',
      description: 'Disabled select state.',
      preview: (
        <NativeSelect
          presentation='popover'
          matchTriggerWidth
          label='Favorite framework'
          description='Choose one option.'
          disabled
        >
          <NativeSelect.Item value='react' label='React' />
          <NativeSelect.Item value='vue' label='Vue' />
          <NativeSelect.Item value='svelte' label='Svelte' />
        </NativeSelect>
      ),
      code: `import { Select } from '@vellira-ui/react-native';

<Select
  presentation='popover'
  matchTriggerWidth
  label='Favorite framework'
  description='Choose one option.'
  disabled
>
  <Select.Item value='react' label='React' />
  <Select.Item value='vue' label='Vue' />
  <Select.Item value='svelte' label='Svelte' />
</Select>`,
    },
    {
      title: 'Loading',
      description: 'Loading state while options are being resolved.',
      preview: (
        <NativeSelect
          presentation='popover'
          matchTriggerWidth
          label='Favorite framework'
          description='Choose one option.'
          loading
        >
          <NativeSelect.Item value='react' label='React' />
          <NativeSelect.Item value='vue' label='Vue' />
          <NativeSelect.Item value='svelte' label='Svelte' />
        </NativeSelect>
      ),
      code: `import { Select } from '@vellira-ui/react-native';

<Select
  presentation='popover'
  matchTriggerWidth
  label='Favorite framework'
  description='Choose one option.'
  loading
>
  <Select.Item value='react' label='React' />
  <Select.Item value='vue' label='Vue' />
  <Select.Item value='svelte' label='Svelte' />
</Select>`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
