import fs from 'node:fs';
import path from 'node:path';

import ts from 'typescript';

import {
  getComponentCatalogDir,
  loadComponentMetadata,
  mergeComponentMetadata,
  validateComponentMetadata,
  type ComponentPageMetadata,
} from './metadata/metadata';
import { getProfileMetadata, inferComponentProfile } from './profiles/profiles';

type Platform = 'react' | 'react-native';

type GeneratedPlatformChildren = Partial<Record<Platform, string>>;

type GeneratedPlatformImports = Partial<Record<Platform, readonly string[]>>;

type GeneratedApiSectionModel = {
  name: string;
  props: readonly ExtractedProp[];
};

type GeneratedApiModel = Record<
  Platform,
  {
    sections: readonly GeneratedApiSectionModel[];
    inheritedProps: readonly ExtractedProp[];
  }
>;

type GeneratedPageModel = {
  componentName: string;
  slug: string;
  platforms: readonly Platform[];
  demo: {
    staticProps: Partial<Record<Platform, string>>;
    children: GeneratedPlatformChildren;
    imports: GeneratedPlatformImports;
    responsivePresentation: boolean;
  };
  playground: {
    props: readonly ExtractedProp[];
    initialValues: Record<string, string | boolean | number>;
  };
  usage: {
    children: GeneratedPlatformChildren;
  };
  examples: readonly GeneratedExample[];
  accessibility: Record<Platform, readonly AccessibilityItem[]>;
  api: GeneratedApiModel;
  related: readonly string[];
};

const [, , componentName, ...args] = process.argv;

const force = args.includes('--force');
const check = args.includes('--check');

if (!componentName) {
  console.error(
    'Usage: pnpm create:component-page ComponentName [--force] [--check]'
  );
  process.exit(1);
}

const root = process.cwd();

const catalogRoot = path.join(
  root,
  'apps',
  'website',
  'src',
  'component-catalog'
);

const catalogComponentsRoot = path.join(catalogRoot, 'components');

const catalogRegistryFile = path.join(
  catalogRoot,
  'registry',
  'componentPages.ts'
);

const componentCatalogDir = getComponentCatalogDir({
  catalogComponentsRoot,
  componentName,
});

const velliraApiSourceRoots = [
  path.join(root, 'packages', 'types', 'src'),
  path.join(root, 'packages', 'types', 'dist'),
  path.join(root, 'packages', 'react', 'src'),
  path.join(root, 'packages', 'react', 'dist'),
  path.join(root, 'packages', 'react-native', 'src'),
  path.join(root, 'packages', 'react-native', 'dist'),
].map((sourceRoot) => path.normalize(sourceRoot));

const slug = componentName.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const generatedFileHeader = `// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

`;

const checkFailures: string[] = [];

function isPathInside(filePath: string, directoryPath: string) {
  const relativePath = path.relative(directoryPath, filePath);

  return (
    Boolean(relativePath) &&
    !relativePath.startsWith('..') &&
    !path.isAbsolute(relativePath)
  );
}

type ApiSectionConfig = NonNullable<
  NonNullable<ComponentPageMetadata['api']>['sections']
>[number];

const componentMetadata = await loadComponentMetadata({
  catalogComponentsRoot,
  componentName,
});

const inferredComponentProfile =
  componentMetadata.profile ?? inferComponentProfile(componentName);

const componentConfig = mergeComponentMetadata(
  getProfileMetadata(inferredComponentProfile),
  componentMetadata
);

validateComponentMetadata({
  componentName,
  metadata: componentConfig,
});

const componentProfile = componentConfig.profile ?? inferredComponentProfile;

function getDemoProps(platform: Platform) {
  if (platform === 'react') {
    return componentConfig.react?.demoProps ?? '';
  }

  return componentConfig.native?.demoProps ?? '';
}

type ExtractedProp = {
  name: string;
  kind: 'boolean' | 'string' | 'number' | 'select' | 'other';
  required: boolean;
  type: string;
  description: string;
  sourceFilePath?: string;
  options?: string[];
};

const typesRoot = path.join(root, 'packages', 'types', 'src');

function findTypeSourceFile(name: string) {
  const candidates = [
    path.join(typesRoot, `${name}.ts`),
    path.join(typesRoot, `${name.charAt(0).toLowerCase()}${name.slice(1)}.ts`),
  ];

  return candidates.find((filePath) => fs.existsSync(filePath));
}

function findPlatformTypeSourceFile(
  platform: Platform,
  name: string
): string | undefined {
  const packageName = platform === 'react' ? 'react' : 'react-native';

  const packageRoot = path.join(root, 'packages', packageName, 'src');
  const stack = [packageRoot];

  while (stack.length > 0) {
    const current = stack.pop();

    if (!current) continue;

    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const fullPath = path.join(current, entry.name);

      if (entry.isDirectory()) {
        stack.push(fullPath);
        continue;
      }

      if (
        entry.name === 'types.ts' &&
        path.basename(path.dirname(fullPath)) === name
      ) {
        return fullPath;
      }
    }
  }

  return undefined;
}

function listPlatformTypeSourceFiles(platform: Platform) {
  const packageName = platform === 'react' ? 'react' : 'react-native';
  const packageRoot = path.join(root, 'packages', packageName, 'src');
  const stack = [packageRoot];
  const files: string[] = [];

  while (stack.length > 0) {
    const current = stack.pop();

    if (!current) continue;

    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const fullPath = path.join(current, entry.name);

      if (entry.isDirectory()) {
        stack.push(fullPath);
        continue;
      }

      if (entry.name === 'types.ts') {
        files.push(fullPath);
      }
    }
  }

  return files;
}

function getSectionExportName(section: ApiSectionConfig, platform: Platform) {
  if (typeof section.exportName === 'string') {
    return section.exportName;
  }

  return section.exportName[platform];
}

function findPlatformExportSourceFile(params: {
  exportName: string;
  platform: Platform;
  program: ts.Program;
}) {
  const { exportName, platform, program } = params;
  const checker = program.getTypeChecker();

  for (const filePath of listPlatformTypeSourceFiles(platform)) {
    const sourceFile = program.getSourceFile(filePath);

    if (!sourceFile) continue;

    const moduleSymbol = checker.getSymbolAtLocation(sourceFile);

    if (!moduleSymbol) continue;

    const hasExport = checker
      .getExportsOfModule(moduleSymbol)
      .some((symbol) => symbol.name === exportName);

    if (hasExport) {
      return filePath;
    }
  }

  return undefined;
}

function createTypesProgram() {
  const tsconfigPath = path.join(root, 'packages', 'types', 'tsconfig.json');

  const configFile = ts.readConfigFile(tsconfigPath, ts.sys.readFile);

  if (configFile.error) {
    const message = ts.flattenDiagnosticMessageText(
      configFile.error.messageText,
      '\n'
    );

    throw new Error(`Failed to read ${tsconfigPath}: ${message}`);
  }

  const parsedConfig = ts.parseJsonConfigFileContent(
    configFile.config,
    ts.sys,
    path.dirname(tsconfigPath)
  );

  return ts.createProgram({
    rootNames: parsedConfig.fileNames,
    options: parsedConfig.options,
  });
}

function createPackageProgram(platform: Platform) {
  const packageName = platform === 'react' ? 'react' : 'react-native';

  const tsconfigPath = path.join(
    root,
    'packages',
    packageName,
    'tsconfig.json'
  );

  const configFile = ts.readConfigFile(tsconfigPath, ts.sys.readFile);

  if (configFile.error) {
    const message = ts.flattenDiagnosticMessageText(
      configFile.error.messageText,
      '\n'
    );

    throw new Error(`Failed to read ${tsconfigPath}: ${message}`);
  }

  const parsedConfig = ts.parseJsonConfigFileContent(
    configFile.config,
    ts.sys,
    path.dirname(tsconfigPath)
  );

  return ts.createProgram({
    rootNames: parsedConfig.fileNames,
    options: parsedConfig.options,
  });
}

function getLiteralUnionOptions(type: ts.Type) {
  if (!type.isUnion()) {
    return null;
  }

  const options: string[] = [];

  for (const item of type.types) {
    if (item.flags & ts.TypeFlags.Undefined) {
      continue;
    }

    if (!item.isStringLiteral()) {
      return null;
    }

    options.push(item.value);
  }

  return options.length > 0 ? options : null;
}

function extractComponentProps(name: string): ExtractedProp[] {
  const sourceFilePath = findTypeSourceFile(
    name.charAt(0).toLowerCase() + name.slice(1)
  );

  if (!sourceFilePath) {
    console.log(`⚠️ Types source not found for ${name}`);
    return [];
  }

  const program = createTypesProgram();
  const checker = program.getTypeChecker();

  const sourceFile = program.getSourceFile(sourceFilePath);

  if (!sourceFile) {
    return [];
  }

  const typeNames = [`Base${name}Props`, `${name}BaseProps`];

  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);

  if (!moduleSymbol) {
    console.log(`⚠️ Module symbol not found for ${sourceFilePath}`);
    return [];
  }

  const exportedSymbol = checker
    .getExportsOfModule(moduleSymbol)
    .find((symbol) => typeNames.includes(symbol.name));

  if (!exportedSymbol) {
    console.log(`⚠️ Export ${typeNames.join(' or ')} not found.`);
    return [];
  }

  const declaredType = checker.getDeclaredTypeOfSymbol(exportedSymbol);

  const propSymbols = checker.getPropertiesOfType(declaredType);

  const extracted: ExtractedProp[] = [];

  for (const propSymbol of propSymbols) {
    const declaration =
      propSymbol.valueDeclaration ?? propSymbol.declarations?.[0];

    if (!declaration) {
      continue;
    }

    const propName = propSymbol.name;

    const required = (propSymbol.flags & ts.SymbolFlags.Optional) === 0;

    const type = checker.getTypeOfSymbolAtLocation(propSymbol, declaration);

    const typeText = checker.typeToString(
      type,
      declaration,
      ts.TypeFormatFlags.NoTruncation
    );

    const description = ts.displayPartsToString(
      propSymbol.getDocumentationComment(checker)
    );

    const unionOptions = getLiteralUnionOptions(type);

    if (unionOptions) {
      extracted.push({
        name: propName,
        kind: 'select',
        required,
        type: typeText,
        description,
        sourceFilePath: declaration.getSourceFile().fileName,
        options: unionOptions,
      });

      continue;
    }

    const nonNullableType = checker.getNonNullableType(type);

    if (nonNullableType.flags & ts.TypeFlags.Boolean) {
      extracted.push({
        name: propName,
        kind: 'boolean',
        required,
        type: typeText,
        description,
        sourceFilePath: declaration.getSourceFile().fileName,
      });

      continue;
    }

    if (
      nonNullableType.flags & ts.TypeFlags.String ||
      nonNullableType.flags & ts.TypeFlags.StringLiteral
    ) {
      extracted.push({
        name: propName,
        kind: 'string',
        required,
        type: typeText,
        description,
        sourceFilePath: declaration.getSourceFile().fileName,
      });

      continue;
    }

    if (
      nonNullableType.flags & ts.TypeFlags.Number ||
      nonNullableType.flags & ts.TypeFlags.NumberLiteral
    ) {
      extracted.push({
        name: propName,
        kind: 'number',
        required,
        type: typeText,
        description,
        sourceFilePath: declaration.getSourceFile().fileName,
      });

      continue;
    }

    extracted.push({
      name: propName,
      kind: 'other',
      required,
      type: typeText,
      description,
      sourceFilePath: declaration.getSourceFile().fileName,
    });
  }

  return extracted;
}

function extractExportedProps(params: {
  sourceFilePath: string;
  exportName: string;
  program: ts.Program;
}): ExtractedProp[] {
  const { sourceFilePath, exportName, program } = params;

  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(sourceFilePath);

  if (!sourceFile) {
    return [];
  }

  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);

  if (!moduleSymbol) {
    return [];
  }

  const exportedSymbol = checker
    .getExportsOfModule(moduleSymbol)
    .find((symbol) => symbol.name === exportName);

  if (!exportedSymbol) {
    console.log(`⚠️ Export ${exportName} not found in ${sourceFilePath}`);
    return [];
  }

  const declaredType = checker.getDeclaredTypeOfSymbol(exportedSymbol);
  const propSymbols = checker.getPropertiesOfType(declaredType);

  const extracted: ExtractedProp[] = [];

  for (const propSymbol of propSymbols) {
    const declaration =
      propSymbol.valueDeclaration ?? propSymbol.declarations?.[0];

    if (!declaration) continue;

    const type = checker.getTypeOfSymbolAtLocation(propSymbol, declaration);

    const typeText = checker.typeToString(
      type,
      declaration,
      ts.TypeFormatFlags.NoTruncation
    );

    const description = ts.displayPartsToString(
      propSymbol.getDocumentationComment(checker)
    );

    const unionOptions = getLiteralUnionOptions(type);
    const nonNullableType = checker.getNonNullableType(type);

    let kind: ExtractedProp['kind'] = 'other';

    if (unionOptions) {
      kind = 'select';
    } else if (nonNullableType.flags & ts.TypeFlags.Boolean) {
      kind = 'boolean';
    } else if (
      nonNullableType.flags & ts.TypeFlags.String ||
      nonNullableType.flags & ts.TypeFlags.StringLiteral
    ) {
      kind = 'string';
    } else if (
      nonNullableType.flags & ts.TypeFlags.Number ||
      nonNullableType.flags & ts.TypeFlags.NumberLiteral
    ) {
      kind = 'number';
    }

    extracted.push({
      name: propSymbol.name,
      kind,
      required: (propSymbol.flags & ts.SymbolFlags.Optional) === 0,
      type: typeText,
      description,
      sourceFilePath: declaration.getSourceFile().fileName,
      ...(unionOptions ? { options: unionOptions } : {}),
    });
  }

  return extracted;
}

const extractedProps = extractComponentProps(componentName);

const excludedControls = new Set(componentConfig.demo?.excludeControls ?? []);

const playgroundProps = extractedProps.filter(
  (prop) =>
    prop.kind !== 'other' &&
    !prop.name.startsWith('on') &&
    !prop.name.startsWith('default') &&
    !excludedControls.has(prop.name)
);

const requiredComplexProps = extractedProps.filter(
  (prop) => prop.required && prop.kind === 'other'
);

const satisfiedRequiredProps = new Set(
  componentConfig.demo?.satisfiedRequiredProps ?? []
);

const missingRequiredComplexProps = requiredComplexProps.filter(
  (prop) =>
    !componentConfig.demo?.staticProps?.[prop.name] &&
    !satisfiedRequiredProps.has(prop.name)
);

if (missingRequiredComplexProps.length > 0) {
  console.warn(
    `⚠️ ${componentName} requires demo values for complex props: ${missingRequiredComplexProps
      .map((prop) => prop.name)
      .join(', ')}`
  );
}

const componentTypeFile = findTypeSourceFile(
  componentName.charAt(0).toLowerCase() + componentName.slice(1)
);

const componentTypeSource = componentTypeFile
  ? fs.readFileSync(componentTypeFile, 'utf8')
  : '';

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function getChangeHandlerName(propName: string) {
  const handlerName = `on${capitalize(propName)}Change`;

  return componentTypeSource.includes(handlerName) ? handlerName : null;
}

function existsInPackage(packageName: 'react' | 'react-native') {
  const packageRoot = path.join(root, 'packages', packageName, 'src');

  const stack = [packageRoot];

  while (stack.length > 0) {
    const current = stack.pop();

    if (!current) continue;

    for (const entry of fs.readdirSync(current, {
      withFileTypes: true,
    })) {
      const fullPath = path.join(current, entry.name);

      if (entry.isDirectory()) {
        if (entry.name === componentName) {
          return true;
        }

        stack.push(fullPath);
      }
    }
  }

  return false;
}

const platforms: Platform[] = [];

if (existsInPackage('react')) {
  platforms.push('react');
}

if (existsInPackage('react-native')) {
  platforms.push('react-native');
}

if (platforms.length === 0) {
  console.error(
    `Component "${componentName}" was not found in react or react-native packages.`
  );
  process.exit(1);
}

function extractPlatformProps(platform: Platform) {
  const sourceFilePath = findPlatformTypeSourceFile(platform, componentName);

  if (!sourceFilePath) {
    console.log(`⚠️ Platform types not found for ${platform}/${componentName}`);
    return [];
  }

  return extractExportedProps({
    sourceFilePath,
    exportName: `${componentName}Props`,
    program: createPackageProgram(platform),
  });
}

const reactApiProps = platforms.includes('react')
  ? extractPlatformProps('react')
  : [];

const nativeApiProps = platforms.includes('react-native')
  ? extractPlatformProps('react-native')
  : [];

function writeIfMissing(filePath: string, content: string) {
  const exists = fs.existsSync(filePath);

  if (check) {
    const currentContent = exists ? fs.readFileSync(filePath, 'utf8') : null;

    if (currentContent !== content) {
      checkFailures.push(path.relative(root, filePath));
    }

    return;
  }

  if (exists && !force) {
    console.log(`⏭ Skipped existing: ${path.relative(root, filePath)}`);
    return;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);

  console.log(
    `${exists ? '♻️ Updated' : '✅ Created'}: ${path.relative(root, filePath)}`
  );
}

const usageDir = componentCatalogDir;

const usageFile = path.join(usageDir, `${componentName}Usage.tsx`);

function createUsageStaticProps(platform: Platform) {
  return [
    getDemoProps(platform) || null,
    componentConfig.demo?.label
      ? `label='${componentConfig.demo.label}'`
      : null,
    componentConfig.demo?.description
      ? `description='${componentConfig.demo.description}'`
      : null,
  ]
    .filter((prop): prop is string => Boolean(prop))
    .map((prop) => `        ${JSON.stringify(prop)},`)
    .join('\n');
}

const reactUsageStaticProps = createUsageStaticProps('react');

const nativeUsageStaticProps = createUsageStaticProps('react-native');

function createUsageChildren(platform: Platform) {
  const children =
    platform === 'react'
      ? (componentConfig.react?.children ?? '')
      : (componentConfig.native?.children ?? '');

  if (!children) {
    return '';
  }

  return children
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');
}

const reactUsageChildren = createUsageChildren('react');

const nativeUsageChildren = createUsageChildren('react-native');

function createPlatformImports(platform: Platform) {
  const imports =
    platform === 'react'
      ? (componentConfig.react?.imports ?? [])
      : (componentConfig.native?.imports ?? []);

  return imports.length > 0 ? `\n${imports.join('\n')}` : '';
}

const reactPlatformImports = createPlatformImports('react');

const nativePlatformImports = createPlatformImports('react-native');

const usageContent = `${generatedFileHeader}'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initial${componentName}PlaygroundValue,
  type ${componentName}PlaygroundValue,
} from './${componentName}Playground';

import styles from '../../shared/ComponentUsage.module.css';

type ${componentName}UsageProps = {
  platform: ComponentPlatform;
};

function create${componentName}Code(
  platform: ComponentPlatform,
  value: ${componentName}PlaygroundValue
) {
  const packageName =
    platform === 'react'
      ? '@vellira-ui/react'
      : '@vellira-ui/react-native';

  const props: string[] =
    platform === 'react'
      ? [
${reactUsageStaticProps}
        ]
      : [
${nativeUsageStaticProps}
        ];

  const children =
    platform === 'react'
      ? ${JSON.stringify(reactUsageChildren)}
      : ${JSON.stringify(nativeUsageChildren)};

${playgroundProps
  .map((prop) => {
    const initialValue = componentConfig.demo?.initialValues?.[prop.name];

    if (prop.kind === 'boolean') {
      return `  if (value.${prop.name}) {
    props.push('${prop.name}');
  }`;
    }

    if (prop.kind === 'string') {
      return `  if (value.${prop.name}) {
    props.push(\`${prop.name}='\${value.${prop.name}}'\`);
  }`;
    }

    if (prop.kind === 'number') {
      return `  if (value.${prop.name} !== ${JSON.stringify(initialValue ?? 0)}) {
    props.push(\`${prop.name}={\${value.${prop.name}}}\`);
  }`;
    }

    return `  if (value.${prop.name} !== ${JSON.stringify(
      initialValue ?? prop.options[0] ?? ''
    )}) {
    props.push(\`${prop.name}='\${value.${prop.name}}'\`);
  }`;
  })
  .join('\n\n')}

  const propsText =
    props.length === 0 ? '' : \`\\n  \${props.join('\\n  ')}\\n\`;

  if (!children) {
    return \`import { ${componentName} } from '\${packageName}';
\${platform === 'react' ? ${JSON.stringify(reactPlatformImports)} : ${JSON.stringify(nativePlatformImports)}}

<${componentName}\${propsText}/>\`;
  }

  return \`import { ${componentName} } from '\${packageName}';
\${platform === 'react' ? ${JSON.stringify(reactPlatformImports)} : ${JSON.stringify(nativePlatformImports)}}

<${componentName}\${propsText}>
\${children}
</${componentName}>\`;
}

export function ${componentName}Usage({
  platform,
}: ${componentName}UsageProps) {
  const [value] =
    useComponentDemoState<${componentName}PlaygroundValue>(
      initial${componentName}PlaygroundValue
    );

  const code = create${componentName}Code(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
`;

writeIfMissing(usageFile, usageContent);

const examplesDir = componentCatalogDir;

const examplesFile = path.join(examplesDir, `${componentName}Examples.tsx`);

type GeneratedExample = {
  title: string;
  description: string;
  props: readonly string[];
  imports?: readonly string[];
  reactImports?: readonly string[];
  nativeImports?: readonly string[];
  reactProps?: readonly string[];
  nativeProps?: readonly string[];
  reactChildren?: string;
  nativeChildren?: string;
  platforms?: readonly Platform[];
};

function hasExtractedProp(name: string) {
  return extractedProps.some((prop) => prop.name === name);
}

function getSelectExample() {
  const prop = playgroundProps.find(
    (item) => item.kind === 'select' && item.options.length > 1
  );

  if (!prop || prop.kind !== 'select') {
    return null;
  }

  const initialValue =
    componentConfig.demo?.initialValues?.[prop.name] ?? prop.options[0];

  const alternative = prop.options.find((option) => option !== initialValue);

  if (!alternative) {
    return null;
  }

  return {
    title: toLabel(prop.name),
    description: `Alternative ${toLabel(prop.name).toLowerCase()} option.`,
    props: [`${prop.name}='${alternative}'`],
  } satisfies GeneratedExample;
}

function createGeneratedExamples(): GeneratedExample[] {
  if (componentConfig.examples) {
    return [...componentConfig.examples];
  }

  const examples: GeneratedExample[] = [
    {
      title: 'Basic',
      description:
        componentProfile === 'overlay'
          ? 'Basic trigger and floating content.'
          : componentProfile === 'navigation'
            ? 'Basic navigation structure.'
            : componentProfile === 'form-control'
              ? 'Basic form control usage.'
              : 'Basic component usage.',
      props: [],
    },
  ];

  if (hasExtractedProp('disabled')) {
    examples.push({
      title: 'Disabled',
      description: 'Disabled state.',
      props: ['disabled'],
    });
  }

  if (hasExtractedProp('checked')) {
    examples.push({
      title: 'Selected',
      description: 'Selected state.',
      props: ['checked'],
    });
  } else if (hasExtractedProp('loading')) {
    examples.push({
      title: 'Loading',
      description: 'Loading state.',
      props: ['loading'],
    });
  } else if (hasExtractedProp('open')) {
    examples.push({
      title: 'Open',
      description: 'Open state.',
      props: ['open'],
    });
  }

  if (hasExtractedProp('error')) {
    examples.push({
      title: 'Error',
      description: 'Validation error state.',
      props: [`error='Please review this option.'`],
    });
  }

  const selectExample = getSelectExample();

  if (selectExample) {
    examples.push(selectExample);
  }

  if (hasExtractedProp('required')) {
    examples.push({
      title: 'Required',
      description: 'Required form control.',
      props: ['required'],
    });
  }

  if (componentProfile === 'compound' && hasExtractedProp('children')) {
    examples.push({
      title: 'Compound usage',
      description: 'Composes the root with public child slots.',
      props: [],
    });
  }

  return examples;
}

const generatedExamples = createGeneratedExamples();

function createExampleJsx(platform: Platform, example: GeneratedExample) {
  const componentAlias =
    platform === 'react' ? `React${componentName}` : `Native${componentName}`;

  const props = [
    getDemoProps(platform),
    componentConfig.demo?.label
      ? `label=${toTsString(componentConfig.demo.label)}`
      : '',
    componentConfig.demo?.description
      ? `description=${toTsString(componentConfig.demo.description)}`
      : '',
    ...example.props,
    ...(platform === 'react'
      ? (example.reactProps ?? [])
      : (example.nativeProps ?? [])),
  ].filter(Boolean);

  const exampleChildren =
    platform === 'react'
      ? (example.reactChildren ?? componentConfig.react?.children ?? '')
      : (example.nativeChildren ?? componentConfig.native?.children ?? '');

  const propsText =
    props.length === 0 ? '' : `\n          ${props.join('\n          ')}`;

  if (!exampleChildren) {
    return `<${componentAlias}${propsText}
        />`;
  }

  const aliasedChildren = exampleChildren
    .replaceAll(`<${componentName}.`, `<${componentAlias}.`)
    .replaceAll(`</${componentName}.`, `</${componentAlias}.`);

  const formattedChildren = aliasedChildren
    .split('\n')
    .map((line) => `          ${line}`)
    .join('\n');

  return `<${componentAlias}${propsText}
        >
${formattedChildren}
        </${componentAlias}>`;
}

function createExampleCode(platform: Platform, example: GeneratedExample) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props = [
    getDemoProps(platform),
    componentConfig.demo?.label
      ? `label=${toTsString(componentConfig.demo.label)}`
      : '',
    componentConfig.demo?.description
      ? `description=${toTsString(componentConfig.demo.description)}`
      : '',
    ...example.props,
    ...(platform === 'react'
      ? (example.reactProps ?? [])
      : (example.nativeProps ?? [])),
  ].filter(Boolean);

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  const exampleChildren =
    platform === 'react'
      ? (example.reactChildren ?? componentConfig.react?.children ?? '')
      : (example.nativeChildren ?? componentConfig.native?.children ?? '');

  if (!exampleChildren) {
    const imports = [
      `import { ${componentName} } from '${packageName}';`,
      ...(example.imports ?? []),
      ...(platform === 'react'
        ? (example.reactImports ?? [])
        : (example.nativeImports ?? [])),
    ].join('\n');

    return `${imports}

<${componentName}${propsText}/>`;
  }

  const formattedChildren = exampleChildren
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');

  const imports = [
    `import { ${componentName} } from '${packageName}';`,
    ...(example.imports ?? []),
    ...(platform === 'react'
      ? (example.reactImports ?? [])
      : (example.nativeImports ?? [])),
  ].join('\n');

  return `${imports}

<${componentName}${propsText}>
${formattedChildren}
</${componentName}>`;
}

function getExamplesForPlatform(platform: Platform) {
  return generatedExamples.filter(
    (example) => !example.platforms || example.platforms.includes(platform)
  );
}

const exampleImports = Array.from(
  new Set(
    generatedExamples.flatMap((example) => [
      ...(example.imports ?? []),
      ...(example.reactImports ?? []),
      ...(example.nativeImports ?? []),
      ...(componentConfig.react?.imports ?? []),
      ...(componentConfig.native?.imports ?? []),
    ])
  )
);

const reactGeneratedExamples = getExamplesForPlatform('react')
  .map(
    (example) => `    {
      title: ${toTsString(example.title)},
      description: ${toTsString(example.description)},
      preview: (
        ${createExampleJsx('react', example)}
      ),
      code: ${JSON.stringify(createExampleCode('react', example))},
    },`
  )
  .join('\n');

const nativeGeneratedExamples = getExamplesForPlatform('react-native')
  .map(
    (example) => `    {
      title: ${toTsString(example.title)},
      description: ${toTsString(example.description)},
      preview: (
        ${createExampleJsx('react-native', example)}
      ),
      code: ${JSON.stringify(createExampleCode('react-native', example))},
    },`
  )
  .join('\n');

const examplesContent = `${generatedFileHeader}'use client';

import { ${componentName} as React${componentName} } from '@vellira-ui/react';
import { ${componentName} as Native${componentName} } from '@vellira-ui/react-native';
${exampleImports.join('\n')}

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type ${componentName}ExamplesProps = {
  platform: ComponentPlatform;
};

export function ${componentName}Examples({
  platform,
}: ${componentName}ExamplesProps) {
  const reactExamples = [
${reactGeneratedExamples}
  ] as const;

  const nativeExamples = [
${nativeGeneratedExamples}
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
`;

writeIfMissing(examplesFile, examplesContent);

const accessibilityDir = componentCatalogDir;

const accessibilityFile = path.join(
  accessibilityDir,
  `${componentName}Accessibility.tsx`
);

function toTsString(value: string) {
  return `'${value
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\n', '\\n')}'`;
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

type AccessibilityItem = {
  title: string;
  description: string;
  props?: readonly string[];
};

function createAccessibilityItems(platform: Platform): AccessibilityItem[] {
  const configuredItems =
    platform === 'react'
      ? componentConfig.accessibility?.react
      : componentConfig.accessibility?.native;

  if (configuredItems) {
    return [...configuredItems];
  }

  const items: AccessibilityItem[] = [];
  const platformProps =
    platform === 'react'
      ? reactApiProps.length > 0
        ? reactApiProps
        : extractedProps
      : nativeApiProps.length > 0
        ? nativeApiProps
        : extractedProps;

  const hasProp = (name: string) =>
    platformProps.some((prop) => prop.name === name);

  const isInteractive =
    hasProp('disabled') ||
    hasProp('checked') ||
    hasProp('selected') ||
    hasProp('open') ||
    hasProp('onPress') ||
    hasProp('onClick') ||
    extractedProps.some((prop) => prop.name.startsWith('on'));

  if (
    componentConfig.demo?.label ||
    hasProp('label') ||
    hasProp('accessibilityLabel')
  ) {
    items.push({
      title: 'Accessible naming',
      description:
        platform === 'react'
          ? 'Provide a visible label or another accessible name that clearly identifies the control.'
          : 'Provide a visible label or accessibilityLabel so screen readers can identify the control.',
      props: ['label', 'children', 'aria-label', 'accessibilityLabel'].filter(
        hasProp
      ),
    });
  }

  if (
    hasProp('checked') ||
    hasProp('selected') ||
    hasProp('open') ||
    hasProp('expanded')
  ) {
    items.push({
      title: 'State communication',
      description:
        platform === 'react'
          ? 'Expose the current interactive state through the appropriate native semantics and keep it synchronized with the visual state.'
          : 'Expose the current interactive state through React Native accessibilityState and keep it synchronized with the visual state.',
      props: ['checked', 'selected', 'open', 'expanded'].filter(hasProp),
    });
  }

  if (hasProp('disabled')) {
    items.push({
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    });
  }

  if (hasProp('error')) {
    items.push({
      title: 'Validation feedback',
      description:
        platform === 'react'
          ? 'Associate validation feedback with the control and expose its invalid state to assistive technologies.'
          : 'Expose validation feedback through accessible text or hints and preserve the invalid state for assistive technologies.',
      props: ['error', 'invalid'].filter(hasProp),
    });
  }

  if (hasProp('required')) {
    items.push({
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    });
  }

  if (isInteractive) {
    items.push({
      title: 'Keyboard and focus',
      description:
        platform === 'react'
          ? 'Preserve expected keyboard interaction and visible focus behavior.'
          : 'Verify focus and screen reader interaction on supported React Native platforms.',
      props: ['onKeyDown', 'onFocus', 'onBlur', 'onPress', 'onClick'].filter(
        hasProp
      ),
    });
  }

  if (items.length === 0) {
    items.push({
      title: 'Accessible usage',
      description:
        platform === 'react'
          ? 'Use semantic markup, accessible naming, and predictable keyboard behavior.'
          : 'Expose meaningful accessibility roles, labels, states, and interaction behavior.',
    });
  }

  if (componentProfile === 'overlay') {
    items.push({
      title: 'Dismissal',
      description:
        platform === 'react'
          ? 'Keep dismissal, focus return, and Escape behavior predictable for overlay interactions.'
          : 'Keep dismissal, back navigation, and screen reader focus predictable for overlay interactions.',
      props: ['open', 'defaultOpen', 'onOpenChange'].filter(hasProp),
    });
  }

  return items;
}

const reactAccessibilityItems = createAccessibilityItems('react')
  .map(
    (item) => `    {
      title: ${toTsString(item.title)},
      description: ${toTsString(item.description)},${
        item.props?.length
          ? `\n      props: [${item.props.map(toTsString).join(', ')}],`
          : ''
      }
    },`
  )
  .join('\n');

const nativeAccessibilityItems = createAccessibilityItems('react-native')
  .map(
    (item) => `    {
      title: ${toTsString(item.title)},
      description: ${toTsString(item.description)},${
        item.props?.length
          ? `\n      props: [${item.props.map(toTsString).join(', ')}],`
          : ''
      }
    },`
  )
  .join('\n');

const accessibilityContent = `${generatedFileHeader}'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type ${componentName}AccessibilityProps = {
  platform: ComponentPlatform;
};

export function ${componentName}Accessibility({
  platform,
}: ${componentName}AccessibilityProps) {
  const reactItems = [
${reactAccessibilityItems}
  ] as const;

  const nativeItems = [
${nativeAccessibilityItems}
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
`;

writeIfMissing(accessibilityFile, accessibilityContent);

const apiFile = path.join(componentCatalogDir, `${slug}Api.ts`);

function cleanApiType(type: string) {
  return type
    .replace(/\s*\|\s*undefined\b/g, '')
    .replace(/\bundefined\s*\|\s*/g, '')
    .trim();
}

function getApiType(prop: ExtractedProp) {
  const sharedProp = getSharedProp(prop);
  const apiProp = isExternalProp(prop) && sharedProp ? sharedProp : prop;

  if (apiProp.kind === 'select' && apiProp.options?.length) {
    return apiProp.options.map((option) => `'${option}'`).join(' | ');
  }

  return cleanApiType(apiProp.type);
}

function getApiDefaultValue(prop: ExtractedProp, platform: Platform) {
  const sharedValue = componentConfig.defaults?.shared?.[prop.name];

  const platformValue =
    platform === 'react'
      ? componentConfig.defaults?.react?.[prop.name]
      : componentConfig.defaults?.native?.[prop.name];

  const value = platformValue ?? sharedValue;

  if (value === undefined) {
    return undefined;
  }

  if (typeof value === 'string') {
    return `'${value}'`;
  }

  return String(value);
}

function isExternalProp(prop: ExtractedProp) {
  if (!prop.sourceFilePath) {
    return false;
  }

  const normalizedSource = path.normalize(prop.sourceFilePath);

  return !velliraApiSourceRoots.some((sourceRoot) =>
    isPathInside(normalizedSource, sourceRoot)
  );
}

function getFallbackApiDescription(prop: ExtractedProp, platform: Platform) {
  if (!isExternalProp(prop)) {
    return `Prop for ${componentName}.`;
  }

  if (platform === 'react') {
    return 'Forwarded React DOM prop.';
  }

  return 'Forwarded React Native prop.';
}

function getSharedProp(prop: ExtractedProp) {
  return extractedProps.find((item) => item.name === prop.name);
}

function isOwnedApiProp(prop: ExtractedProp) {
  return !isExternalProp(prop) || Boolean(getSharedProp(prop));
}

function createApiEntries(props: readonly ExtractedProp[], platform: Platform) {
  return props
    .map((prop) => {
      const defaultValue = getApiDefaultValue(prop, platform);
      const sharedProp = getSharedProp(prop);

      const description =
        componentConfig.api?.descriptions?.[prop.name] ||
        (isExternalProp(prop) ? sharedProp?.description : undefined) ||
        prop.description ||
        sharedProp?.description ||
        getFallbackApiDescription(prop, platform);

      return `  {
    name: ${toTsString(prop.name)},
    type: ${toTsString(getApiType(prop))},${
      defaultValue ? `\n    defaultValue: ${toTsString(defaultValue)},` : ''
    }
    description: ${toTsString(description)},${
      prop.required ? '\n    required: true,' : ''
    }
  },`;
    })
    .join('\n');
}

function splitApiProps(props: readonly ExtractedProp[]) {
  const ownedProps: ExtractedProp[] = [];
  const inheritedProps: ExtractedProp[] = [];

  for (const prop of props) {
    if (isOwnedApiProp(prop)) {
      ownedProps.push(prop);
    } else {
      inheritedProps.push(prop);
    }
  }

  return { ownedProps, inheritedProps };
}

type ApiSectionData = {
  name: string;
  ownedProps: ExtractedProp[];
};

function createConfiguredApiSections(platform: Platform): ApiSectionData[] {
  const program = createPackageProgram(platform);
  const sections: ApiSectionData[] = [];

  for (const section of componentConfig.api?.sections ?? []) {
    const exportName = getSectionExportName(section, platform);

    if (!exportName) continue;

    const sourceFilePath = findPlatformExportSourceFile({
      exportName,
      platform,
      program,
    });

    if (!sourceFilePath) {
      console.log(
        `⚠️ Export ${exportName} not found for ${platform}/${componentName}`
      );
      continue;
    }

    const props = extractExportedProps({
      sourceFilePath,
      exportName,
      program,
    });

    sections.push({
      name: section.name,
      ownedProps: splitApiProps(props).ownedProps,
    });
  }

  return sections.filter((section) => section.ownedProps.length > 0);
}

const reactSplit = splitApiProps(
  reactApiProps.length > 0 ? reactApiProps : extractedProps
);

const nativeSplit = splitApiProps(
  nativeApiProps.length > 0 ? nativeApiProps : extractedProps
);

const reactApiSections = [
  {
    name: componentName,
    ownedProps: reactSplit.ownedProps,
  },
  ...createConfiguredApiSections('react'),
];

const nativeApiSections = [
  {
    name: componentName,
    ownedProps: nativeSplit.ownedProps,
  },
  ...createConfiguredApiSections('react-native'),
];

function createApiSectionEntries(
  sections: readonly ApiSectionData[],
  platform: Platform
) {
  return sections
    .map(
      (section) => `  {
    name: ${toTsString(section.name)},
    props: [
${createApiEntries(section.ownedProps, platform)}
    ],
  },`
    )
    .join('\n');
}

const reactApiSectionEntries = createApiSectionEntries(
  reactApiSections,
  'react'
);

const nativeApiSectionEntries = createApiSectionEntries(
  nativeApiSections,
  'react-native'
);

const reactInheritedApiEntries = createApiEntries(
  reactSplit.inheritedProps,
  'react'
);

const nativeInheritedApiEntries = createApiEntries(
  nativeSplit.inheritedProps,
  'react-native'
);

const apiContent = `${generatedFileHeader}import type {
  ComponentApiProp,
  ComponentApiSection,
} from '../../shared/ComponentApi';

const react${componentName}ApiSections: readonly ComponentApiSection[] = [
${reactApiSectionEntries}
];

const native${componentName}ApiSections: readonly ComponentApiSection[] = [
${nativeApiSectionEntries}
];

const inheritedReact${componentName}Api: readonly ComponentApiProp[] = [
${reactInheritedApiEntries}
];

const inheritedNative${componentName}Api: readonly ComponentApiProp[] = [
${nativeInheritedApiEntries}
];

export const ${slug}Api = {
  react: {
    sections: react${componentName}ApiSections,
    inheritedProps: inheritedReact${componentName}Api,
  },
  'react-native': {
    sections: native${componentName}ApiSections,
    inheritedProps: inheritedNative${componentName}Api,
  },
} as const;
`;

writeIfMissing(apiFile, apiContent);

function insertAfterMarker(params: {
  filePath: string;
  marker: string;
  content: string;
  existsCheck: string;
}) {
  const { filePath, marker, content, existsCheck } = params;

  const originalSource = fs.readFileSync(filePath, 'utf8');
  const source = originalSource;

  if (source.includes(existsCheck)) {
    if (!force) {
      console.log(`⏭ Skipped registry update: ${existsCheck}`);
      return;
    }

    const entryStartMatch = source.match(
      new RegExp(`\\n\\s*${escapeRegExp(slug)}: \\{`)
    );
    const entryStart =
      entryStartMatch?.index !== undefined ? entryStartMatch.index + 1 : -1;

    if (entryStart === -1) {
      console.error(`Existing registry entry not found for ${slug}`);
      process.exit(1);
    }

    const nextEntryMatch = source
      .slice(entryStart + 1)
      .match(/\n {2}[a-z0-9-]+: \{/);

    const registryEndMatch = source
      .slice(entryStart)
      .match(/\n}(?: satisfies [^;]+)?;/);

    const entryEnd =
      nextEntryMatch?.index !== undefined
        ? entryStart + 1 + nextEntryMatch.index
        : registryEndMatch?.index !== undefined
          ? entryStart + registryEndMatch.index
          : -1;

    if (entryEnd === -1) {
      console.error(`Could not determine registry entry boundary for ${slug}`);
      process.exit(1);
    }

    const nextSource =
      source.slice(0, entryStart) + content + source.slice(entryEnd);

    if (check) {
      if (nextSource !== source) {
        checkFailures.push(path.relative(root, filePath));
      }

      return;
    }

    fs.writeFileSync(filePath, nextSource);

    console.log(`♻️ Updated registry: ${existsCheck}`);
    return;
  }

  if (!source.includes(marker)) {
    console.error(`Marker not found in ${filePath}: ${marker}`);
    process.exit(1);
  }

  const nextSource = source.replace(marker, `${marker}\n${content}`);

  if (check) {
    if (nextSource !== source) {
      checkFailures.push(path.relative(root, filePath));
    }

    return;
  }

  fs.writeFileSync(filePath, nextSource);

  console.log(`✅ Updated: ${path.relative(root, filePath)}`);
}

const playgroundDir = componentCatalogDir;

const playgroundSchemaFile = path.join(
  playgroundDir,
  `${slug}PlaygroundSchema.ts`
);

function toLabel(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/^./, (character) => character.toUpperCase());
}

function getInitialValue(prop: ExtractedProp) {
  const configuredValue = componentConfig.demo?.initialValues?.[prop.name];

  if (configuredValue !== undefined) {
    return JSON.stringify(configuredValue);
  }

  if (prop.kind === 'boolean') {
    return 'false';
  }

  if (prop.kind === 'number') {
    return '0';
  }

  if (prop.kind === 'select') {
    return JSON.stringify(prop.options[0] ?? '');
  }

  return prop.required ? JSON.stringify('example') : JSON.stringify('');
}

function getPlaygroundPropBinding(prop: ExtractedProp) {
  const propValue =
    prop.kind === 'string' && !prop.required
      ? `value.${prop.name} || undefined`
      : `value.${prop.name}`;

  const binding = `${prop.name}={${propValue}}`;

  const changeHandler = getChangeHandlerName(prop.name);

  if (!changeHandler) {
    return binding;
  }

  return `${binding}
          ${changeHandler}={(nextValue) =>
            onChange('${prop.name}', nextValue)
          }`;
}

const reactStaticDemoProps = getDemoProps('react');
const nativeStaticDemoProps = getDemoProps('react-native');

const reactDemoChildren = componentConfig.react?.children ?? '';
const nativeDemoChildren = componentConfig.native?.children ?? '';

function isPlaygroundProp(name: string) {
  return playgroundProps.some((prop) => prop.name === name);
}

const demoPresentationProps = [
  componentConfig.demo?.label && !isPlaygroundProp('label')
    ? `label=${toTsString(componentConfig.demo.label)}`
    : null,
  componentConfig.demo?.description && !isPlaygroundProp('description')
    ? `description=${toTsString(componentConfig.demo.description)}`
    : null,
]
  .filter(Boolean)
  .join('\n          ');

const staticDemoProps = Object.entries(componentConfig.demo?.staticProps ?? {})
  .map(([name, value]) => `${name}={${value}}`)
  .join('\n          ');

const playgroundPropBindings = playgroundProps
  .map((prop) => getPlaygroundPropBinding(prop))
  .join('\n          ');

const playgroundValueFields = playgroundProps
  .map((prop) => {
    if (prop.kind === 'boolean') {
      return `  ${prop.name}: boolean;`;
    }

    if (prop.kind === 'number') {
      return `  ${prop.name}: number;`;
    }

    if (prop.kind === 'select') {
      const union = prop.options.map((option) => `'${option}'`).join(' | ');

      return `  ${prop.name}: ${union};`;
    }

    return `  ${prop.name}: string;`;
  })
  .join('\n');

const playgroundInitialValues = playgroundProps
  .map((prop) => `  ${prop.name}: ${getInitialValue(prop)},`)
  .join('\n');

const playgroundControlEntries = playgroundProps
  .map((prop) => {
    const label = toLabel(prop.name);

    if (prop.kind === 'boolean') {
      return `  {
    type: 'toggle',
    key: '${prop.name}',
    label: '${label}',
    group: 'Options',
  },`;
    }

    if (prop.kind === 'select') {
      return `  {
    type: 'select',
    key: '${prop.name}',
    label: '${label}',
    options: [${prop.options.map((option) => `'${option}'`).join(', ')}],
  },`;
    }

    if (prop.kind === 'number') {
      return `  {
    type: 'number',
    key: '${prop.name}',
    label: '${label}',
  },`;
    }

    return `  {
    type: 'text',
    key: '${prop.name}',
    label: '${label}',
  },`;
  })
  .join('\n');

const playgroundSchemaContent = `${generatedFileHeader}import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { ${componentName}PlaygroundValue } from './${componentName}Playground';

export const ${slug}PlaygroundControls = [
${playgroundControlEntries}
] as const satisfies readonly PlaygroundControl<${componentName}PlaygroundValue>[];
`;

writeIfMissing(playgroundSchemaFile, playgroundSchemaContent);

const playgroundFile = path.join(
  playgroundDir,
  `${componentName}Playground.tsx`
);

const playgroundContent = `${generatedFileHeader}'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { ${slug}PlaygroundControls } from './${slug}PlaygroundSchema';

export type ${componentName}PlaygroundValue = {
${playgroundValueFields}
};

type ${componentName}PlaygroundProps = {
  render${componentName}: (
    value: ${componentName}PlaygroundValue,
    onChange: <K extends keyof ${componentName}PlaygroundValue>(
      key: K,
      nextValue: ${componentName}PlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initial${componentName}PlaygroundValue: ${componentName}PlaygroundValue = {
${playgroundInitialValues}
};

export function ${componentName}Playground({
  render${componentName},
}: ${componentName}PlaygroundProps) {
  const [value, setValue] =
    useComponentDemoState<${componentName}PlaygroundValue>(
      initial${componentName}PlaygroundValue
    );

    const update = (
    key: keyof ${componentName}PlaygroundValue,
    nextValue: ${componentName}PlaygroundValue[keyof ${componentName}PlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
    previewWidth=${JSON.stringify(componentConfig.demo?.previewWidth ?? 'auto')}
      controls={
        <PlaygroundControlsFromSchema
          value={value}
          controls={${slug}PlaygroundControls}
          onChange={update}
        />
      }
    >
      {render${componentName}(value, update)}
    </ComponentPlayground>
  );
}
`;

writeIfMissing(playgroundFile, playgroundContent);

const demoEntries = [
  platforms.includes('react') ? `      react: ${componentName}Demo,` : null,
  platforms.includes('react-native')
    ? `      'react-native': Native${componentName}Demo,`
    : null,
]
  .filter(Boolean)
  .join('\n');

const relatedComponents = componentConfig.related ?? [];

const nativeResponsivePresentation =
  componentConfig.native?.responsivePresentation === true;

function createInitialValueMap() {
  return Object.fromEntries(
    playgroundProps.map((prop) => [prop.name, getInitialValue(prop)])
  ) as Record<string, string | boolean | number>;
}

function createGeneratedPageModel(): GeneratedPageModel {
  return {
    componentName,
    slug,
    platforms,
    demo: {
      staticProps: {
        react: reactStaticDemoProps,
        'react-native': nativeStaticDemoProps,
      },
      children: {
        react: reactDemoChildren,
        'react-native': nativeDemoChildren,
      },
      imports: {
        react: componentConfig.react?.imports ?? [],
        'react-native': componentConfig.native?.imports ?? [],
      },
      responsivePresentation: nativeResponsivePresentation,
    },
    playground: {
      props: playgroundProps,
      initialValues: createInitialValueMap(),
    },
    usage: {
      children: {
        react: reactUsageChildren,
        'react-native': nativeUsageChildren,
      },
    },
    examples: generatedExamples,
    accessibility: {
      react: createAccessibilityItems('react'),
      'react-native': createAccessibilityItems('react-native'),
    },
    api: {
      react: {
        sections: reactApiSections.map((section) => ({
          name: section.name,
          props: section.ownedProps,
        })),
        inheritedProps: reactSplit.inheritedProps,
      },
      'react-native': {
        sections: nativeApiSections.map((section) => ({
          name: section.name,
          props: section.ownedProps,
        })),
        inheritedProps: nativeSplit.inheritedProps,
      },
    },
    related: relatedComponents,
  };
}

const generatedPageModel = createGeneratedPageModel();

const pageConfigSnippet = `
  ${slug}: {
    name: '${componentName}',
    demos: {
${demoEntries}
    },
    Usage: ${componentName}Usage,
    Examples: ${componentName}Examples,
    Accessibility: ${componentName}Accessibility,
    api: ${slug}Api,
    related: ${
      generatedPageModel.related.length > 0
        ? `[${generatedPageModel.related.map((item) => `'${item}'`).join(', ')}]`
        : '[]'
    },
  },
`;

const componentPagesFile = catalogRegistryFile;

const reactDemoDir = componentCatalogDir;

const reactDemoFile = path.join(reactDemoDir, `${componentName}Demo.tsx`);

const nativeResponsiveImport = nativeResponsivePresentation
  ? `import { useWindowDimensions } from 'react-native';\n`
  : '';

const nativeResponsiveSetup = nativeResponsivePresentation
  ? `  const { width } = useWindowDimensions();
  const presentation = width <= 890 ? 'sheet' : 'popover';

`
  : '';

function createDemoElement(params: {
  platform: Platform;
  propBindings: string;
}) {
  const { platform, propBindings } = params;

  const children =
    platform === 'react' ? reactDemoChildren : nativeDemoChildren;

  const staticProps =
    platform === 'react' ? reactStaticDemoProps : nativeStaticDemoProps;

  const props = [
    staticProps,
    staticDemoProps,
    platform === 'react-native' && nativeResponsivePresentation
      ? 'presentation={presentation}'
      : '',
    propBindings,
    demoPresentationProps,
  ]
    .filter(Boolean)
    .join('\n          ');

  if (!children) {
    return `<${componentName}
          ${props}
        />`;
  }

  const formattedChildren = children
    .split('\n')
    .map((line) => `          ${line}`)
    .join('\n');

  return `<${componentName}
          ${props}
        >
${formattedChildren}
        </${componentName}>`;
}

const reactDemoElement = createDemoElement({
  platform: 'react',
  propBindings: playgroundPropBindings,
});

const nativeDemoElement = createDemoElement({
  platform: 'react-native',
  propBindings: playgroundPropBindings,
});

const usesDemoValue = playgroundProps.length > 0;

const usesDemoOnChange = playgroundProps.some((prop) =>
  Boolean(getChangeHandlerName(prop.name))
);

const demoRenderParams = usesDemoOnChange
  ? '(value, onChange)'
  : usesDemoValue
    ? '(value)'
    : '()';

const reactDemoContent = `${generatedFileHeader}'use client';

import { ${componentName} } from '@vellira-ui/react';
${componentConfig.react?.imports?.join('\n') ?? ''}

import { ${componentName}Playground } from './${componentName}Playground';

export function ${componentName}Demo() {
  return (
    <${componentName}Playground
      render${componentName}={${demoRenderParams} => (
        ${reactDemoElement}
      )}
    />
  );
}
`;

if (platforms.includes('react')) {
  writeIfMissing(reactDemoFile, reactDemoContent);
}

const nativeDemoDir = componentCatalogDir;

const nativeDemoFile = path.join(
  nativeDemoDir,
  `Native${componentName}Demo.tsx`
);

const nativeDemoContent = `${generatedFileHeader}'use client';

${nativeResponsiveImport}import { ${componentName} } from '@vellira-ui/react-native';
${componentConfig.native?.imports?.join('\n') ?? ''}

import { ${componentName}Playground } from './${componentName}Playground';

export function Native${componentName}Demo() {
${nativeResponsiveSetup}  return (
    <${componentName}Playground
      render${componentName}={${demoRenderParams} => (
        ${nativeDemoElement}
      )}
    />
  );
}
`;

if (platforms.includes('react-native')) {
  writeIfMissing(nativeDemoFile, nativeDemoContent);
}

const componentIndexFile = path.join(componentCatalogDir, 'index.ts');

const componentIndexContent = `${generatedFileHeader}export { ${componentName}Accessibility } from './${componentName}Accessibility';
${platforms.includes('react') ? `export { ${componentName}Demo } from './${componentName}Demo';\n` : ''}export { ${componentName}Examples } from './${componentName}Examples';
export {
  ${componentName}Playground,
  initial${componentName}PlaygroundValue,
} from './${componentName}Playground';
export { ${componentName}Usage } from './${componentName}Usage';
${platforms.includes('react-native') ? `export { Native${componentName}Demo } from './Native${componentName}Demo';\n` : ''}export { ${slug}Api } from './${slug}Api';

export type {
  ${componentName}PlaygroundValue,
} from './${componentName}Playground';
`;

writeIfMissing(componentIndexFile, componentIndexContent);

function insertMissingLinesAfterMarker(params: {
  filePath: string;
  marker: string;
  lines: string[];
}) {
  const { filePath, marker, lines } = params;

  const originalSource = fs.readFileSync(filePath, 'utf8');
  let source = originalSource;

  if (!source.includes(marker)) {
    console.error(`Marker not found in ${filePath}: ${marker}`);
    process.exit(1);
  }

  const missingLines = lines.filter((line) => !source.includes(line));

  if (missingLines.length === 0) {
    console.log('⏭ Skipped registry imports: already present');
    return;
  }

  source = source.replace(
    new RegExp(
      `\\nimport \\{[^;]*?\\} from '../components/${escapeRegExp(
        componentName
      )}';`,
      'g'
    ),
    ''
  );

  const nextSource = source.replace(
    marker,
    `${marker}\n${missingLines.join('\n')}`
  );

  if (check) {
    if (nextSource !== originalSource) {
      checkFailures.push(path.relative(root, filePath));
    }

    return;
  }

  fs.writeFileSync(filePath, nextSource);

  console.log(`✅ Updated imports: ${path.relative(root, filePath)}`);
}

const requiredDemoFiles = [
  platforms.includes('react')
    ? path.join(componentCatalogDir, `${componentName}Demo.tsx`)
    : null,

  platforms.includes('react-native')
    ? path.join(componentCatalogDir, `Native${componentName}Demo.tsx`)
    : null,
].filter((filePath): filePath is string => Boolean(filePath));

const missingDemoFiles = requiredDemoFiles.filter(
  (filePath) => !fs.existsSync(filePath)
);

if (missingDemoFiles.length > 0) {
  console.log('\n⚠️ Registry update skipped. Missing website demos:');

  for (const filePath of missingDemoFiles) {
    console.log(`   - ${path.relative(root, filePath)}`);
  }
} else {
  const registryImportNames = [
    `${componentName}Accessibility`,
    platforms.includes('react') ? `${componentName}Demo` : null,
    `${componentName}Examples`,
    `${componentName}Usage`,
    platforms.includes('react-native') ? `Native${componentName}Demo` : null,
    `${slug}Api`,
  ].filter((name): name is string => Boolean(name));

  const registryImports = [
    `import {
${registryImportNames.map((name) => `  ${name},`).join('\n')}
} from '../components/${componentName}';`,
  ];
  insertMissingLinesAfterMarker({
    filePath: componentPagesFile,
    marker: '// component-page-imports',
    lines: registryImports,
  });

  insertAfterMarker({
    filePath: componentPagesFile,
    marker: '// component-page-entries',
    content: pageConfigSnippet.trimEnd().replace(/^\n/, ''),
    existsCheck: `${slug}: {`,
  });
}

if (check) {
  if (checkFailures.length > 0) {
    console.error('Generated component page files are out of date:');

    for (const filePath of [...new Set(checkFailures)].sort()) {
      console.error(`  - ${filePath}`);
    }

    process.exit(1);
  }

  console.log(`Generated component page is up to date: ${componentName}`);
  process.exit(0);
}

console.log('Extracted props:', extractedProps);

console.log(`Component: ${componentName}`);
console.log(`Slug: ${slug}`);
console.log(`Platforms: ${platforms.join(', ')}`);
console.log(`Catalog root: ${catalogRoot}`);
