// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { InputPlaygroundValue } from './InputPlayground';

export const inputPlaygroundControls = [
  {
    type: 'text',
    key: 'label',
    label: 'Label',
  },
  {
    type: 'text',
    key: 'description',
    label: 'Description',
  },
  {
    type: 'text',
    key: 'placeholder',
    label: 'Placeholder',
  },
  {
    type: 'select',
    key: 'size',
    label: 'Size',
    options: ['sm', 'md', 'lg'],
  },
  {
    type: 'select',
    key: 'color',
    label: 'Color',
    options: ['primary', 'neutral', 'success', 'warning', 'danger'],
  },
  {
    type: 'select',
    key: 'variant',
    label: 'Variant',
    options: ['outline', 'filled', 'soft'],
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'readOnly',
    label: 'Read Only',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'required',
    label: 'Required',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'invalid',
    label: 'Invalid',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'loading',
    label: 'Loading',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'clearable',
    label: 'Clearable',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'revealPassword',
    label: 'Reveal Password',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'showCounter',
    label: 'Show Counter',
    group: 'Options',
  },
  {
    type: 'text',
    key: 'error',
    label: 'Error',
  },
] as const satisfies readonly PlaygroundControl<InputPlaygroundValue>[];
