// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Input } from '@vellira-ui/react';

import { InputPlayground } from './InputPlayground';

export function InputDemo() {
  return (
    <InputPlayground
      renderInput={(value) => (
        <Input
          label={value.label || undefined}
          description={value.description || undefined}
          placeholder={value.placeholder || undefined}
          size={value.size}
          color={value.color}
          variant={value.variant}
          disabled={value.disabled}
          readOnly={value.readOnly}
          required={value.required}
          invalid={value.invalid}
          loading={value.loading}
          clearable={value.clearable}
          revealPassword={value.revealPassword}
          showCounter={value.showCounter}
          error={value.error || undefined}
        />
      )}
    />
  );
}
