// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialInputPlaygroundValue,
  type InputPlaygroundValue,
} from './InputPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type InputUsageProps = {
  platform: ComponentPlatform;
};

function createInputCode(
  platform: ComponentPlatform,
  value: InputPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] =
    platform === 'react'
      ? ["label='Email'", "description='Used for account notifications.'"]
      : ["label='Email'", "description='Used for account notifications.'"];

  const children = platform === 'react' ? '' : '';

  if (value.label) {
    props.push(`label='${value.label}'`);
  }

  if (value.description) {
    props.push(`description='${value.description}'`);
  }

  if (value.placeholder) {
    props.push(`placeholder='${value.placeholder}'`);
  }

  if (value.size !== 'md') {
    props.push(`size='${value.size}'`);
  }

  if (value.color !== 'primary') {
    props.push(`color='${value.color}'`);
  }

  if (value.variant !== 'outline') {
    props.push(`variant='${value.variant}'`);
  }

  if (value.disabled) {
    props.push('disabled');
  }

  if (value.readOnly) {
    props.push('readOnly');
  }

  if (value.required) {
    props.push('required');
  }

  if (value.invalid) {
    props.push('invalid');
  }

  if (value.loading) {
    props.push('loading');
  }

  if (value.clearable) {
    props.push('clearable');
  }

  if (value.revealPassword) {
    props.push('revealPassword');
  }

  if (value.showCounter) {
    props.push('showCounter');
  }

  if (value.error) {
    props.push(`error='${value.error}'`);
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Input } from '${packageName}';
${platform === 'react' ? '' : ''}

<Input${propsText}/>`;
  }

  return `import { Input } from '${packageName}';
${platform === 'react' ? '' : ''}

<Input${propsText}>
${children}
</Input>`;
}

export function InputUsage({ platform }: InputUsageProps) {
  const [value] = useComponentDemoState<InputPlaygroundValue>(
    initialInputPlaygroundValue
  );

  const code = createInputCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
