// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Radio } from '@vellira-ui/react-native';

import { RadioPlayground } from './RadioPlayground';

export function NativeRadioDemo() {
  return (
    <RadioPlayground
      renderRadio={(value, onChange) => (
        <Radio
          value='option'
          checked={value.checked}
          onCheckedChange={(nextValue) => onChange('checked', nextValue)}
          disabled={value.disabled}
          error={value.error || undefined}
          size={value.size}
          color={value.color}
          label='Email notifications'
          description='Receive updates by email.'
        />
      )}
    />
  );
}
