// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type RadioAccessibilityProps = {
  platform: ComponentPlatform;
};

export function RadioAccessibility({ platform }: RadioAccessibilityProps) {
  const reactItems = [
    {
      title: 'Accessible naming',
      description:
        'Provide a visible label or another accessible name that clearly identifies the control.',
      props: ['label', 'children', 'aria-label'],
    },
    {
      title: 'State communication',
      description:
        'Expose the current interactive state through the appropriate native semantics and keep it synchronized with the visual state.',
      props: ['checked'],
    },
    {
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    },
    {
      title: 'Validation feedback',
      description:
        'Associate validation feedback with the control and expose its invalid state to assistive technologies.',
      props: ['error'],
    },
    {
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    },
    {
      title: 'Keyboard and focus',
      description:
        'Preserve expected keyboard interaction and visible focus behavior.',
      props: ['onKeyDown', 'onFocus', 'onBlur', 'onClick'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Accessible naming',
      description:
        'Provide a visible label or accessibilityLabel so screen readers can identify the control.',
      props: ['label', 'children', 'aria-label', 'accessibilityLabel'],
    },
    {
      title: 'State communication',
      description:
        'Expose the current interactive state through React Native accessibilityState and keep it synchronized with the visual state.',
      props: ['checked'],
    },
    {
      title: 'Disabled state',
      description:
        'Disabled controls should remain identifiable while preventing interaction.',
      props: ['disabled'],
    },
    {
      title: 'Validation feedback',
      description:
        'Expose validation feedback through accessible text or hints and preserve the invalid state for assistive technologies.',
      props: ['error'],
    },
    {
      title: 'Required fields',
      description:
        'Required state should be communicated semantically and not rely only on visual styling.',
      props: ['required'],
    },
    {
      title: 'Keyboard and focus',
      description:
        'Verify focus and screen reader interaction on supported React Native platforms.',
      props: ['onFocus', 'onBlur'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
