// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { RadioPlaygroundValue } from './RadioPlayground';

export const radioPlaygroundControls = [
  {
    type: 'toggle',
    key: 'checked',
    label: 'Checked',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
  {
    type: 'text',
    key: 'error',
    label: 'Error',
  },
  {
    type: 'select',
    key: 'size',
    label: 'Size',
    options: ['sm', 'md', 'lg'],
  },
  {
    type: 'select',
    key: 'color',
    label: 'Color',
    options: ['primary', 'neutral', 'success', 'warning', 'danger'],
  },
] as const satisfies readonly PlaygroundControl<RadioPlaygroundValue>[];
