// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import { Radio as ReactRadio } from '@vellira-ui/react';
import { Radio as NativeRadio } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type RadioExamplesProps = {
  platform: ComponentPlatform;
};

export function RadioExamples({ platform }: RadioExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Standalone radio option.',
      preview: (
        <ReactRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
        />
      ),
      code: "import { Radio } from '@vellira-ui/react';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n/>",
    },
    {
      title: 'Selected',
      description: 'Selected state.',
      preview: (
        <ReactRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          checked
        />
      ),
      code: "import { Radio } from '@vellira-ui/react';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  checked\n/>",
    },
    {
      title: 'Disabled',
      description: 'Disabled state.',
      preview: (
        <ReactRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          disabled
        />
      ),
      code: "import { Radio } from '@vellira-ui/react';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  disabled\n/>",
    },
    {
      title: 'Required',
      description: 'Required form control.',
      preview: (
        <ReactRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          required
        />
      ),
      code: "import { Radio } from '@vellira-ui/react';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  required\n/>",
    },
    {
      title: 'Error',
      description: 'Validation error state.',
      preview: (
        <ReactRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          error='Please choose an option.'
        />
      ),
      code: "import { Radio } from '@vellira-ui/react';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  error='Please choose an option.'\n/>",
    },
    {
      title: 'Size and color',
      description: 'Large semantic radio treatment.',
      preview: (
        <ReactRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          size='lg'
          color='success'
        />
      ),
      code: "import { Radio } from '@vellira-ui/react';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  size='lg'\n  color='success'\n/>",
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Standalone radio option.',
      preview: (
        <NativeRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
        />
      ),
      code: "import { Radio } from '@vellira-ui/react-native';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n/>",
    },
    {
      title: 'Selected',
      description: 'Selected state.',
      preview: (
        <NativeRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          checked
        />
      ),
      code: "import { Radio } from '@vellira-ui/react-native';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  checked\n/>",
    },
    {
      title: 'Disabled',
      description: 'Disabled state.',
      preview: (
        <NativeRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          disabled
        />
      ),
      code: "import { Radio } from '@vellira-ui/react-native';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  disabled\n/>",
    },
    {
      title: 'Required',
      description: 'Required form control.',
      preview: (
        <NativeRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          required
        />
      ),
      code: "import { Radio } from '@vellira-ui/react-native';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  required\n/>",
    },
    {
      title: 'Error',
      description: 'Validation error state.',
      preview: (
        <NativeRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          error='Please choose an option.'
        />
      ),
      code: "import { Radio } from '@vellira-ui/react-native';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  error='Please choose an option.'\n/>",
    },
    {
      title: 'Size and color',
      description: 'Large semantic radio treatment.',
      preview: (
        <NativeRadio
          value='option'
          label='Email notifications'
          description='Receive updates by email.'
          size='lg'
          color='success'
        />
      ),
      code: "import { Radio } from '@vellira-ui/react-native';\n\n<Radio\n  value=\"option\"\n  label='Email notifications'\n  description='Receive updates by email.'\n  size='lg'\n  color='success'\n/>",
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
