// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import { Dropdown as ReactDropdown } from '@vellira-ui/react';
import { Dropdown as NativeDropdown } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type DropdownExamplesProps = {
  platform: ComponentPlatform;
};

export function DropdownExamples({ platform }: DropdownExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Action menu with common items.',
      preview: (
        <ReactDropdown>
          <ReactDropdown.Trigger>Actions</ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item>Profile</ReactDropdown.Item>
            <ReactDropdown.Item>Settings</ReactDropdown.Item>
            <ReactDropdown.Separator />
            <ReactDropdown.Item color='danger'>Sign out</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: "import { Dropdown } from '@vellira-ui/react';\n\n<Dropdown>\n  <Dropdown.Trigger>Actions</Dropdown.Trigger>\n  <Dropdown.Content>\n    <Dropdown.Item>Profile</Dropdown.Item>\n    <Dropdown.Item>Settings</Dropdown.Item>\n    <Dropdown.Separator />\n    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>\n  </Dropdown.Content>\n</Dropdown>",
    },
    {
      title: 'Searchable',
      description: 'Filter menu items.',
      preview: (
        <ReactDropdown searchable>
          <ReactDropdown.Trigger>Actions</ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item>Profile</ReactDropdown.Item>
            <ReactDropdown.Item>Settings</ReactDropdown.Item>
            <ReactDropdown.Separator />
            <ReactDropdown.Item color='danger'>Sign out</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: "import { Dropdown } from '@vellira-ui/react';\n\n<Dropdown\n  searchable\n>\n  <Dropdown.Trigger>Actions</Dropdown.Trigger>\n  <Dropdown.Content>\n    <Dropdown.Item>Profile</Dropdown.Item>\n    <Dropdown.Item>Settings</Dropdown.Item>\n    <Dropdown.Separator />\n    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>\n  </Dropdown.Content>\n</Dropdown>",
    },
    {
      title: 'Loading',
      description: 'Loading menu state.',
      preview: (
        <ReactDropdown loading>
          <ReactDropdown.Trigger>Actions</ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item>Profile</ReactDropdown.Item>
            <ReactDropdown.Item>Settings</ReactDropdown.Item>
            <ReactDropdown.Separator />
            <ReactDropdown.Item color='danger'>Sign out</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: "import { Dropdown } from '@vellira-ui/react';\n\n<Dropdown\n  loading\n>\n  <Dropdown.Trigger>Actions</Dropdown.Trigger>\n  <Dropdown.Content>\n    <Dropdown.Item>Profile</Dropdown.Item>\n    <Dropdown.Item>Settings</Dropdown.Item>\n    <Dropdown.Separator />\n    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>\n  </Dropdown.Content>\n</Dropdown>",
    },
    {
      title: 'Disabled',
      description: 'Disabled trigger state.',
      preview: (
        <ReactDropdown disabled>
          <ReactDropdown.Trigger>Actions</ReactDropdown.Trigger>
          <ReactDropdown.Content>
            <ReactDropdown.Item>Profile</ReactDropdown.Item>
            <ReactDropdown.Item>Settings</ReactDropdown.Item>
            <ReactDropdown.Separator />
            <ReactDropdown.Item color='danger'>Sign out</ReactDropdown.Item>
          </ReactDropdown.Content>
        </ReactDropdown>
      ),
      code: "import { Dropdown } from '@vellira-ui/react';\n\n<Dropdown\n  disabled\n>\n  <Dropdown.Trigger>Actions</Dropdown.Trigger>\n  <Dropdown.Content>\n    <Dropdown.Item>Profile</Dropdown.Item>\n    <Dropdown.Item>Settings</Dropdown.Item>\n    <Dropdown.Separator />\n    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>\n  </Dropdown.Content>\n</Dropdown>",
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Action menu with common items.',
      preview: (
        <NativeDropdown>
          <NativeDropdown.Trigger>Actions</NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Item value='profile'>Profile</NativeDropdown.Item>
            <NativeDropdown.Item value='settings'>Settings</NativeDropdown.Item>
            <NativeDropdown.Separator />
            <NativeDropdown.Item value='sign-out' color='danger'>
              Sign out
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: "import { Dropdown } from '@vellira-ui/react-native';\n\n<Dropdown>\n  <Dropdown.Trigger>Actions</Dropdown.Trigger>\n  <Dropdown.Content>\n    <Dropdown.Item value='profile'>Profile</Dropdown.Item>\n    <Dropdown.Item value='settings'>Settings</Dropdown.Item>\n    <Dropdown.Separator />\n    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>\n  </Dropdown.Content>\n</Dropdown>",
    },
    {
      title: 'Searchable',
      description: 'Filter menu items.',
      preview: (
        <NativeDropdown searchable>
          <NativeDropdown.Trigger>Actions</NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Item value='profile'>Profile</NativeDropdown.Item>
            <NativeDropdown.Item value='settings'>Settings</NativeDropdown.Item>
            <NativeDropdown.Separator />
            <NativeDropdown.Item value='sign-out' color='danger'>
              Sign out
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: "import { Dropdown } from '@vellira-ui/react-native';\n\n<Dropdown\n  searchable\n>\n  <Dropdown.Trigger>Actions</Dropdown.Trigger>\n  <Dropdown.Content>\n    <Dropdown.Item value='profile'>Profile</Dropdown.Item>\n    <Dropdown.Item value='settings'>Settings</Dropdown.Item>\n    <Dropdown.Separator />\n    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>\n  </Dropdown.Content>\n</Dropdown>",
    },
    {
      title: 'Loading',
      description: 'Loading menu state.',
      preview: (
        <NativeDropdown loading>
          <NativeDropdown.Trigger>Actions</NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Item value='profile'>Profile</NativeDropdown.Item>
            <NativeDropdown.Item value='settings'>Settings</NativeDropdown.Item>
            <NativeDropdown.Separator />
            <NativeDropdown.Item value='sign-out' color='danger'>
              Sign out
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: "import { Dropdown } from '@vellira-ui/react-native';\n\n<Dropdown\n  loading\n>\n  <Dropdown.Trigger>Actions</Dropdown.Trigger>\n  <Dropdown.Content>\n    <Dropdown.Item value='profile'>Profile</Dropdown.Item>\n    <Dropdown.Item value='settings'>Settings</Dropdown.Item>\n    <Dropdown.Separator />\n    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>\n  </Dropdown.Content>\n</Dropdown>",
    },
    {
      title: 'Disabled',
      description: 'Disabled trigger state.',
      preview: (
        <NativeDropdown disabled>
          <NativeDropdown.Trigger>Actions</NativeDropdown.Trigger>
          <NativeDropdown.Content>
            <NativeDropdown.Item value='profile'>Profile</NativeDropdown.Item>
            <NativeDropdown.Item value='settings'>Settings</NativeDropdown.Item>
            <NativeDropdown.Separator />
            <NativeDropdown.Item value='sign-out' color='danger'>
              Sign out
            </NativeDropdown.Item>
          </NativeDropdown.Content>
        </NativeDropdown>
      ),
      code: "import { Dropdown } from '@vellira-ui/react-native';\n\n<Dropdown\n  disabled\n>\n  <Dropdown.Trigger>Actions</Dropdown.Trigger>\n  <Dropdown.Content>\n    <Dropdown.Item value='profile'>Profile</Dropdown.Item>\n    <Dropdown.Item value='settings'>Settings</Dropdown.Item>\n    <Dropdown.Separator />\n    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>\n  </Dropdown.Content>\n</Dropdown>",
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
