// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import { Dropdown } from '@vellira-ui/react';

import { DropdownPlayground } from './DropdownPlayground';

export function DropdownDemo() {
  return (
    <DropdownPlayground
      renderDropdown={(value, onChange) => (
        <Dropdown
          open={value.open}
          onOpenChange={(nextValue) => onChange('open', nextValue)}
          size={value.size}
          color={value.color}
          disabled={value.disabled}
          loading={value.loading}
          closeOnSelect={value.closeOnSelect}
          searchable={value.searchable}
          command={value.command}
          searchValue={value.searchValue || undefined}
          searchPlaceholder={value.searchPlaceholder || undefined}
        >
          <Dropdown.Trigger>Actions</Dropdown.Trigger>
          <Dropdown.Content>
            <Dropdown.Item>Profile</Dropdown.Item>
            <Dropdown.Item>Settings</Dropdown.Item>
            <Dropdown.Separator />
            <Dropdown.Item color='danger'>Sign out</Dropdown.Item>
          </Dropdown.Content>
        </Dropdown>
      )}
    />
  );
}
