// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialDropdownPlaygroundValue,
  type DropdownPlaygroundValue,
} from './DropdownPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type DropdownUsageProps = {
  platform: ComponentPlatform;
};

function createDropdownCode(
  platform: ComponentPlatform,
  value: DropdownPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children =
    platform === 'react'
      ? `  <Dropdown.Trigger asChild>
    <ReactButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</ReactButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item>Profile</Dropdown.Item>
    <Dropdown.Item>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>`
      : `  <Dropdown.Trigger asChild>
    <NativeButton appearance='outline' color='neutral' iconEnd={<ChevronDown />}>Actions</NativeButton>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Item value='profile'>Profile</Dropdown.Item>
    <Dropdown.Item value='settings'>Settings</Dropdown.Item>
    <Dropdown.Separator />
    <Dropdown.Item value='sign-out' color='danger'>Sign out</Dropdown.Item>
  </Dropdown.Content>`;

  if (value.open) {
    props.push('open');
  }

  if (value.size !== 'md') {
    props.push(`size='${value.size}'`);
  }

  if (value.color !== 'primary') {
    props.push(`color='${value.color}'`);
  }

  if (value.disabled) {
    props.push('disabled');
  }

  if (value.loading) {
    props.push('loading');
  }

  if (value.closeOnSelect) {
    props.push('closeOnSelect');
  }

  if (value.searchable) {
    props.push('searchable');
  }

  if (value.command) {
    props.push('command');
  }

  if (value.searchValue) {
    props.push(`searchValue='${value.searchValue}'`);
  }

  if (value.searchPlaceholder) {
    props.push(`searchPlaceholder='${value.searchPlaceholder}'`);
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Dropdown } from '${packageName}';
${
  platform === 'react'
    ? `
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';`
    : `
import { ChevronDown } from '@vellira-ui/icons';
import { Button as NativeButton } from '@vellira-ui/react-native';`
}

<Dropdown${propsText}/>`;
  }

  return `import { Dropdown } from '${packageName}';
${
  platform === 'react'
    ? `
import { ChevronDown } from '@vellira-ui/icons';
import { Button as ReactButton } from '@vellira-ui/react';`
    : `
import { ChevronDown } from '@vellira-ui/icons';
import { Button as NativeButton } from '@vellira-ui/react-native';`
}

<Dropdown${propsText}>
${children}
</Dropdown>`;
}

export function DropdownUsage({ platform }: DropdownUsageProps) {
  const [value] = useComponentDemoState<DropdownPlaygroundValue>(
    initialDropdownPlaygroundValue
  );

  const code = createDropdownCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
