// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { dropdownPlaygroundControls } from './dropdownPlaygroundSchema';

export type DropdownPlaygroundValue = {
  open: boolean;
  size: 'sm' | 'md' | 'lg';
  color: 'primary' | 'neutral' | 'success' | 'warning' | 'danger';
  disabled: boolean;
  loading: boolean;
  closeOnSelect: boolean;
  searchable: boolean;
  command: boolean;
  searchValue: string;
  searchPlaceholder: string;
};

type DropdownPlaygroundProps = {
  renderDropdown: (
    value: DropdownPlaygroundValue,
    onChange: <K extends keyof DropdownPlaygroundValue>(
      key: K,
      nextValue: DropdownPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialDropdownPlaygroundValue: DropdownPlaygroundValue = {
  open: false,
  size: 'md',
  color: 'primary',
  disabled: false,
  loading: false,
  closeOnSelect: false,
  searchable: false,
  command: false,
  searchValue: '',
  searchPlaceholder: '',
};

export function DropdownPlayground({
  renderDropdown,
}: DropdownPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<DropdownPlaygroundValue>(
    initialDropdownPlaygroundValue
  );

  const update = (
    key: keyof DropdownPlaygroundValue,
    nextValue: DropdownPlaygroundValue[keyof DropdownPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='auto'
      controls={
        <PlaygroundControlsFromSchema
          value={value}
          controls={dropdownPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderDropdown(value, update)}
    </ComponentPlayground>
  );
}
