// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { DropdownPlaygroundValue } from './DropdownPlayground';

export const dropdownPlaygroundControls = [
  {
    type: 'toggle',
    key: 'open',
    label: 'Open',
    group: 'Options',
  },
  {
    type: 'select',
    key: 'size',
    label: 'Size',
    options: ['sm', 'md', 'lg'],
  },
  {
    type: 'select',
    key: 'color',
    label: 'Color',
    options: ['primary', 'neutral', 'success', 'warning', 'danger'],
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'loading',
    label: 'Loading',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'closeOnSelect',
    label: 'Close On Select',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'searchable',
    label: 'Searchable',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'command',
    label: 'Command',
    group: 'Options',
  },
  {
    type: 'text',
    key: 'searchValue',
    label: 'Search Value',
  },
  {
    type: 'text',
    key: 'searchPlaceholder',
    label: 'Search Placeholder',
  },
] as const satisfies readonly PlaygroundControl<DropdownPlaygroundValue>[];
