// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { useWindowDimensions } from 'react-native';
import { Dropdown } from '@vellira-ui/react-native';

import { DropdownPlayground } from './DropdownPlayground';

export function NativeDropdownDemo() {
  const { width } = useWindowDimensions();
  const presentation = width <= 890 ? 'sheet' : 'popover';

  return (
    <DropdownPlayground
      renderDropdown={(value, onChange) => (
        <Dropdown
          presentation={presentation}
          open={value.open}
          onOpenChange={(nextValue) => onChange('open', nextValue)}
          size={value.size}
          color={value.color}
          disabled={value.disabled}
          loading={value.loading}
          closeOnSelect={value.closeOnSelect}
          searchable={value.searchable}
          command={value.command}
          searchValue={value.searchValue || undefined}
          searchPlaceholder={value.searchPlaceholder || undefined}
        >
          <Dropdown.Trigger>Actions</Dropdown.Trigger>
          <Dropdown.Content>
            <Dropdown.Item value='profile'>Profile</Dropdown.Item>
            <Dropdown.Item value='settings'>Settings</Dropdown.Item>
            <Dropdown.Separator />
            <Dropdown.Item value='sign-out' color='danger'>
              Sign out
            </Dropdown.Item>
          </Dropdown.Content>
        </Dropdown>
      )}
    />
  );
}
