// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { CheckboxPlaygroundValue } from './CheckboxPlayground';

export const checkboxPlaygroundControls = [
  {
    type: 'toggle',
    key: 'checked',
    label: 'Checked',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'required',
    label: 'Required',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'indeterminate',
    label: 'Indeterminate',
    group: 'Options',
  },
  {
    type: 'text',
    key: 'error',
    label: 'Error',
  },
  {
    type: 'select',
    key: 'size',
    label: 'Size',
    options: ['sm', 'md', 'lg'],
  },
  {
    type: 'select',
    key: 'color',
    label: 'Color',
    options: ['primary', 'neutral', 'success', 'warning', 'danger'],
  },
  {
    type: 'select',
    key: 'labelPosition',
    label: 'Label Position',
    options: ['start', 'end'],
  },
] as const satisfies readonly PlaygroundControl<CheckboxPlaygroundValue>[];
