// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { checkboxPlaygroundControls } from './checkboxPlaygroundSchema';

export type CheckboxPlaygroundValue = {
  checked: boolean;
  disabled: boolean;
  required: boolean;
  indeterminate: boolean;
  error: string;
  size: 'sm' | 'md' | 'lg';
  color: 'primary' | 'neutral' | 'success' | 'warning' | 'danger';
  labelPosition: 'start' | 'end';
};

type CheckboxPlaygroundProps = {
  renderCheckbox: (
    value: CheckboxPlaygroundValue,
    onChange: <K extends keyof CheckboxPlaygroundValue>(
      key: K,
      nextValue: CheckboxPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialCheckboxPlaygroundValue: CheckboxPlaygroundValue = {
  checked: false,
  disabled: false,
  required: false,
  indeterminate: false,
  error: '',
  size: 'md',
  color: 'primary',
  labelPosition: 'end',
};

export function CheckboxPlayground({
  renderCheckbox,
}: CheckboxPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<CheckboxPlaygroundValue>(
    initialCheckboxPlaygroundValue
  );

  const update = (
    key: keyof CheckboxPlaygroundValue,
    nextValue: CheckboxPlaygroundValue[keyof CheckboxPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='field'
      controls={
        <PlaygroundControlsFromSchema
          value={value}
          controls={checkboxPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderCheckbox(value, update)}
    </ComponentPlayground>
  );
}
