// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialCheckboxPlaygroundValue,
  type CheckboxPlaygroundValue,
} from './CheckboxPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type CheckboxUsageProps = {
  platform: ComponentPlatform;
};

function createCheckboxCode(
  platform: ComponentPlatform,
  value: CheckboxPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] =
    platform === 'react' ? [`label='Accept terms'`] : [`label='Accept terms'`];

  const children = platform === 'react' ? `` : ``;

  if (value.checked) {
    props.push('checked');
  }

  if (value.disabled) {
    props.push('disabled');
  }

  if (value.required) {
    props.push('required');
  }

  if (value.indeterminate) {
    props.push('indeterminate');
  }

  if (value.error) {
    props.push(`error='${value.error}'`);
  }

  if (value.size !== 'md') {
    props.push(`size='${value.size}'`);
  }

  if (value.color !== 'primary') {
    props.push(`color='${value.color}'`);
  }

  if (value.labelPosition !== 'end') {
    props.push(`labelPosition='${value.labelPosition}'`);
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Checkbox } from '${packageName}';
${platform === 'react' ? `` : ``}

<Checkbox${propsText}/>`;
  }

  return `import { Checkbox } from '${packageName}';
${platform === 'react' ? `` : ``}

<Checkbox${propsText}>
${children}
</Checkbox>`;
}

export function CheckboxUsage({ platform }: CheckboxUsageProps) {
  const [value] = useComponentDemoState<CheckboxPlaygroundValue>(
    initialCheckboxPlaygroundValue
  );

  const code = createCheckboxCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
