// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import { Checkbox as ReactCheckbox } from '@vellira-ui/react';
import { Checkbox as NativeCheckbox } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type CheckboxExamplesProps = {
  platform: ComponentPlatform;
};

export function CheckboxExamples({ platform }: CheckboxExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Binary selection control.',
      preview: (
        <ReactCheckbox
          label='Accept terms'
          description='Required before continuing.'
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n/>",
    },
    {
      title: 'Checked',
      description: 'Selected state.',
      preview: (
        <ReactCheckbox
          label='Accept terms'
          description='Required before continuing.'
          checked
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n  checked\n/>",
    },
    {
      title: 'Indeterminate',
      description: 'Mixed state for partial selections.',
      preview: (
        <ReactCheckbox
          label='Accept terms'
          description='Required before continuing.'
          indeterminate
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n  indeterminate\n/>",
    },
    {
      title: 'Disabled',
      description: 'Disabled state.',
      preview: (
        <ReactCheckbox
          label='Accept terms'
          description='Required before continuing.'
          disabled
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n  disabled\n/>",
    },
    {
      title: 'Error',
      description: 'Validation feedback state.',
      preview: (
        <ReactCheckbox
          label='Accept terms'
          description='Required before continuing.'
          error='Accept the terms to continue.'
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n  error='Accept the terms to continue.'\n/>",
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Binary selection control.',
      preview: (
        <NativeCheckbox
          label='Accept terms'
          description='Required before continuing.'
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react-native';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n/>",
    },
    {
      title: 'Checked',
      description: 'Selected state.',
      preview: (
        <NativeCheckbox
          label='Accept terms'
          description='Required before continuing.'
          checked
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react-native';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n  checked\n/>",
    },
    {
      title: 'Indeterminate',
      description: 'Mixed state for partial selections.',
      preview: (
        <NativeCheckbox
          label='Accept terms'
          description='Required before continuing.'
          indeterminate
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react-native';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n  indeterminate\n/>",
    },
    {
      title: 'Disabled',
      description: 'Disabled state.',
      preview: (
        <NativeCheckbox
          label='Accept terms'
          description='Required before continuing.'
          disabled
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react-native';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n  disabled\n/>",
    },
    {
      title: 'Error',
      description: 'Validation feedback state.',
      preview: (
        <NativeCheckbox
          label='Accept terms'
          description='Required before continuing.'
          error='Accept the terms to continue.'
        />
      ),
      code: "import { Checkbox } from '@vellira-ui/react-native';\n\n<Checkbox\n  label='Accept terms'\n  description='Required before continuing.'\n  error='Accept the terms to continue.'\n/>",
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
