// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialTabsPlaygroundValue,
  type TabsPlaygroundValue,
} from './TabsPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type TabsUsageProps = {
  platform: ComponentPlatform;
};

function createTabsCode(
  platform: ComponentPlatform,
  value: TabsPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children =
    platform === 'react'
      ? `  <Tabs.List>
    <Tabs.Trigger value='account'>Account</Tabs.Trigger>
    <Tabs.Trigger value='billing'>Billing</Tabs.Trigger>
    <Tabs.Indicator />
  </Tabs.List>
  <Tabs.Content value='account'>Account settings</Tabs.Content>
  <Tabs.Content value='billing'>Billing details</Tabs.Content>`
      : `  <Tabs.List>
    <Tabs.Trigger value='account'>Account</Tabs.Trigger>
    <Tabs.Trigger value='billing'>Billing</Tabs.Trigger>
    <Tabs.Indicator />
  </Tabs.List>
  <Tabs.Content value='account'><NativeText>Account settings</NativeText></Tabs.Content>
  <Tabs.Content value='billing'><NativeText>Billing details</NativeText></Tabs.Content>`;

  if (value.value) {
    props.push(`value='${value.value}'`);
  }

  if (value.orientation !== 'horizontal') {
    props.push(`orientation='${value.orientation}'`);
  }

  if (value.activationMode !== 'automatic') {
    props.push(`activationMode='${value.activationMode}'`);
  }

  if (value.dir !== 'ltr') {
    props.push(`dir='${value.dir}'`);
  }

  if (value.loop) {
    props.push('loop');
  }

  if (value.keepMounted) {
    props.push('keepMounted');
  }

  if (value.lazyMount) {
    props.push('lazyMount');
  }

  if (value.variant !== 'line') {
    props.push(`variant='${value.variant}'`);
  }

  if (value.color !== 'primary') {
    props.push(`color='${value.color}'`);
  }

  if (value.size !== 'md') {
    props.push(`size='${value.size}'`);
  }

  if (value.mode !== 'tabs') {
    props.push(`mode='${value.mode}'`);
  }

  if (value.disabled) {
    props.push('disabled');
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Tabs } from '${packageName}';
${
  platform === 'react'
    ? ``
    : `
import { Text as NativeText } from 'react-native';`
}

<Tabs${propsText}/>`;
  }

  return `import { Tabs } from '${packageName}';
${
  platform === 'react'
    ? ``
    : `
import { Text as NativeText } from 'react-native';`
}

<Tabs${propsText}>
${children}
</Tabs>`;
}

export function TabsUsage({ platform }: TabsUsageProps) {
  const [value] = useComponentDemoState<TabsPlaygroundValue>(
    initialTabsPlaygroundValue
  );

  const code = createTabsCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
