// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type TabsAccessibilityProps = {
  platform: ComponentPlatform;
};

export function TabsAccessibility({ platform }: TabsAccessibilityProps) {
  const reactItems = [
    {
      title: 'Keyboard navigation',
      description:
        'Support arrow-key movement between triggers and preserve focus order.',
      props: ['orientation', 'activationMode', 'loop'],
    },
    {
      title: 'Panel relationships',
      description:
        'Each trigger value should match exactly one content panel value.',
      props: ['value', 'defaultValue'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Screen reader state',
      description:
        'Expose the selected tab and associated panel content through React Native accessibility state.',
      props: ['value', 'defaultValue'],
    },
    {
      title: 'Orientation',
      description:
        'Use an orientation that keeps tab navigation clear and predictable for the available space.',
      props: ['orientation'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
