// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Tabs } from '@vellira-ui/react';

import { TabsPlayground } from './TabsPlayground';

export function TabsDemo() {
  return (
    <TabsPlayground
      renderTabs={(value, onChange) => (
        <Tabs
          value={value.value || undefined}
          onValueChange={(nextValue) => onChange('value', nextValue)}
          orientation={value.orientation}
          activationMode={value.activationMode}
          dir={value.dir}
          loop={value.loop}
          keepMounted={value.keepMounted}
          lazyMount={value.lazyMount}
          variant={value.variant}
          color={value.color}
          size={value.size}
          disabled={value.disabled}
        >
          <Tabs.List>
            <Tabs.Trigger value='account'>Account</Tabs.Trigger>
            <Tabs.Trigger value='billing'>Billing</Tabs.Trigger>
          </Tabs.List>
          <Tabs.Content value='account'>Account settings</Tabs.Content>
          <Tabs.Content value='billing'>Billing details</Tabs.Content>
        </Tabs>
      )}
    />
  );
}
