// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { ButtonPlaygroundValue } from './ButtonPlayground';

export const buttonPlaygroundControls = [
  {
    type: 'select',
    key: 'color',
    label: 'Color',
    options: ['primary', 'neutral', 'success', 'warning', 'danger'],
  },
  {
    type: 'select',
    key: 'appearance',
    label: 'Appearance',
    options: ['solid', 'outline', 'ghost', 'soft', 'link'],
  },
  {
    type: 'select',
    key: 'size',
    label: 'Size',
    options: ['sm', 'md', 'lg'],
  },
  {
    type: 'select',
    key: 'shape',
    label: 'Shape',
    options: ['square', 'rounded', 'pill'],
  },
  {
    type: 'toggle',
    key: 'fullWidth',
    label: 'Full Width',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'loading',
    label: 'Loading',
    group: 'Options',
  },
  {
    type: 'text',
    key: 'loadingText',
    label: 'Loading Text',
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'iconOnly',
    label: 'Icon Only',
    group: 'Options',
  },
] as const satisfies readonly PlaygroundControl<ButtonPlaygroundValue>[];
