// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { buttonPlaygroundControls } from './buttonPlaygroundSchema';

export type ButtonPlaygroundValue = {
  color: 'primary' | 'neutral' | 'success' | 'warning' | 'danger';
  appearance: 'solid' | 'outline' | 'ghost' | 'soft' | 'link';
  size: 'sm' | 'md' | 'lg';
  shape: 'square' | 'rounded' | 'pill';
  fullWidth: boolean;
  loading: boolean;
  loadingText: string;
  disabled: boolean;
  iconOnly: boolean;
};

type ButtonPlaygroundProps = {
  renderButton: (
    value: ButtonPlaygroundValue,
    onChange: <K extends keyof ButtonPlaygroundValue>(
      key: K,
      nextValue: ButtonPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialButtonPlaygroundValue: ButtonPlaygroundValue = {
  color: 'primary',
  appearance: 'solid',
  size: 'md',
  shape: 'pill',
  fullWidth: false,
  loading: false,
  loadingText: '',
  disabled: false,
  iconOnly: false,
};

export function ButtonPlayground({ renderButton }: ButtonPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<ButtonPlaygroundValue>(
    initialButtonPlaygroundValue
  );

  const update = (
    key: keyof ButtonPlaygroundValue,
    nextValue: ButtonPlaygroundValue[keyof ButtonPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='auto'
      controls={
        <PlaygroundControlsFromSchema
          value={value}
          controls={buttonPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderButton(value, update)}
    </ComponentPlayground>
  );
}
