// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Button as ReactButton } from '@vellira-ui/react';
import { Button as NativeButton } from '@vellira-ui/react-native';
import { ArrowRight, Download } from '@vellira-ui/icons';
import { Plus } from '@vellira-ui/icons';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type ButtonExamplesProps = {
  platform: ComponentPlatform;
};

export function ButtonExamples({ platform }: ButtonExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Primary action button.',
      preview: <ReactButton>Button</ReactButton>,
      code: "import { Button } from '@vellira-ui/react';\n\n<Button>\n  Button\n</Button>",
    },
    {
      title: 'Appearance and color',
      description: 'Alternative surface and semantic action tone.',
      preview: (
        <ReactButton appearance='outline' color='danger'>
          Button
        </ReactButton>
      ),
      code: "import { Button } from '@vellira-ui/react';\n\n<Button\n  appearance='outline'\n  color='danger'\n>\n  Button\n</Button>",
    },
    {
      title: 'Icons',
      description: 'Icons clarify the action without replacing the label.',
      preview: (
        <ReactButton iconStart={<Download />} iconEnd={<ArrowRight />}>
          Button
        </ReactButton>
      ),
      code: "import { Button } from '@vellira-ui/react';\nimport { ArrowRight, Download } from '@vellira-ui/icons';\n\n<Button\n  iconStart={<Download />}\n  iconEnd={<ArrowRight />}\n>\n  Button\n</Button>",
    },
    {
      title: 'Icon-only',
      description: 'Compact action with an accessible name.',
      preview: (
        <ReactButton iconOnly iconStart={<Plus />} aria-label='Add item' />
      ),
      code: "import { Button } from '@vellira-ui/react';\nimport { Plus } from '@vellira-ui/icons';\n\n<Button\n  iconOnly\n  iconStart={<Plus />}\n  aria-label='Add item'\n/>",
    },
    {
      title: 'Loading',
      description: 'Shows progress and prevents interaction.',
      preview: (
        <ReactButton loading loadingText='Saving...'>
          Button
        </ReactButton>
      ),
      code: "import { Button } from '@vellira-ui/react';\n\n<Button\n  loading\n  loadingText='Saving...'\n>\n  Button\n</Button>",
    },
    {
      title: 'Disabled',
      description: 'Disabled action state.',
      preview: <ReactButton disabled>Button</ReactButton>,
      code: "import { Button } from '@vellira-ui/react';\n\n<Button\n  disabled\n>\n  Button\n</Button>",
    },
    {
      title: 'Full width',
      description: 'Button expands to fill its container.',
      preview: <ReactButton fullWidth>Button</ReactButton>,
      code: "import { Button } from '@vellira-ui/react';\n\n<Button\n  fullWidth\n>\n  Button\n</Button>",
    },
    {
      title: 'Size and shape',
      description: 'Large rounded button treatment.',
      preview: (
        <ReactButton size='lg' shape='rounded'>
          Button
        </ReactButton>
      ),
      code: "import { Button } from '@vellira-ui/react';\n\n<Button\n  size='lg'\n  shape='rounded'\n>\n  Button\n</Button>",
    },
    {
      title: 'Composed link',
      description: 'Composes button styling onto a custom React link.',
      preview: (
        <ReactButton asChild>
          <a href='/components/button'>Button</a>
        </ReactButton>
      ),
      code: "import { Button } from '@vellira-ui/react';\n\n<Button\n  asChild\n>\n  <a href='/components/button'>Button</a>\n</Button>",
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Primary action button.',
      preview: <NativeButton>Button</NativeButton>,
      code: "import { Button } from '@vellira-ui/react-native';\n\n<Button>\n  Button\n</Button>",
    },
    {
      title: 'Appearance and color',
      description: 'Alternative surface and semantic action tone.',
      preview: (
        <NativeButton appearance='outline' color='danger'>
          Button
        </NativeButton>
      ),
      code: "import { Button } from '@vellira-ui/react-native';\n\n<Button\n  appearance='outline'\n  color='danger'\n>\n  Button\n</Button>",
    },
    {
      title: 'Icons',
      description: 'Icons clarify the action without replacing the label.',
      preview: (
        <NativeButton iconStart={<Download />} iconEnd={<ArrowRight />}>
          Button
        </NativeButton>
      ),
      code: "import { Button } from '@vellira-ui/react-native';\nimport { ArrowRight, Download } from '@vellira-ui/icons';\n\n<Button\n  iconStart={<Download />}\n  iconEnd={<ArrowRight />}\n>\n  Button\n</Button>",
    },
    {
      title: 'Icon-only',
      description: 'Compact action with an accessible name.',
      preview: (
        <NativeButton
          iconOnly
          iconStart={<Plus />}
          accessibilityLabel='Add item'
        />
      ),
      code: "import { Button } from '@vellira-ui/react-native';\nimport { Plus } from '@vellira-ui/icons';\n\n<Button\n  iconOnly\n  iconStart={<Plus />}\n  accessibilityLabel='Add item'\n/>",
    },
    {
      title: 'Loading',
      description: 'Shows progress and prevents interaction.',
      preview: (
        <NativeButton loading loadingText='Saving...'>
          Button
        </NativeButton>
      ),
      code: "import { Button } from '@vellira-ui/react-native';\n\n<Button\n  loading\n  loadingText='Saving...'\n>\n  Button\n</Button>",
    },
    {
      title: 'Disabled',
      description: 'Disabled action state.',
      preview: <NativeButton disabled>Button</NativeButton>,
      code: "import { Button } from '@vellira-ui/react-native';\n\n<Button\n  disabled\n>\n  Button\n</Button>",
    },
    {
      title: 'Full width',
      description: 'Button expands to fill its container.',
      preview: <NativeButton fullWidth>Button</NativeButton>,
      code: "import { Button } from '@vellira-ui/react-native';\n\n<Button\n  fullWidth\n>\n  Button\n</Button>",
    },
    {
      title: 'Size and shape',
      description: 'Large rounded button treatment.',
      preview: (
        <NativeButton size='lg' shape='rounded'>
          Button
        </NativeButton>
      ),
      code: "import { Button } from '@vellira-ui/react-native';\n\n<Button\n  size='lg'\n  shape='rounded'\n>\n  Button\n</Button>",
    },
    {
      title: 'Press handler',
      description: 'Handles native press interaction.',
      preview: <NativeButton onPress={() => {}}>Button</NativeButton>,
      code: "import { Button } from '@vellira-ui/react-native';\n\n<Button\n  onPress={() => {}}\n>\n  Button\n</Button>",
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
