// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type ButtonAccessibilityProps = {
  platform: ComponentPlatform;
};

export function ButtonAccessibility({ platform }: ButtonAccessibilityProps) {
  const reactItems = [
    {
      title: 'Accessible names',
      description:
        'Use visible text for normal buttons and aria-label or aria-labelledby for icon-only actions.',
      props: ['children', 'iconOnly', 'aria-label', 'aria-labelledby'],
    },
    {
      title: 'Loading and disabled state',
      description:
        'Loading buttons expose busy state and prevent interaction while preserving the button label.',
      props: ['loading', 'loadingText', 'disabled'],
    },
    {
      title: 'Composed semantics',
      description:
        'When using asChild, pass semantic attributes and href to the child element.',
      props: ['asChild', 'href', 'type'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Accessible names',
      description:
        'Use visible text for normal buttons and accessibilityLabel for icon-only actions.',
      props: ['children', 'iconOnly', 'accessibilityLabel'],
    },
    {
      title: 'Loading and disabled state',
      description:
        'Loading buttons announce disabled interaction through React Native accessibility state.',
      props: ['loading', 'loadingText', 'disabled'],
    },
    {
      title: 'Press handling',
      description:
        'Keep onPress actions predictable and provide an accessibilityHint when the result is not obvious.',
      props: ['onPress', 'accessibilityHint'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
