// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Button } from '@vellira-ui/react-native';
import { Plus } from '@vellira-ui/icons';

import { ButtonPlayground } from './ButtonPlayground';

export function NativeButtonDemo() {
  return (
    <ButtonPlayground
      platform='react-native'
      renderButton={(value) => (
        <Button
          iconStart={<Plus />}
          accessibilityLabel='Add item'
          color={value.color}
          appearance={value.appearance}
          size={value.size}
          shape={value.shape}
          fullWidth={value.fullWidth}
          loading={value.loading}
          loadingText={value.loadingText || undefined}
          disabled={value.disabled}
          iconOnly={value.iconOnly}
        >
          Add item
        </Button>
      )}
    />
  );
}
