// Generated by scripts/generators/create-component-page.ts.
// Do not edit manually.

'use client';

import { Popover } from '@vellira-ui/react-native';
import { Button as NativeButton } from '@vellira-ui/react-native';

import { PopoverPlayground } from './PopoverPlayground';

export function NativePopoverDemo() {
  return (
    <PopoverPlayground
      renderPopover={(value, onChange) => (
        <Popover
          open={value.open}
          onOpenChange={(nextValue) => onChange('open', nextValue)}
          modal={value.modal}
        >
          <Popover.Trigger asChild>
            <NativeButton>Open popover</NativeButton>
          </Popover.Trigger>
          <Popover.Content>
            <Popover.Title>Details</Popover.Title>
            <Popover.Description>
              Contextual information for this control.
            </Popover.Description>
          </Popover.Content>
        </Popover>
      )}
    />
  );
}
