// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Popover as ReactPopover } from '@vellira-ui/react';
import { Popover as NativePopover } from '@vellira-ui/react-native';
import { Button as ReactButton } from '@vellira-ui/react';
import { Button as NativeButton } from '@vellira-ui/react-native';
import { Text as NativeText, View as NativeView } from 'react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type PopoverExamplesProps = {
  platform: ComponentPlatform;
};

export function PopoverExamples({ platform }: PopoverExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Floating contextual content.',
      preview: (
        <ReactPopover>
          <ReactPopover.Trigger asChild>
            <ReactButton>Open popover</ReactButton>
          </ReactPopover.Trigger>
          <ReactPopover.Content>
            <ReactPopover.Arrow />
            <ReactPopover.Title>Details</ReactPopover.Title>
            <ReactPopover.Description>
              Contextual information for this control.
            </ReactPopover.Description>
          </ReactPopover.Content>
        </ReactPopover>
      ),
      code: `import { Popover } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Popover>
  <Popover.Trigger asChild>
    <ReactButton>Open popover</ReactButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Placement',
      description: 'Positions content relative to the trigger.',
      preview: (
        <ReactPopover side='top' align='start' sideOffset={12}>
          <ReactPopover.Trigger asChild>
            <ReactButton>Open popover</ReactButton>
          </ReactPopover.Trigger>
          <ReactPopover.Content>
            <ReactPopover.Arrow />
            <ReactPopover.Title>Details</ReactPopover.Title>
            <ReactPopover.Description>
              Contextual information for this control.
            </ReactPopover.Description>
          </ReactPopover.Content>
        </ReactPopover>
      ),
      code: `import { Popover } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Popover
  side='top'
  align='start'
  sideOffset={12}
>
  <Popover.Trigger asChild>
    <ReactButton>Open popover</ReactButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Open change handler',
      description: 'Observes popover visibility from application state.',
      preview: (
        <ReactPopover onOpenChange={() => {}}>
          <ReactPopover.Trigger asChild>
            <ReactButton>Open popover</ReactButton>
          </ReactPopover.Trigger>
          <ReactPopover.Content>
            <ReactPopover.Arrow />
            <ReactPopover.Title>Details</ReactPopover.Title>
            <ReactPopover.Description>
              Contextual information for this control.
            </ReactPopover.Description>
          </ReactPopover.Content>
        </ReactPopover>
      ),
      code: `import { Popover } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Popover
  onOpenChange={() => {}}
>
  <Popover.Trigger asChild>
    <ReactButton>Open popover</ReactButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Modal',
      description: 'Modal interaction semantics.',
      preview: (
        <ReactPopover modal>
          <ReactPopover.Trigger asChild>
            <ReactButton>Open popover</ReactButton>
          </ReactPopover.Trigger>
          <ReactPopover.Content>
            <ReactPopover.Arrow />
            <ReactPopover.Title>Details</ReactPopover.Title>
            <ReactPopover.Description>
              Contextual information for this control.
            </ReactPopover.Description>
          </ReactPopover.Content>
        </ReactPopover>
      ),
      code: `import { Popover } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Popover
  modal
>
  <Popover.Trigger asChild>
    <ReactButton>Open popover</ReactButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Arrow and close action',
      description:
        'Adds an arrow and an explicit close control inside the popover.',
      preview: (
        <ReactPopover>
          <ReactPopover.Trigger asChild>
            <ReactButton>Open popover</ReactButton>
          </ReactPopover.Trigger>
          <ReactPopover.Content>
            <ReactPopover.Arrow />
            <ReactPopover.Title>Details</ReactPopover.Title>
            <ReactPopover.Description>
              Contextual information for this control.
            </ReactPopover.Description>
            <ReactPopover.Close asChild>
              <ReactButton appearance='outline'>Close</ReactButton>
            </ReactPopover.Close>
          </ReactPopover.Content>
        </ReactPopover>
      ),
      code: `import { Popover } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Popover>
  <Popover.Trigger asChild>
    <ReactButton>Open popover</ReactButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
    <Popover.Close asChild>
      <ReactButton appearance='outline'>Close</ReactButton>
    </Popover.Close>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Separate anchor',
      description:
        'Positions content from an anchor while using a separate trigger.',
      preview: (
        <ReactPopover>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 16,
            }}
          >
            <ReactPopover.Anchor asChild>
              <div
                style={{
                  padding: 16,
                  border: '1px dashed var(--border-muted)',
                  borderRadius: 'var(--radius-lg)',
                }}
              >
                Position relative to me
              </div>
            </ReactPopover.Anchor>

            <ReactPopover.Trigger asChild>
              <ReactButton>Toggle popover</ReactButton>
            </ReactPopover.Trigger>
          </div>

          <ReactPopover.Content>
            <ReactPopover.Arrow />
            <ReactPopover.Title>Separate anchor</ReactPopover.Title>
            <ReactPopover.Description>
              The trigger controls the state, but the content is positioned
              relative to the anchor.
            </ReactPopover.Description>

            <ReactPopover.Close asChild>
              <ReactButton size='sm' appearance='ghost'>
                Close
              </ReactButton>
            </ReactPopover.Close>
          </ReactPopover.Content>
        </ReactPopover>
      ),
      code: `import { Popover } from '@vellira-ui/react';
import { Button as ReactButton } from '@vellira-ui/react';

<Popover>
  <div
    style={{
      display: 'flex',
      alignItems: 'center',
      gap: 16,
    }}
  >
    <Popover.Anchor asChild>
      <div
        style={{
          padding: 16,
          border: '1px dashed var(--border-muted)',
          borderRadius: 'var(--radius-lg)',
        }}
      >
        Position relative to me
      </div>
    </Popover.Anchor>
  
    <Popover.Trigger asChild>
      <ReactButton>Toggle popover</ReactButton>
    </Popover.Trigger>
  </div>
  
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Separate anchor</Popover.Title>
    <Popover.Description>
      The trigger controls the state, but the content is positioned relative to the anchor.
    </Popover.Description>
  
    <Popover.Close asChild>
      <ReactButton size='sm' appearance='ghost'>
        Close
      </ReactButton>
    </Popover.Close>
  </Popover.Content>
</Popover>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Floating contextual content.',
      preview: (
        <NativePopover>
          <NativePopover.Trigger asChild>
            <NativeButton>Open popover</NativeButton>
          </NativePopover.Trigger>
          <NativePopover.Content>
            <NativePopover.Arrow />
            <NativePopover.Title>Details</NativePopover.Title>
            <NativePopover.Description>
              Contextual information for this control.
            </NativePopover.Description>
          </NativePopover.Content>
        </NativePopover>
      ),
      code: `import { Popover } from '@vellira-ui/react-native';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Popover>
  <Popover.Trigger asChild>
    <NativeButton>Open popover</NativeButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Placement',
      description: 'Positions content relative to the trigger.',
      preview: (
        <NativePopover side='top' align='start' sideOffset={12}>
          <NativePopover.Trigger asChild>
            <NativeButton>Open popover</NativeButton>
          </NativePopover.Trigger>
          <NativePopover.Content>
            <NativePopover.Arrow />
            <NativePopover.Title>Details</NativePopover.Title>
            <NativePopover.Description>
              Contextual information for this control.
            </NativePopover.Description>
          </NativePopover.Content>
        </NativePopover>
      ),
      code: `import { Popover } from '@vellira-ui/react-native';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Popover
  side='top'
  align='start'
  sideOffset={12}
>
  <Popover.Trigger asChild>
    <NativeButton>Open popover</NativeButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Open change handler',
      description: 'Observes popover visibility from application state.',
      preview: (
        <NativePopover onOpenChange={() => {}}>
          <NativePopover.Trigger asChild>
            <NativeButton>Open popover</NativeButton>
          </NativePopover.Trigger>
          <NativePopover.Content>
            <NativePopover.Arrow />
            <NativePopover.Title>Details</NativePopover.Title>
            <NativePopover.Description>
              Contextual information for this control.
            </NativePopover.Description>
          </NativePopover.Content>
        </NativePopover>
      ),
      code: `import { Popover } from '@vellira-ui/react-native';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Popover
  onOpenChange={() => {}}
>
  <Popover.Trigger asChild>
    <NativeButton>Open popover</NativeButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Modal',
      description: 'Modal interaction semantics.',
      preview: (
        <NativePopover modal>
          <NativePopover.Trigger asChild>
            <NativeButton>Open popover</NativeButton>
          </NativePopover.Trigger>
          <NativePopover.Content>
            <NativePopover.Arrow />
            <NativePopover.Title>Details</NativePopover.Title>
            <NativePopover.Description>
              Contextual information for this control.
            </NativePopover.Description>
          </NativePopover.Content>
        </NativePopover>
      ),
      code: `import { Popover } from '@vellira-ui/react-native';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Popover
  modal
>
  <Popover.Trigger asChild>
    <NativeButton>Open popover</NativeButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Arrow and close action',
      description:
        'Adds an arrow and an explicit close control inside the popover.',
      preview: (
        <NativePopover>
          <NativePopover.Trigger asChild>
            <NativeButton>Open popover</NativeButton>
          </NativePopover.Trigger>
          <NativePopover.Content>
            <NativePopover.Arrow />
            <NativePopover.Title>Details</NativePopover.Title>
            <NativePopover.Description>
              Contextual information for this control.
            </NativePopover.Description>
            <NativePopover.Close asChild>
              <NativeButton>Close</NativeButton>
            </NativePopover.Close>
          </NativePopover.Content>
        </NativePopover>
      ),
      code: `import { Popover } from '@vellira-ui/react-native';
import { Button as NativeButton } from '@vellira-ui/react-native';

<Popover>
  <Popover.Trigger asChild>
    <NativeButton>Open popover</NativeButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
    <Popover.Close asChild>
      <NativeButton>Close</NativeButton>
    </Popover.Close>
  </Popover.Content>
</Popover>`,
    },
    {
      title: 'Separate anchor',
      description:
        'Positions content from an anchor while using a separate trigger.',
      preview: (
        <NativePopover>
          <NativeView
            style={{
              flexDirection: 'row',
              alignItems: 'center',
              gap: 16,
            }}
          >
            <NativePopover.Anchor asChild>
              <NativeView
                style={{
                  padding: 16,
                  borderWidth: 1,
                  borderStyle: 'dashed',
                  borderColor: '#d8d2f0',
                  borderRadius: 16,
                }}
              >
                <NativeText>Position relative to me</NativeText>
              </NativeView>
            </NativePopover.Anchor>

            <NativePopover.Trigger asChild>
              <NativeButton>Toggle popover</NativeButton>
            </NativePopover.Trigger>
          </NativeView>

          <NativePopover.Content>
            <NativePopover.Arrow />
            <NativePopover.Title>Separate anchor</NativePopover.Title>
            <NativePopover.Description>
              The trigger controls the state, but the content is positioned
              relative to the anchor.
            </NativePopover.Description>

            <NativePopover.Close asChild>
              <NativeButton size='sm' appearance='ghost'>
                Close
              </NativeButton>
            </NativePopover.Close>
          </NativePopover.Content>
        </NativePopover>
      ),
      code: `import { Popover } from '@vellira-ui/react-native';
import { Button as NativeButton } from '@vellira-ui/react-native';
import { Text as NativeText, View as NativeView } from 'react-native';

<Popover>
  <NativeView
    style={{
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
    }}
  >
    <Popover.Anchor asChild>
      <NativeView
        style={{
          padding: 16,
          borderWidth: 1,
          borderStyle: 'dashed',
          borderColor: '#d8d2f0',
          borderRadius: 16,
        }}
      >
        <NativeText>Position relative to me</NativeText>
      </NativeView>
    </Popover.Anchor>
  
    <Popover.Trigger asChild>
      <NativeButton>Toggle popover</NativeButton>
    </Popover.Trigger>
  </NativeView>
  
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Separate anchor</Popover.Title>
    <Popover.Description>
      The trigger controls the state, but the content is positioned relative to the anchor.
    </Popover.Description>
  
    <Popover.Close asChild>
      <NativeButton size='sm' appearance='ghost'>
        Close
      </NativeButton>
    </Popover.Close>
  </Popover.Content>
</Popover>`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
