// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ReactNode } from 'react';

import { ComponentPlayground } from '../../shared/ComponentPlayground';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';
import { PlaygroundControlsFromSchema } from '../../shared/PlaygroundControls';

import { popoverPlaygroundControls } from './popoverPlaygroundSchema';

export type PopoverPlaygroundValue = {
  open: boolean;
  modal: boolean;
};

type PopoverPlaygroundProps = {
  platform: 'react' | 'react-native';
  renderPopover: (
    value: PopoverPlaygroundValue,
    onChange: <K extends keyof PopoverPlaygroundValue>(
      key: K,
      nextValue: PopoverPlaygroundValue[K]
    ) => void
  ) => ReactNode;
};

export const initialPopoverPlaygroundValue: PopoverPlaygroundValue = {
  open: false,
  modal: false,
};

export function PopoverPlayground({
  platform,
  renderPopover,
}: PopoverPlaygroundProps) {
  const [value, setValue] = useComponentDemoState<PopoverPlaygroundValue>(
    initialPopoverPlaygroundValue
  );

  const update = (
    key: keyof PopoverPlaygroundValue,
    nextValue: PopoverPlaygroundValue[keyof PopoverPlaygroundValue]
  ) => {
    setValue({
      ...value,
      [key]: nextValue,
    });
  };

  return (
    <ComponentPlayground
      previewWidth='field'
      controls={
        <PlaygroundControlsFromSchema
          platform={platform}
          value={value}
          controls={popoverPlaygroundControls}
          onChange={update}
        />
      }
    >
      {renderPopover(value, update)}
    </ComponentPlayground>
  );
}
