// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { Popover } from '@vellira-ui/react';

import { PopoverPlayground } from './PopoverPlayground';

export function PopoverDemo() {
  return (
    <PopoverPlayground
      renderPopover={(value, onChange) => (
        <Popover
          open={value.open}
          onOpenChange={(nextValue) => onChange('open', nextValue)}
          modal={value.modal}
        >
          <Popover.Trigger>Open popover</Popover.Trigger>
          <Popover.Content>
            <Popover.Title>Details</Popover.Title>
            <Popover.Description>
              Contextual information for this control.
            </Popover.Description>
          </Popover.Content>
        </Popover>
      )}
    />
  );
}
