// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialPopoverPlaygroundValue,
  type PopoverPlaygroundValue,
} from './PopoverPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type PopoverUsageProps = {
  platform: ComponentPlatform;
};

function createPopoverCode(
  platform: ComponentPlatform,
  value: PopoverPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] = platform === 'react' ? [] : [];

  const children =
    platform === 'react'
      ? `  <Popover.Trigger asChild>
    <ReactButton>Open popover</ReactButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>`
      : `  <Popover.Trigger asChild>
    <NativeButton>Open popover</NativeButton>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Arrow />
    <Popover.Title>Details</Popover.Title>
    <Popover.Description>Contextual information for this control.</Popover.Description>
  </Popover.Content>`;

  if (value.open) {
    props.push('open');
  }

  if (value.modal) {
    props.push('modal');
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { Popover } from '${packageName}';
${
  platform === 'react'
    ? `
import { Button as ReactButton } from '@vellira-ui/react';`
    : `
import { Button as NativeButton } from '@vellira-ui/react-native';`
}

<Popover${propsText}/>`;
  }

  return `import { Popover } from '${packageName}';
${
  platform === 'react'
    ? `
import { Button as ReactButton } from '@vellira-ui/react';`
    : `
import { Button as NativeButton } from '@vellira-ui/react-native';`
}

<Popover${propsText}>
${children}
</Popover>`;
}

export function PopoverUsage({ platform }: PopoverUsageProps) {
  const [value] = useComponentDemoState<PopoverPlaygroundValue>(
    initialPopoverPlaygroundValue
  );

  const code = createPopoverCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
