// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { PopoverPlaygroundValue } from './PopoverPlayground';

export const popoverPlaygroundControls = [
  {
    type: 'toggle',
    key: 'open',
    label: 'Open',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'modal',
    label: 'Modal',
    group: 'Options',
    platforms: ['react'],
  },
] as const satisfies readonly PlaygroundControl<PopoverPlaygroundValue>[];
