// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type PopoverAccessibilityProps = {
  platform: ComponentPlatform;
};

export function PopoverAccessibility({ platform }: PopoverAccessibilityProps) {
  const reactItems = [
    {
      title: 'Trigger relationship',
      description:
        'Use trigger content and popover title or description to clarify the relationship.',
      props: ['children', 'open', 'onOpenChange'],
    },
    {
      title: 'Dismissal and focus',
      description:
        'Keep focus and dismissal predictable when content contains interactive controls.',
      props: ['modal', 'side', 'align', 'onOpenChange'],
    },
    {
      title: 'Explicit close controls',
      description:
        'Provide a close action when popover content contains interactive or multi-step content.',
      props: ['children'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Context announcement',
      description:
        'Use title and description content so screen readers can identify popover purpose.',
      props: ['children'],
    },
    {
      title: 'Placement',
      description:
        'Choose placement that keeps content near its trigger without obscuring controls.',
      props: ['side', 'align'],
    },
    {
      title: 'Explicit close controls',
      description:
        'Use a clearly labelled close action when the popover stays open for task content.',
      props: ['children'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
