// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { FormField as ReactFormField } from '@vellira-ui/react';
import { FormField as NativeFormField } from '@vellira-ui/react-native';
import { Input as ReactInput } from '@vellira-ui/react';
import { Input as NativeInput } from '@vellira-ui/react-native';

import { ComponentExamples } from '../../shared/ComponentExamples';
import type { ComponentPlatform } from '../../types';

type FormFieldExamplesProps = {
  platform: ComponentPlatform;
};

export function FormFieldExamples({ platform }: FormFieldExamplesProps) {
  const reactExamples = [
    {
      title: 'Basic',
      description: 'Labels and describes a composed input control.',
      preview: (
        <ReactFormField
          label='Email'
          description='Used for account notifications.'
        >
          <ReactInput placeholder='name@company.com' type='email' />
        </ReactFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react';
import { Input as ReactInput } from '@vellira-ui/react';

<FormField
  label='Email'
  description='Used for account notifications.'
>
  <ReactInput placeholder='name@company.com' type='email' />
</FormField>`,
    },
    {
      title: 'Compound API',
      description:
        'Composes label, description, control, and message slots explicitly.',
      preview: (
        <ReactFormField>
          <ReactFormField.Label>Email</ReactFormField.Label>
          <ReactFormField.Description>
            Used for account notifications.
          </ReactFormField.Description>
          <ReactFormField.Control>
            <ReactInput placeholder='name@company.com' type='email' />
          </ReactFormField.Control>
          <ReactFormField.Message>
            We will never share your email.
          </ReactFormField.Message>
        </ReactFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react';
import { Input as ReactInput } from '@vellira-ui/react';

<FormField>
  <FormField.Label>Email</FormField.Label>
  <FormField.Description>
    Used for account notifications.
  </FormField.Description>
  <FormField.Control>
    <ReactInput placeholder='name@company.com' type='email' />
  </FormField.Control>
  <FormField.Message>
    We will never share your email.
  </FormField.Message>
</FormField>`,
    },
    {
      title: 'Required',
      description: 'Shows required field treatment.',
      preview: (
        <ReactFormField
          label='Email'
          description='Used for account notifications.'
          required
        >
          <ReactInput placeholder='vellira-design' />
        </ReactFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react';
import { Input as ReactInput } from '@vellira-ui/react';

<FormField
  label='Email'
  description='Used for account notifications.'
  required
>
  <ReactInput placeholder='vellira-design' />
</FormField>`,
    },
    {
      title: 'Error',
      description: 'Prioritizes validation feedback below the control.',
      preview: (
        <ReactFormField
          label='Email'
          description='Used for account notifications.'
          error='Enter a valid email address.'
        >
          <ReactInput placeholder='name@company.com' type='email' />
        </ReactFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react';
import { Input as ReactInput } from '@vellira-ui/react';

<FormField
  label='Email'
  description='Used for account notifications.'
  error='Enter a valid email address.'
>
  <ReactInput placeholder='name@company.com' type='email' />
</FormField>`,
    },
    {
      title: 'Message',
      description: 'Displays non-error supporting status content.',
      preview: (
        <ReactFormField
          label='Email'
          description='Used for account notifications.'
          message='Available workspace slug.'
          messageTone='success'
          messageLive='polite'
        >
          <ReactInput placeholder='vellira-design' />
        </ReactFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react';
import { Input as ReactInput } from '@vellira-ui/react';

<FormField
  label='Email'
  description='Used for account notifications.'
  message='Available workspace slug.'
  messageTone='success'
  messageLive='polite'
>
  <ReactInput placeholder='vellira-design' />
</FormField>`,
    },
    {
      title: 'Disabled',
      description: 'Applies disabled field treatment to compatible controls.',
      preview: (
        <ReactFormField
          label='Email'
          description='Used for account notifications.'
          disabled
        >
          <ReactInput placeholder='name@company.com' type='email' />
        </ReactFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react';
import { Input as ReactInput } from '@vellira-ui/react';

<FormField
  label='Email'
  description='Used for account notifications.'
  disabled
>
  <ReactInput placeholder='name@company.com' type='email' />
</FormField>`,
    },
  ] as const;

  const nativeExamples = [
    {
      title: 'Basic',
      description: 'Labels and describes a composed input control.',
      preview: (
        <NativeFormField
          label='Email'
          description='Used for account notifications.'
        >
          <NativeInput placeholder='name@company.com' />
        </NativeFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react-native';
import { Input as NativeInput } from '@vellira-ui/react-native';

<FormField
  label='Email'
  description='Used for account notifications.'
>
  <NativeInput placeholder='name@company.com' />
</FormField>`,
    },
    {
      title: 'Compound API',
      description:
        'Composes label, description, control, and message slots explicitly.',
      preview: (
        <NativeFormField>
          <NativeFormField.Label>Email</NativeFormField.Label>
          <NativeFormField.Description>
            Used for account notifications.
          </NativeFormField.Description>
          <NativeFormField.Control>
            <NativeInput placeholder='name@company.com' />
          </NativeFormField.Control>
          <NativeFormField.Message>
            We will never share your email.
          </NativeFormField.Message>
        </NativeFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react-native';
import { Input as NativeInput } from '@vellira-ui/react-native';

<FormField>
  <FormField.Label>Email</FormField.Label>
  <FormField.Description>
    Used for account notifications.
  </FormField.Description>
  <FormField.Control>
    <NativeInput placeholder='name@company.com' />
  </FormField.Control>
  <FormField.Message>
    We will never share your email.
  </FormField.Message>
</FormField>`,
    },
    {
      title: 'Required',
      description: 'Shows required field treatment.',
      preview: (
        <NativeFormField
          label='Email'
          description='Used for account notifications.'
          required
        >
          <NativeInput placeholder='vellira-design' />
        </NativeFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react-native';
import { Input as NativeInput } from '@vellira-ui/react-native';

<FormField
  label='Email'
  description='Used for account notifications.'
  required
>
  <NativeInput placeholder='vellira-design' />
</FormField>`,
    },
    {
      title: 'Error',
      description: 'Prioritizes validation feedback below the control.',
      preview: (
        <NativeFormField
          label='Email'
          description='Used for account notifications.'
          error='Enter a valid email address.'
        >
          <NativeInput placeholder='name@company.com' />
        </NativeFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react-native';
import { Input as NativeInput } from '@vellira-ui/react-native';

<FormField
  label='Email'
  description='Used for account notifications.'
  error='Enter a valid email address.'
>
  <NativeInput placeholder='name@company.com' />
</FormField>`,
    },
    {
      title: 'Message',
      description: 'Displays non-error supporting status content.',
      preview: (
        <NativeFormField
          label='Email'
          description='Used for account notifications.'
          message='Available workspace slug.'
          messageTone='success'
          messageLive='polite'
        >
          <NativeInput placeholder='vellira-design' />
        </NativeFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react-native';
import { Input as NativeInput } from '@vellira-ui/react-native';

<FormField
  label='Email'
  description='Used for account notifications.'
  message='Available workspace slug.'
  messageTone='success'
  messageLive='polite'
>
  <NativeInput placeholder='vellira-design' />
</FormField>`,
    },
    {
      title: 'Disabled',
      description: 'Applies disabled field treatment to compatible controls.',
      preview: (
        <NativeFormField
          label='Email'
          description='Used for account notifications.'
          disabled
        >
          <NativeInput placeholder='name@company.com' />
        </NativeFormField>
      ),
      code: `import { FormField } from '@vellira-ui/react-native';
import { Input as NativeInput } from '@vellira-ui/react-native';

<FormField
  label='Email'
  description='Used for account notifications.'
  disabled
>
  <NativeInput placeholder='name@company.com' />
</FormField>`,
    },
  ] as const;

  return (
    <ComponentExamples
      items={platform === 'react' ? reactExamples : nativeExamples}
    />
  );
}
