// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentAccessibility } from '../../shared/ComponentAccessibility';

type FormFieldAccessibilityProps = {
  platform: ComponentPlatform;
};

export function FormFieldAccessibility({
  platform,
}: FormFieldAccessibilityProps) {
  const reactItems = [
    {
      title: 'Control relationship',
      description:
        'FormField connects label, description, error, and message ids to compatible controls.',
      props: ['label', 'description', 'error', 'message'],
    },
    {
      title: 'Validation priority',
      description:
        'Error content takes precedence over supporting messages and should explain how to recover.',
      props: ['error', 'invalid', 'message'],
    },
    {
      title: 'Required and disabled state',
      description:
        'Use required and disabled on the field so compatible controls inherit the same state.',
      props: ['required', 'disabled'],
    },
  ] as const;

  const nativeItems = [
    {
      title: 'Visible field structure',
      description:
        'Use label, description, and error content so the control has clear surrounding context.',
      props: ['label', 'description', 'error'],
    },
    {
      title: 'State propagation',
      description:
        'Compatible Vellira controls inherit disabled, invalid, required, and size through context.',
      props: ['disabled', 'invalid', 'required', 'size'],
    },
    {
      title: 'Accessible state',
      description:
        'Compatible controls announce required and invalid state through React Native accessibility semantics.',
      props: ['required', 'invalid'],
    },
  ] as const;

  return (
    <ComponentAccessibility
      items={platform === 'react' ? reactItems : nativeItems}
    />
  );
}
