// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { FormField } from '@vellira-ui/react';
import { Input as ReactInput } from '@vellira-ui/react';

import { FormFieldPlayground } from './FormFieldPlayground';

export function FormFieldDemo() {
  return (
    <FormFieldPlayground
      platform='react'
      renderFormField={(value) => (
        <FormField
          label={value.label || undefined}
          description={value.description || undefined}
          error={value.error || undefined}
          message={value.message || undefined}
          messageTone={value.messageTone}
          messageLive={value.messageLive}
          required={value.required}
          disabled={value.disabled}
          invalid={value.invalid}
          size={value.size}
        >
          <ReactInput placeholder='name@company.com' type='email' />
        </FormField>
      )}
    />
  );
}
