// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

import type { PlaygroundControl } from '../../shared/PlaygroundControls';

import type { FormFieldPlaygroundValue } from './FormFieldPlayground';

export const formFieldPlaygroundControls = [
  {
    type: 'text',
    key: 'label',
    label: 'Label',
  },
  {
    type: 'text',
    key: 'description',
    label: 'Description',
  },
  {
    type: 'text',
    key: 'error',
    label: 'Error',
  },
  {
    type: 'text',
    key: 'message',
    label: 'Message',
  },
  {
    type: 'select',
    key: 'messageTone',
    label: 'Message Tone',
    options: ['neutral', 'success', 'warning', 'danger'],
  },
  {
    type: 'select',
    key: 'messageLive',
    label: 'Message Live',
    options: ['off', 'polite'],
  },
  {
    type: 'toggle',
    key: 'required',
    label: 'Required',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'disabled',
    label: 'Disabled',
    group: 'Options',
  },
  {
    type: 'toggle',
    key: 'invalid',
    label: 'Invalid',
    group: 'Options',
  },
  {
    type: 'select',
    key: 'size',
    label: 'Size',
    options: ['sm', 'md', 'lg'],
  },
] as const satisfies readonly PlaygroundControl<FormFieldPlaygroundValue>[];
