// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import type { ComponentPlatform } from '../../types';

import { ComponentCodeBlock } from '../../shared/ComponentCodeBlock';
import { useComponentDemoState } from '../../shared/ComponentDemoStateProvider';

import {
  initialFormFieldPlaygroundValue,
  type FormFieldPlaygroundValue,
} from './FormFieldPlayground';

import styles from '../../shared/ComponentUsage.module.css';

type FormFieldUsageProps = {
  platform: ComponentPlatform;
};

function createFormFieldCode(
  platform: ComponentPlatform,
  value: FormFieldPlaygroundValue
) {
  const packageName =
    platform === 'react' ? '@vellira-ui/react' : '@vellira-ui/react-native';

  const props: string[] =
    platform === 'react'
      ? [`label='Email'`, `description='Used for account notifications.'`]
      : [`label='Email'`, `description='Used for account notifications.'`];

  const children =
    platform === 'react'
      ? `  <ReactInput placeholder='name@company.com' type='email' />`
      : `  <NativeInput placeholder='name@company.com' />`;

  if (value.label) {
    props.push(`label='${value.label}'`);
  }

  if (value.description) {
    props.push(`description='${value.description}'`);
  }

  if (value.error) {
    props.push(`error='${value.error}'`);
  }

  if (value.message) {
    props.push(`message='${value.message}'`);
  }

  if (value.messageTone !== 'neutral') {
    props.push(`messageTone='${value.messageTone}'`);
  }

  if (value.messageLive !== 'off') {
    props.push(`messageLive='${value.messageLive}'`);
  }

  if (value.required) {
    props.push('required');
  }

  if (value.disabled) {
    props.push('disabled');
  }

  if (value.invalid) {
    props.push('invalid');
  }

  if (value.size !== 'md') {
    props.push(`size='${value.size}'`);
  }

  const propsText = props.length === 0 ? '' : `\n  ${props.join('\n  ')}\n`;

  if (!children) {
    return `import { FormField } from '${packageName}';
${
  platform === 'react'
    ? `
import { Input as ReactInput } from '@vellira-ui/react';`
    : `
import { Input as NativeInput } from '@vellira-ui/react-native';`
}

<FormField${propsText}/>`;
  }

  return `import { FormField } from '${packageName}';
${
  platform === 'react'
    ? `
import { Input as ReactInput } from '@vellira-ui/react';`
    : `
import { Input as NativeInput } from '@vellira-ui/react-native';`
}

<FormField${propsText}>
${children}
</FormField>`;
}

export function FormFieldUsage({ platform }: FormFieldUsageProps) {
  const [value] = useComponentDemoState<FormFieldPlaygroundValue>(
    initialFormFieldPlaygroundValue
  );

  const code = createFormFieldCode(platform, value);

  return (
    <section className={styles.root}>
      <div className={styles.header}>
        <h2 className={styles.title}>Usage</h2>

        <p className={styles.description}>
          Import the component and configure it with the same props used in the
          playground.
        </p>
      </div>

      <ComponentCodeBlock code={code} />
    </section>
  );
}
