// Generated by scripts/generators/component-page/create-component-page.ts.
// Do not edit manually.

'use client';

import { FormField } from '@vellira-ui/react-native';
import { Input as NativeInput } from '@vellira-ui/react-native';

import { FormFieldPlayground } from './FormFieldPlayground';

export function NativeFormFieldDemo() {
  return (
    <FormFieldPlayground
      renderFormField={(value) => (
        <FormField
          label={value.label || undefined}
          description={value.description || undefined}
          error={value.error || undefined}
          message={value.message || undefined}
          messageTone={value.messageTone}
          messageLive={value.messageLive}
          required={value.required}
          disabled={value.disabled}
          invalid={value.invalid}
          size={value.size}
        >
          <NativeInput placeholder='name@company.com' />
        </FormField>
      )}
    />
  );
}
